// Code generated by go-swagger; DO NOT EDIT.

package channel_currency_assignments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostChannelsCurrencyAssignmentsReader is a Reader for the PostChannelsCurrencyAssignments structure.
type PostChannelsCurrencyAssignmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostChannelsCurrencyAssignmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostChannelsCurrencyAssignmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewPostChannelsCurrencyAssignmentsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostChannelsCurrencyAssignmentsOK creates a PostChannelsCurrencyAssignmentsOK with default headers values
func NewPostChannelsCurrencyAssignmentsOK() *PostChannelsCurrencyAssignmentsOK {
	return &PostChannelsCurrencyAssignmentsOK{}
}

/*PostChannelsCurrencyAssignmentsOK handles this case with default header values.

PostChannelsCurrencyAssignmentsOK post channels currency assignments o k
*/
type PostChannelsCurrencyAssignmentsOK struct {
	Payload *PostChannelsCurrencyAssignmentsOKBody
}

func (o *PostChannelsCurrencyAssignmentsOK) Error() string {
	return fmt.Sprintf("[POST /channels/currency-assignments][%d] postChannelsCurrencyAssignmentsOK  %+v", 200, o.Payload)
}

func (o *PostChannelsCurrencyAssignmentsOK) GetPayload() *PostChannelsCurrencyAssignmentsOKBody {
	return o.Payload
}

func (o *PostChannelsCurrencyAssignmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostChannelsCurrencyAssignmentsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostChannelsCurrencyAssignmentsUnprocessableEntity creates a PostChannelsCurrencyAssignmentsUnprocessableEntity with default headers values
func NewPostChannelsCurrencyAssignmentsUnprocessableEntity() *PostChannelsCurrencyAssignmentsUnprocessableEntity {
	return &PostChannelsCurrencyAssignmentsUnprocessableEntity{}
}

/*PostChannelsCurrencyAssignmentsUnprocessableEntity handles this case with default header values.

Unprocessable Entity (WebDAV)
*/
type PostChannelsCurrencyAssignmentsUnprocessableEntity struct {
	Payload interface{}
}

func (o *PostChannelsCurrencyAssignmentsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /channels/currency-assignments][%d] postChannelsCurrencyAssignmentsUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *PostChannelsCurrencyAssignmentsUnprocessableEntity) GetPayload() interface{} {
	return o.Payload
}

func (o *PostChannelsCurrencyAssignmentsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostChannelsCurrencyAssignmentsOKBody currencyAssignments_Resp
swagger:model PostChannelsCurrencyAssignmentsOKBody
*/
type PostChannelsCurrencyAssignmentsOKBody struct {

	// data
	Data []*PostChannelsCurrencyAssignmentsOKBodyDataItems0 `json:"data"`

	// meta
	Meta interface{} `json:"meta,omitempty"`
}

// Validate validates this post channels currency assignments o k body
func (o *PostChannelsCurrencyAssignmentsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostChannelsCurrencyAssignmentsOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("postChannelsCurrencyAssignmentsOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostChannelsCurrencyAssignmentsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostChannelsCurrencyAssignmentsOKBody) UnmarshalBinary(b []byte) error {
	var res PostChannelsCurrencyAssignmentsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostChannelsCurrencyAssignmentsOKBodyDataItems0 post channels currency assignments o k body data items0
swagger:model PostChannelsCurrencyAssignmentsOKBodyDataItems0
*/
type PostChannelsCurrencyAssignmentsOKBodyDataItems0 struct {

	// The ID of the channel
	// Required: true
	// Minimum: 0
	// Multiple Of: 1
	ChannelID *float64 `json:"channel_id"`

	// Default currency for the channel in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) three character alphabetic format. Will be used on storefront when other currencies cannot
	// Required: true
	// Min Length: 1
	DefaultCurrency *string `json:"default_currency"`

	// Currencies that are enabled for the given channel in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) three character alphabetic format.
	// Required: true
	EnabledCurrencies []string `json:"enabled_currencies"`
}

// Validate validates this post channels currency assignments o k body data items0
func (o *PostChannelsCurrencyAssignmentsOKBodyDataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateChannelID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDefaultCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateEnabledCurrencies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostChannelsCurrencyAssignmentsOKBodyDataItems0) validateChannelID(formats strfmt.Registry) error {

	if err := validate.Required("channel_id", "body", o.ChannelID); err != nil {
		return err
	}

	if err := validate.Minimum("channel_id", "body", float64(*o.ChannelID), 0, false); err != nil {
		return err
	}

	if err := validate.MultipleOf("channel_id", "body", float64(*o.ChannelID), 1); err != nil {
		return err
	}

	return nil
}

func (o *PostChannelsCurrencyAssignmentsOKBodyDataItems0) validateDefaultCurrency(formats strfmt.Registry) error {

	if err := validate.Required("default_currency", "body", o.DefaultCurrency); err != nil {
		return err
	}

	if err := validate.MinLength("default_currency", "body", string(*o.DefaultCurrency), 1); err != nil {
		return err
	}

	return nil
}

func (o *PostChannelsCurrencyAssignmentsOKBodyDataItems0) validateEnabledCurrencies(formats strfmt.Registry) error {

	if err := validate.Required("enabled_currencies", "body", o.EnabledCurrencies); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostChannelsCurrencyAssignmentsOKBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostChannelsCurrencyAssignmentsOKBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res PostChannelsCurrencyAssignmentsOKBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostChannelsCurrencyAssignmentsParamsBodyItems0 post channels currency assignments params body items0
swagger:model PostChannelsCurrencyAssignmentsParamsBodyItems0
*/
type PostChannelsCurrencyAssignmentsParamsBodyItems0 struct {

	// The ID of the channel
	// Required: true
	// Minimum: 0
	// Multiple Of: 1
	ChannelID *float64 `json:"channel_id"`

	// Default currency for the channel in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) three character alphabetic format. Will be used on storefront when other currencies cannot
	// Required: true
	// Min Length: 1
	DefaultCurrency *string `json:"default_currency"`

	// Currencies that are enabled for the given channel in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) three character alphabetic format.
	// Required: true
	EnabledCurrencies []string `json:"enabled_currencies"`
}

// Validate validates this post channels currency assignments params body items0
func (o *PostChannelsCurrencyAssignmentsParamsBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateChannelID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDefaultCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateEnabledCurrencies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostChannelsCurrencyAssignmentsParamsBodyItems0) validateChannelID(formats strfmt.Registry) error {

	if err := validate.Required("channel_id", "body", o.ChannelID); err != nil {
		return err
	}

	if err := validate.Minimum("channel_id", "body", float64(*o.ChannelID), 0, false); err != nil {
		return err
	}

	if err := validate.MultipleOf("channel_id", "body", float64(*o.ChannelID), 1); err != nil {
		return err
	}

	return nil
}

func (o *PostChannelsCurrencyAssignmentsParamsBodyItems0) validateDefaultCurrency(formats strfmt.Registry) error {

	if err := validate.Required("default_currency", "body", o.DefaultCurrency); err != nil {
		return err
	}

	if err := validate.MinLength("default_currency", "body", string(*o.DefaultCurrency), 1); err != nil {
		return err
	}

	return nil
}

func (o *PostChannelsCurrencyAssignmentsParamsBodyItems0) validateEnabledCurrencies(formats strfmt.Registry) error {

	if err := validate.Required("enabled_currencies", "body", o.EnabledCurrencies); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostChannelsCurrencyAssignmentsParamsBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostChannelsCurrencyAssignmentsParamsBodyItems0) UnmarshalBinary(b []byte) error {
	var res PostChannelsCurrencyAssignmentsParamsBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
