// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ChannelConfigMetaFull Optional channel configuration object.
//
// swagger:model channelConfigMeta_Full
type ChannelConfigMetaFull struct {

	// app
	App *ChannelConfigMetaFullApp `json:"app,omitempty"`
}

// Validate validates this channel config meta full
func (m *ChannelConfigMetaFull) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChannelConfigMetaFull) validateApp(formats strfmt.Registry) error {

	if swag.IsZero(m.App) { // not required
		return nil
	}

	if m.App != nil {
		if err := m.App.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("app")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ChannelConfigMetaFull) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelConfigMetaFull) UnmarshalBinary(b []byte) error {
	var res ChannelConfigMetaFull
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ChannelConfigMetaFullApp A [channel app](https://developer.bigcommerce.com/api-docs/channels/overview#channel-apps) config object for optionally configuring the channel's user interface in the control panel.
//
// swagger:model ChannelConfigMetaFullApp
type ChannelConfigMetaFullApp struct {

	// The unique `id` given to an app registered in [DevTools](https://devtools.bigcommerce.com/); used to create links to the app in channel manager. [Learn how to find an App's ID](https://developer.bigcommerce.com/api-docs/apps/tutorials/id).
	// Required: true
	ID *int64 `json:"id"`

	// if set, when the app is loaded within the control panel, the navigation `sections` will be directly embedded in the control panel navigation.
	Sections []*ChannelConfigMetaFullAppSectionsItems0 `json:"sections"`
}

// Validate validates this channel config meta full app
func (m *ChannelConfigMetaFullApp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSections(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChannelConfigMetaFullApp) validateID(formats strfmt.Registry) error {

	if err := validate.Required("app"+"."+"id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *ChannelConfigMetaFullApp) validateSections(formats strfmt.Registry) error {

	if swag.IsZero(m.Sections) { // not required
		return nil
	}

	for i := 0; i < len(m.Sections); i++ {
		if swag.IsZero(m.Sections[i]) { // not required
			continue
		}

		if m.Sections[i] != nil {
			if err := m.Sections[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("app" + "." + "sections" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ChannelConfigMetaFullApp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelConfigMetaFullApp) UnmarshalBinary(b []byte) error {
	var res ChannelConfigMetaFullApp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// ChannelConfigMetaFullAppSectionsItems0 channel config meta full app sections items0
//
// swagger:model ChannelConfigMetaFullAppSectionsItems0
type ChannelConfigMetaFullAppSectionsItems0 struct {

	// The value that will be passed to the app's iFrame in the URL and will allow the app to display the appropriate section within the app iFrame in the control panel.
	QueryPath string `json:"query_path,omitempty"`

	// The title of the navigation section.
	Title string `json:"title,omitempty"`
}

// Validate validates this channel config meta full app sections items0
func (m *ChannelConfigMetaFullAppSectionsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChannelConfigMetaFullAppSectionsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelConfigMetaFullAppSectionsItems0) UnmarshalBinary(b []byte) error {
	var res ChannelConfigMetaFullAppSectionsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
