// Code generated by go-swagger; DO NOT EDIT.

package order_shipments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetCountShipmentsReader is a Reader for the GetCountShipments structure.
type GetCountShipmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCountShipmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCountShipmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCountShipmentsOK creates a GetCountShipmentsOK with default headers values
func NewGetCountShipmentsOK() *GetCountShipmentsOK {
	return &GetCountShipmentsOK{}
}

/*GetCountShipmentsOK handles this case with default header values.

GetCountShipmentsOK get count shipments o k
*/
type GetCountShipmentsOK struct {
	Payload *GetCountShipmentsOKBody
}

func (o *GetCountShipmentsOK) Error() string {
	return fmt.Sprintf("[GET /orders/{order_id}/shipments/count][%d] getCountShipmentsOK  %+v", 200, o.Payload)
}

func (o *GetCountShipmentsOK) GetPayload() *GetCountShipmentsOKBody {
	return o.Payload
}

func (o *GetCountShipmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCountShipmentsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetCountShipmentsOKBody orderCount
swagger:model GetCountShipmentsOKBody
*/
type GetCountShipmentsOKBody struct {

	// count
	Count float64 `json:"count,omitempty"`
}

// Validate validates this get count shipments o k body
func (o *GetCountShipmentsOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCountShipmentsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCountShipmentsOKBody) UnmarshalBinary(b []byte) error {
	var res GetCountShipmentsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
