// Code generated by go-swagger; DO NOT EDIT.

package order_shipments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateOrderShipmentReader is a Reader for the UpdateOrderShipment structure.
type UpdateOrderShipmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateOrderShipmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateOrderShipmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateOrderShipmentOK creates a UpdateOrderShipmentOK with default headers values
func NewUpdateOrderShipmentOK() *UpdateOrderShipmentOK {
	return &UpdateOrderShipmentOK{}
}

/*UpdateOrderShipmentOK handles this case with default header values.

UpdateOrderShipmentOK update order shipment o k
*/
type UpdateOrderShipmentOK struct {
	Payload *UpdateOrderShipmentOKBody
}

func (o *UpdateOrderShipmentOK) Error() string {
	return fmt.Sprintf("[PUT /orders/{order_id}/shipments/{shipment_id}][%d] updateOrderShipmentOK  %+v", 200, o.Payload)
}

func (o *UpdateOrderShipmentOK) GetPayload() *UpdateOrderShipmentOKBody {
	return o.Payload
}

func (o *UpdateOrderShipmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UpdateOrderShipmentOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*UpdateOrderShipmentBody orderShipment_Post
swagger:model UpdateOrderShipmentBody
*/
type UpdateOrderShipmentBody struct {

	// Comments the shipper wishes to add.
	Comments string `json:"comments,omitempty"`

	// The items in the shipment. This object has the following members, all integer: order_product_id (required), quantity (required), product_id (read-only). A sample items value might be: [ {"order_product_id":16,"product_id": 0,"quantity":2} ]
	Items []*UpdateOrderShipmentParamsBodyItemsItems0 `json:"items"`

	// ID of the desired `shipping_address` associated with the shipment.
	OrderAddressID int64 `json:"order_address_id,omitempty"`

	// Additional information to describe the method of shipment (ex. Standard, Ship by Weight, Custom Shipment). Can be used for live quotes from certain shipping providers.
	// If different from `shipping_provider`, `shipping_method` should correspond to `tracking_carrier`.
	//
	ShippingMethod string `json:"shipping_method,omitempty"`

	// Enum of the BigCommerce shipping-carrier integration/module.
	// Enum: [auspost canadapost endicia usps fedex ups upsready upsonline shipperhq]
	ShippingProvider string `json:"shipping_provider,omitempty"`

	// Tracking Carrier
	//
	// Tracking carrier for the shipment.
	// Acceptable values include an empty string (`""`) or one of the valid tracking-carrier values viewable [here](https://docs.google.com/spreadsheets/d/1w9c_aECSCGyf-oOrvGeUniDl-ARGKemfZl0qSsav8D4/pubhtml?gid=0&single=true) and downloadable as a .CSV file [here](https://docs.google.com/spreadsheets/d/1mTueEynfcEmwsU2y2Jd2MX-8GKwNZrmlRMBcIElg9aY/pub?gid=0&single=true&output=csv).
	TrackingCarrier string `json:"tracking_carrier,omitempty"`

	// Tracking number of the shipment.
	TrackingNumber string `json:"tracking_number,omitempty"`
}

// Validate validates this update order shipment body
func (o *UpdateOrderShipmentBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateShippingProvider(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateOrderShipmentBody) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(o.Items) { // not required
		return nil
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("body" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var updateOrderShipmentBodyTypeShippingProviderPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["auspost","canadapost","endicia","usps","fedex","ups","upsready","upsonline","shipperhq"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateOrderShipmentBodyTypeShippingProviderPropEnum = append(updateOrderShipmentBodyTypeShippingProviderPropEnum, v)
	}
}

const (

	// UpdateOrderShipmentBodyShippingProviderAuspost captures enum value "auspost"
	UpdateOrderShipmentBodyShippingProviderAuspost string = "auspost"

	// UpdateOrderShipmentBodyShippingProviderCanadapost captures enum value "canadapost"
	UpdateOrderShipmentBodyShippingProviderCanadapost string = "canadapost"

	// UpdateOrderShipmentBodyShippingProviderEndicia captures enum value "endicia"
	UpdateOrderShipmentBodyShippingProviderEndicia string = "endicia"

	// UpdateOrderShipmentBodyShippingProviderUsps captures enum value "usps"
	UpdateOrderShipmentBodyShippingProviderUsps string = "usps"

	// UpdateOrderShipmentBodyShippingProviderFedex captures enum value "fedex"
	UpdateOrderShipmentBodyShippingProviderFedex string = "fedex"

	// UpdateOrderShipmentBodyShippingProviderUps captures enum value "ups"
	UpdateOrderShipmentBodyShippingProviderUps string = "ups"

	// UpdateOrderShipmentBodyShippingProviderUpsready captures enum value "upsready"
	UpdateOrderShipmentBodyShippingProviderUpsready string = "upsready"

	// UpdateOrderShipmentBodyShippingProviderUpsonline captures enum value "upsonline"
	UpdateOrderShipmentBodyShippingProviderUpsonline string = "upsonline"

	// UpdateOrderShipmentBodyShippingProviderShipperhq captures enum value "shipperhq"
	UpdateOrderShipmentBodyShippingProviderShipperhq string = "shipperhq"
)

// prop value enum
func (o *UpdateOrderShipmentBody) validateShippingProviderEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, updateOrderShipmentBodyTypeShippingProviderPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *UpdateOrderShipmentBody) validateShippingProvider(formats strfmt.Registry) error {

	if swag.IsZero(o.ShippingProvider) { // not required
		return nil
	}

	// value enum
	if err := o.validateShippingProviderEnum("body"+"."+"shipping_provider", "body", o.ShippingProvider); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateOrderShipmentBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateOrderShipmentBody) UnmarshalBinary(b []byte) error {
	var res UpdateOrderShipmentBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateOrderShipmentOKBody orderShipment
swagger:model UpdateOrderShipmentOKBody
*/
type UpdateOrderShipmentOKBody struct {

	// billing address
	BillingAddress *UpdateOrderShipmentOKBodyBillingAddress `json:"billing_address,omitempty"`

	// Comments the shipper wishes to add.
	Comments string `json:"comments,omitempty"`

	// ID of this order’s customer.
	CustomerID int64 `json:"customer_id,omitempty"`

	// Creation date for the shipment.
	DateCreated string `json:"date_created,omitempty"`

	// Shipment ID.
	ID int64 `json:"id,omitempty"`

	// The items in the shipment. This object has the following members, all integer: order_product_id (required), quantity (required), product_id (read-only). A sample items value might be: [ {"order_product_id":16,"product_id": 0,"quantity":2} ]
	Items []*UpdateOrderShipmentOKBodyItemsItems0 `json:"items"`

	// ID of the desired `shipping_address` associated with the shipment.
	OrderAddressID int64 `json:"order_address_id,omitempty"`

	// ID of the order associated with this shipment.
	OrderID int64 `json:"order_id,omitempty"`

	// shipping address
	ShippingAddress *UpdateOrderShipmentOKBodyShippingAddress `json:"shipping_address,omitempty"`

	// Additional information to describe the method of shipment (ex. Standard, Ship by Weight, Custom Shipment). Can be used for live quotes from certain shipping providers.
	// If different from `shipping_provider`, `shipping_method` should correspond to `tracking_carrier`.
	ShippingMethod string `json:"shipping_method,omitempty"`

	// Enum of the BigCommerce shipping-carrier integration/module.
	// Enum: [auspost canadapost endicia usps fedex ups upsready upsonline shipperhq  ]
	ShippingProvider string `json:"shipping_provider,omitempty"`

	// Tracking Carrier
	//
	// Tracking carrier for the shipment.
	// Acceptable values include an empty string (`""`) or one of the valid tracking-carrier values viewable [here](https://docs.google.com/spreadsheets/d/1w9c_aECSCGyf-oOrvGeUniDl-ARGKemfZl0qSsav8D4/pubhtml?gid=0&single=true) and downloadable as a .CSV file [here](https://docs.google.com/spreadsheets/d/1mTueEynfcEmwsU2y2Jd2MX-8GKwNZrmlRMBcIElg9aY/pub?gid=0&single=true&output=csv).
	TrackingCarrier string `json:"tracking_carrier,omitempty"`

	// Returns a tracking link from the shipping service.
	TrackingLink string `json:"tracking_link,omitempty"`

	// Tracking number of the shipment.
	TrackingNumber string `json:"tracking_number,omitempty"`
}

// Validate validates this update order shipment o k body
func (o *UpdateOrderShipmentOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBillingAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateShippingAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateShippingProvider(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateOrderShipmentOKBody) validateBillingAddress(formats strfmt.Registry) error {

	if swag.IsZero(o.BillingAddress) { // not required
		return nil
	}

	if o.BillingAddress != nil {
		if err := o.BillingAddress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updateOrderShipmentOK" + "." + "billing_address")
			}
			return err
		}
	}

	return nil
}

func (o *UpdateOrderShipmentOKBody) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(o.Items) { // not required
		return nil
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("updateOrderShipmentOK" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateOrderShipmentOKBody) validateShippingAddress(formats strfmt.Registry) error {

	if swag.IsZero(o.ShippingAddress) { // not required
		return nil
	}

	if o.ShippingAddress != nil {
		if err := o.ShippingAddress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updateOrderShipmentOK" + "." + "shipping_address")
			}
			return err
		}
	}

	return nil
}

var updateOrderShipmentOKBodyTypeShippingProviderPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["auspost","canadapost","endicia","usps","fedex","ups","upsready","upsonline","shipperhq"," "]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateOrderShipmentOKBodyTypeShippingProviderPropEnum = append(updateOrderShipmentOKBodyTypeShippingProviderPropEnum, v)
	}
}

const (

	// UpdateOrderShipmentOKBodyShippingProviderAuspost captures enum value "auspost"
	UpdateOrderShipmentOKBodyShippingProviderAuspost string = "auspost"

	// UpdateOrderShipmentOKBodyShippingProviderCanadapost captures enum value "canadapost"
	UpdateOrderShipmentOKBodyShippingProviderCanadapost string = "canadapost"

	// UpdateOrderShipmentOKBodyShippingProviderEndicia captures enum value "endicia"
	UpdateOrderShipmentOKBodyShippingProviderEndicia string = "endicia"

	// UpdateOrderShipmentOKBodyShippingProviderUsps captures enum value "usps"
	UpdateOrderShipmentOKBodyShippingProviderUsps string = "usps"

	// UpdateOrderShipmentOKBodyShippingProviderFedex captures enum value "fedex"
	UpdateOrderShipmentOKBodyShippingProviderFedex string = "fedex"

	// UpdateOrderShipmentOKBodyShippingProviderUps captures enum value "ups"
	UpdateOrderShipmentOKBodyShippingProviderUps string = "ups"

	// UpdateOrderShipmentOKBodyShippingProviderUpsready captures enum value "upsready"
	UpdateOrderShipmentOKBodyShippingProviderUpsready string = "upsready"

	// UpdateOrderShipmentOKBodyShippingProviderUpsonline captures enum value "upsonline"
	UpdateOrderShipmentOKBodyShippingProviderUpsonline string = "upsonline"

	// UpdateOrderShipmentOKBodyShippingProviderShipperhq captures enum value "shipperhq"
	UpdateOrderShipmentOKBodyShippingProviderShipperhq string = "shipperhq"

	// UpdateOrderShipmentOKBodyShippingProvider captures enum value " "
	UpdateOrderShipmentOKBodyShippingProvider string = " "
)

// prop value enum
func (o *UpdateOrderShipmentOKBody) validateShippingProviderEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, updateOrderShipmentOKBodyTypeShippingProviderPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *UpdateOrderShipmentOKBody) validateShippingProvider(formats strfmt.Registry) error {

	if swag.IsZero(o.ShippingProvider) { // not required
		return nil
	}

	// value enum
	if err := o.validateShippingProviderEnum("updateOrderShipmentOK"+"."+"shipping_provider", "body", o.ShippingProvider); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateOrderShipmentOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateOrderShipmentOKBody) UnmarshalBinary(b []byte) error {
	var res UpdateOrderShipmentOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateOrderShipmentOKBodyBillingAddress billingAddress_Base
swagger:model UpdateOrderShipmentOKBodyBillingAddress
*/
type UpdateOrderShipmentOKBodyBillingAddress struct {

	// city
	City string `json:"city,omitempty"`

	// company
	Company string `json:"company,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// country iso2
	CountryIso2 string `json:"country_iso2,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// phone
	Phone string `json:"phone,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// street 1
	Street1 string `json:"street_1,omitempty"`

	// street 2
	Street2 string `json:"street_2,omitempty"`

	// zip
	Zip string `json:"zip,omitempty"`
}

// Validate validates this update order shipment o k body billing address
func (o *UpdateOrderShipmentOKBodyBillingAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateOrderShipmentOKBodyBillingAddress) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateOrderShipmentOKBodyBillingAddress) UnmarshalBinary(b []byte) error {
	var res UpdateOrderShipmentOKBodyBillingAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateOrderShipmentOKBodyItemsItems0 update order shipment o k body items items0
swagger:model UpdateOrderShipmentOKBodyItemsItems0
*/
type UpdateOrderShipmentOKBodyItemsItems0 struct {

	// order product id
	OrderProductID int64 `json:"order_product_id,omitempty"`

	// product id
	ProductID int64 `json:"product_id,omitempty"`

	// quantity
	Quantity float64 `json:"quantity,omitempty"`
}

// Validate validates this update order shipment o k body items items0
func (o *UpdateOrderShipmentOKBodyItemsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateOrderShipmentOKBodyItemsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateOrderShipmentOKBodyItemsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateOrderShipmentOKBodyItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateOrderShipmentOKBodyShippingAddress shippingAddress_Base
swagger:model UpdateOrderShipmentOKBodyShippingAddress
*/
type UpdateOrderShipmentOKBodyShippingAddress struct {

	// city
	City string `json:"city,omitempty"`

	// company
	Company string `json:"company,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// 2-letter ISO Alpha-2 code for the country.
	CountryIso2 string `json:"country_iso2,omitempty"`

	// Recipient's email address.
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// Recipient's telephone number.
	Phone string `json:"phone,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// Street address (first line).
	Street1 string `json:"street_1,omitempty"`

	// Street address (second line).
	Street2 string `json:"street_2,omitempty"`

	// Zip or postal code, as a string.
	Zip string `json:"zip,omitempty"`
}

// Validate validates this update order shipment o k body shipping address
func (o *UpdateOrderShipmentOKBodyShippingAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateOrderShipmentOKBodyShippingAddress) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateOrderShipmentOKBodyShippingAddress) UnmarshalBinary(b []byte) error {
	var res UpdateOrderShipmentOKBodyShippingAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateOrderShipmentParamsBodyItemsItems0 update order shipment params body items items0
swagger:model UpdateOrderShipmentParamsBodyItemsItems0
*/
type UpdateOrderShipmentParamsBodyItemsItems0 struct {

	// order product id
	OrderProductID int64 `json:"order_product_id,omitempty"`

	// product id
	ProductID int64 `json:"product_id,omitempty"`

	// quantity
	Quantity float64 `json:"quantity,omitempty"`
}

// Validate validates this update order shipment params body items items0
func (o *UpdateOrderShipmentParamsBodyItemsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateOrderShipmentParamsBodyItemsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateOrderShipmentParamsBodyItemsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateOrderShipmentParamsBodyItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
