// Code generated by go-swagger; DO NOT EDIT.

package subscribers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUpdateSubscriberParams creates a new UpdateSubscriberParams object
// with the default values initialized.
func NewUpdateSubscriberParams() *UpdateSubscriberParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &UpdateSubscriberParams{
		Accept:      &acceptDefault,
		ContentType: &contentTypeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSubscriberParamsWithTimeout creates a new UpdateSubscriberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateSubscriberParamsWithTimeout(timeout time.Duration) *UpdateSubscriberParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &UpdateSubscriberParams{
		Accept:      &acceptDefault,
		ContentType: &contentTypeDefault,

		timeout: timeout,
	}
}

// NewUpdateSubscriberParamsWithContext creates a new UpdateSubscriberParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateSubscriberParamsWithContext(ctx context.Context) *UpdateSubscriberParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &UpdateSubscriberParams{
		Accept:      &acceptDefault,
		ContentType: &contentTypeDefault,

		Context: ctx,
	}
}

// NewUpdateSubscriberParamsWithHTTPClient creates a new UpdateSubscriberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateSubscriberParamsWithHTTPClient(client *http.Client) *UpdateSubscriberParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &UpdateSubscriberParams{
		Accept:      &acceptDefault,
		ContentType: &contentTypeDefault,
		HTTPClient:  client,
	}
}

/*UpdateSubscriberParams contains all the parameters to send to the API endpoint
for the update subscriber operation typically these are written to a http.Request
*/
type UpdateSubscriberParams struct {

	/*Accept*/
	Accept *string
	/*ContentType*/
	ContentType *string
	/*Subscriber*/
	Subscriber UpdateSubscriberBody
	/*SubscriberID
	  The ID of the `Subscriber` requested.


	*/
	SubscriberID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update subscriber params
func (o *UpdateSubscriberParams) WithTimeout(timeout time.Duration) *UpdateSubscriberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update subscriber params
func (o *UpdateSubscriberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update subscriber params
func (o *UpdateSubscriberParams) WithContext(ctx context.Context) *UpdateSubscriberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update subscriber params
func (o *UpdateSubscriberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update subscriber params
func (o *UpdateSubscriberParams) WithHTTPClient(client *http.Client) *UpdateSubscriberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update subscriber params
func (o *UpdateSubscriberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccept adds the accept to the update subscriber params
func (o *UpdateSubscriberParams) WithAccept(accept *string) *UpdateSubscriberParams {
	o.SetAccept(accept)
	return o
}

// SetAccept adds the accept to the update subscriber params
func (o *UpdateSubscriberParams) SetAccept(accept *string) {
	o.Accept = accept
}

// WithContentType adds the contentType to the update subscriber params
func (o *UpdateSubscriberParams) WithContentType(contentType *string) *UpdateSubscriberParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the update subscriber params
func (o *UpdateSubscriberParams) SetContentType(contentType *string) {
	o.ContentType = contentType
}

// WithSubscriber adds the subscriber to the update subscriber params
func (o *UpdateSubscriberParams) WithSubscriber(subscriber UpdateSubscriberBody) *UpdateSubscriberParams {
	o.SetSubscriber(subscriber)
	return o
}

// SetSubscriber adds the subscriber to the update subscriber params
func (o *UpdateSubscriberParams) SetSubscriber(subscriber UpdateSubscriberBody) {
	o.Subscriber = subscriber
}

// WithSubscriberID adds the subscriberID to the update subscriber params
func (o *UpdateSubscriberParams) WithSubscriberID(subscriberID int64) *UpdateSubscriberParams {
	o.SetSubscriberID(subscriberID)
	return o
}

// SetSubscriberID adds the subscriberId to the update subscriber params
func (o *UpdateSubscriberParams) SetSubscriberID(subscriberID int64) {
	o.SubscriberID = subscriberID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSubscriberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Accept != nil {

		// header param Accept
		if err := r.SetHeaderParam("Accept", *o.Accept); err != nil {
			return err
		}

	}

	if o.ContentType != nil {

		// header param Content-Type
		if err := r.SetHeaderParam("Content-Type", *o.ContentType); err != nil {
			return err
		}

	}

	if err := r.SetBodyParam(o.Subscriber); err != nil {
		return err
	}

	// path param subscriber_id
	if err := r.SetPathParam("subscriber_id", swag.FormatInt64(o.SubscriberID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
