// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateACartParams creates a new CreateACartParams object
// with the default values initialized.
func NewCreateACartParams() *CreateACartParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &CreateACartParams{
		Accept:      acceptDefault,
		ContentType: contentTypeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateACartParamsWithTimeout creates a new CreateACartParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateACartParamsWithTimeout(timeout time.Duration) *CreateACartParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &CreateACartParams{
		Accept:      acceptDefault,
		ContentType: contentTypeDefault,

		timeout: timeout,
	}
}

// NewCreateACartParamsWithContext creates a new CreateACartParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateACartParamsWithContext(ctx context.Context) *CreateACartParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &CreateACartParams{
		Accept:      acceptDefault,
		ContentType: contentTypeDefault,

		Context: ctx,
	}
}

// NewCreateACartParamsWithHTTPClient creates a new CreateACartParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateACartParamsWithHTTPClient(client *http.Client) *CreateACartParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &CreateACartParams{
		Accept:      acceptDefault,
		ContentType: contentTypeDefault,
		HTTPClient:  client,
	}
}

/*CreateACartParams contains all the parameters to send to the API endpoint
for the create a cart operation typically these are written to a http.Request
*/
type CreateACartParams struct {

	/*Accept*/
	Accept string
	/*ContentType*/
	ContentType string
	/*CartData
	  **Examples:**

	1. Creating a cart by adding a simple product (a product without option selections).
	2. Creating a cart with a variant. This works when a product can be specified purely by a variant, without any other required options.
	3. Creating a cart using a date option. The API supports timestamps, “option_value”: 1743570000, and dates as an array, “option_value”: {“day”:”01”, “month”:”02”, “year”:”2020”}.
	4. Creating a cart with a variant, a checkbox, and a picklist modifier added.
	5. Creating a cart using a custom item.

	*/
	CartData CreateACartBody
	/*Include
	  * `redirect_urls`: Create a direct link to a Cart. This can be used during the /POST request for Carts.
	* `line_items.physical_items.options`: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return.
	* `line_items.digital_items.options`: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return.

	*/
	Include *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create a cart params
func (o *CreateACartParams) WithTimeout(timeout time.Duration) *CreateACartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create a cart params
func (o *CreateACartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create a cart params
func (o *CreateACartParams) WithContext(ctx context.Context) *CreateACartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create a cart params
func (o *CreateACartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create a cart params
func (o *CreateACartParams) WithHTTPClient(client *http.Client) *CreateACartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create a cart params
func (o *CreateACartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccept adds the accept to the create a cart params
func (o *CreateACartParams) WithAccept(accept string) *CreateACartParams {
	o.SetAccept(accept)
	return o
}

// SetAccept adds the accept to the create a cart params
func (o *CreateACartParams) SetAccept(accept string) {
	o.Accept = accept
}

// WithContentType adds the contentType to the create a cart params
func (o *CreateACartParams) WithContentType(contentType string) *CreateACartParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the create a cart params
func (o *CreateACartParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithCartData adds the cartData to the create a cart params
func (o *CreateACartParams) WithCartData(cartData CreateACartBody) *CreateACartParams {
	o.SetCartData(cartData)
	return o
}

// SetCartData adds the cartData to the create a cart params
func (o *CreateACartParams) SetCartData(cartData CreateACartBody) {
	o.CartData = cartData
}

// WithInclude adds the include to the create a cart params
func (o *CreateACartParams) WithInclude(include *string) *CreateACartParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the create a cart params
func (o *CreateACartParams) SetInclude(include *string) {
	o.Include = include
}

// WriteToRequest writes these params to a swagger request
func (o *CreateACartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Accept
	if err := r.SetHeaderParam("Accept", o.Accept); err != nil {
		return err
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.CartData); err != nil {
		return err
	}

	if o.Include != nil {

		// query param include
		var qrInclude string
		if o.Include != nil {
			qrInclude = *o.Include
		}
		qInclude := qrInclude
		if qInclude != "" {
			if err := r.SetQueryParam("include", qInclude); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
