// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateACartReader is a Reader for the UpdateACart structure.
type UpdateACartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateACartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUpdateACartCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateACartCreated creates a UpdateACartCreated with default headers values
func NewUpdateACartCreated() *UpdateACartCreated {
	return &UpdateACartCreated{}
}

/*UpdateACartCreated handles this case with default header values.

UpdateACartCreated update a cart created
*/
type UpdateACartCreated struct {
	Payload *UpdateACartCreatedBody
}

func (o *UpdateACartCreated) Error() string {
	return fmt.Sprintf("[PUT /carts/{cartId}][%d] updateACartCreated  %+v", 201, o.Payload)
}

func (o *UpdateACartCreated) GetPayload() *UpdateACartCreatedBody {
	return o.Payload
}

func (o *UpdateACartCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UpdateACartCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*UpdateACartBody Cart Update Put Request Data
swagger:model UpdateACartBody
*/
type UpdateACartBody struct {

	// customer id
	CustomerID int64 `json:"customer_id,omitempty"`
}

// Validate validates this update a cart body
func (o *UpdateACartBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartBody) UnmarshalBinary(b []byte) error {
	var res UpdateACartBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBody Cart_Full
//
// A cart contains a collection of items, prices, discounts, etc.. It does not contain customer-related data.
swagger:model UpdateACartCreatedBody
*/
type UpdateACartCreatedBody struct {

	// Cost of cart's contents, before applying discounts.
	BaseAmount float64 `json:"base_amount,omitempty"`

	// Sum of line-items amounts, minus cart-level discounts and coupons. This amount includes taxes (where applicable).
	CartAmount float64 `json:"cart_amount,omitempty"`

	// If no channel is specified, defaults to 1.
	ChannelID int64 `json:"channel_id,omitempty"`

	// coupons
	Coupons []*UpdateACartCreatedBodyCouponsItems0 `json:"coupons"`

	// Time when the cart was created.
	CreatedTime string `json:"created_time,omitempty"`

	// currency
	Currency *UpdateACartCreatedBodyCurrency `json:"currency,omitempty"`

	// ID of the customer to which the cart belongs.
	CustomerID int64 `json:"customer_id,omitempty"`

	// Discounted amount.
	DiscountAmount float64 `json:"discount_amount,omitempty"`

	// discounts
	Discounts []*UpdateACartCreatedBodyDiscountsItems0 `json:"discounts"`

	// The cart's email. This is the same email that is used in the billing address
	Email string `json:"email,omitempty"`

	// Cart ID, provided after creating a cart with a POST.
	ID string `json:"id,omitempty"`

	// line items
	LineItems []*UpdateACartCreatedBodyLineItemsItems0 `json:"line_items"`

	// Bundled items will have their parent's item Id.
	ParentID string `json:"parent_id,omitempty"`

	// tax included
	TaxIncluded bool `json:"tax_included,omitempty"`

	// Time when the cart was last updated.
	UpdatedTime string `json:"updated_time,omitempty"`
}

// Validate validates this update a cart created body
func (o *UpdateACartCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDiscounts(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLineItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateACartCreatedBody) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(o.Coupons) { // not required
		return nil
	}

	for i := 0; i < len(o.Coupons); i++ {
		if swag.IsZero(o.Coupons[i]) { // not required
			continue
		}

		if o.Coupons[i] != nil {
			if err := o.Coupons[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("updateACartCreated" + "." + "coupons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBody) validateCurrency(formats strfmt.Registry) error {

	if swag.IsZero(o.Currency) { // not required
		return nil
	}

	if o.Currency != nil {
		if err := o.Currency.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updateACartCreated" + "." + "currency")
			}
			return err
		}
	}

	return nil
}

func (o *UpdateACartCreatedBody) validateDiscounts(formats strfmt.Registry) error {

	if swag.IsZero(o.Discounts) { // not required
		return nil
	}

	for i := 0; i < len(o.Discounts); i++ {
		if swag.IsZero(o.Discounts[i]) { // not required
			continue
		}

		if o.Discounts[i] != nil {
			if err := o.Discounts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("updateACartCreated" + "." + "discounts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBody) validateLineItems(formats strfmt.Registry) error {

	if swag.IsZero(o.LineItems) { // not required
		return nil
	}

	for i := 0; i < len(o.LineItems); i++ {
		if swag.IsZero(o.LineItems[i]) { // not required
			continue
		}

		if o.LineItems[i] != nil {
			if err := o.LineItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("updateACartCreated" + "." + "line_items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBody) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyCouponsItems0 Applied Coupon
//
// |Type `int`|Type Name|
// |-|-|
// |`0`|`per_item_discount`|
// |`1`|`percentage_discount`|
// |`2`|`per_total_discount`|
// |`3`|`shipping_discount`|
// |`4`|`free_shipping`|
// |`5`|`promotion`|
swagger:model UpdateACartCreatedBodyCouponsItems0
*/
type UpdateACartCreatedBodyCouponsItems0 struct {

	// the coupon code
	// Required: true
	Code *string `json:"code"`

	// Key name to identify the type of coupon.
	//
	// type 0: per_item_discount
	// type 1: percentage_discount
	// type 2: per_total_discount
	// type 3: shipping_discount
	// type 4: free_shipping
	// type 5: promotion
	// Read Only: true
	CouponType string `json:"coupon_type,omitempty"`

	// The discounted amount applied within a given context.
	// Read Only: true
	DiscountedAmount float64 `json:"discounted_amount,omitempty"`

	// The coupon ID. Read Only
	// Read Only: true
	ID string `json:"id,omitempty"`
}

// Validate validates this update a cart created body coupons items0
func (o *UpdateACartCreatedBodyCouponsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateACartCreatedBodyCouponsItems0) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyCouponsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyCouponsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyCouponsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyCurrency Currency
//
// This will always be the same between cart and checkout.
swagger:model UpdateACartCreatedBodyCurrency
*/
type UpdateACartCreatedBodyCurrency struct {

	// ISO-4217 currency code. (See: http://en.wikipedia.org/wiki/ISO_4217.)
	Code string `json:"code,omitempty"`
}

// Validate validates this update a cart created body currency
func (o *UpdateACartCreatedBodyCurrency) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyCurrency) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyCurrency) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyCurrency
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyDiscountsItems0 Applied Discount
//
// Example as part of a Cart response:
//
// ```
// "discounts": [
// 		{
// 				"id": 2,
// 				"discounted_amount": 2
// 		},
// 		{
// 				"id": "coupon",
// 				"discounted_amount": 0.42
// 		}
// ]
// ```
swagger:model UpdateACartCreatedBodyDiscountsItems0
*/
type UpdateACartCreatedBodyDiscountsItems0 struct {

	// The discounted amount.
	DiscountedAmount float64 `json:"discounted_amount,omitempty"`

	// ID of the applied discount.
	ID float64 `json:"id,omitempty"`
}

// Validate validates this update a cart created body discounts items0
func (o *UpdateACartCreatedBodyDiscountsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyDiscountsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyDiscountsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyDiscountsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0 Line Item
swagger:model UpdateACartCreatedBodyLineItemsItems0
*/
type UpdateACartCreatedBodyLineItemsItems0 struct {

	// custom items
	CustomItems []*UpdateACartCreatedBodyLineItemsItems0CustomItemsItems0 `json:"custom_items"`

	// digital items
	// Required: true
	DigitalItems []*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0 `json:"digital_items"`

	// gift certificates
	GiftCertificates []*UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0 `json:"gift_certificates"`

	// physical items
	// Required: true
	PhysicalItems []*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0 `json:"physical_items"`
}

// Validate validates this update a cart created body line items items0
func (o *UpdateACartCreatedBodyLineItemsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCustomItems(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDigitalItems(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateGiftCertificates(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePhysicalItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0) validateCustomItems(formats strfmt.Registry) error {

	if swag.IsZero(o.CustomItems) { // not required
		return nil
	}

	for i := 0; i < len(o.CustomItems); i++ {
		if swag.IsZero(o.CustomItems[i]) { // not required
			continue
		}

		if o.CustomItems[i] != nil {
			if err := o.CustomItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("custom_items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0) validateDigitalItems(formats strfmt.Registry) error {

	if err := validate.Required("digital_items", "body", o.DigitalItems); err != nil {
		return err
	}

	for i := 0; i < len(o.DigitalItems); i++ {
		if swag.IsZero(o.DigitalItems[i]) { // not required
			continue
		}

		if o.DigitalItems[i] != nil {
			if err := o.DigitalItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("digital_items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0) validateGiftCertificates(formats strfmt.Registry) error {

	if swag.IsZero(o.GiftCertificates) { // not required
		return nil
	}

	for i := 0; i < len(o.GiftCertificates); i++ {
		if swag.IsZero(o.GiftCertificates[i]) { // not required
			continue
		}

		if o.GiftCertificates[i] != nil {
			if err := o.GiftCertificates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("gift_certificates" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0) validatePhysicalItems(formats strfmt.Registry) error {

	if err := validate.Required("physical_items", "body", o.PhysicalItems); err != nil {
		return err
	}

	for i := 0; i < len(o.PhysicalItems); i++ {
		if swag.IsZero(o.PhysicalItems[i]) { // not required
			continue
		}

		if o.PhysicalItems[i] != nil {
			if err := o.PhysicalItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("physical_items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0CustomItemsItems0 Item Custom
//
// Add a custom item to the shoppers cart.
//
// * Custom items are not added to the catalog.
// * The price should be set to match the store settings for taxes.
swagger:model UpdateACartCreatedBodyLineItemsItems0CustomItemsItems0
*/
type UpdateACartCreatedBodyLineItemsItems0CustomItemsItems0 struct {

	// Item's list price multiplied by quantity.
	ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

	// Custom item id.
	ID string `json:"id,omitempty"`

	// Price of the item. With or without tax depending on the store's set up.
	ListPrice float64 `json:"list_price,omitempty"`

	// Item's product name.
	Name string `json:"name,omitempty"`

	// Quantity of this item in the cart.
	Quantity float64 `json:"quantity,omitempty"`

	// Custom item sku.
	Sku string `json:"sku,omitempty"`
}

// Validate validates this update a cart created body line items items0 custom items items0
func (o *UpdateACartCreatedBodyLineItemsItems0CustomItemsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0CustomItemsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0CustomItemsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0CustomItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0 Item Digital
swagger:model UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0
*/
type UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0 struct {

	// The total value of all coupons applied to this item.
	CouponAmount float64 `json:"coupon_amount,omitempty"`

	// coupons
	Coupons []*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0 `json:"coupons"`

	// The total value of all discounts applied to this item. This includes coupons and cart level discounts
	DiscountAmount float64 `json:"discount_amount,omitempty"`

	// discounts
	Discounts []*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0DiscountsItems0 `json:"discounts"`

	// Item's list price multiplied by the quantity.
	ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

	// Item's sale price multiplied by the quantity.
	ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

	// The line-item ID.
	ID string `json:"id,omitempty"`

	// Image of the product or variant.
	// Format: uri
	ImageURL strfmt.URI `json:"image_url,omitempty"`

	// Whether the item is taxable.
	IsTaxable bool `json:"is_taxable,omitempty"`

	// Item's list price, as quoted by the manufacturer/distributor.
	ListPrice float64 `json:"list_price,omitempty"`

	// The item's product name.
	Name string `json:"name,omitempty"`

	// The list of selected options for this product.
	Options []*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0OptionsItems0 `json:"options"`

	// The id of the product. Required in a /POST
	// Required: true
	ProductID *float64 `json:"product_id"`

	// Quantity of this item in the cart.
	// Required: true
	Quantity *float64 `json:"quantity"`

	// Item's price after all discounts are applied. (The final price before tax calculation.)
	SalePrice float64 `json:"sale_price,omitempty"`

	// SKU of the variant.
	Sku string `json:"sku,omitempty"`

	// The product URL.
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`

	// The id of the variant. Required in the /PUT or /POST if the product has variants.
	// Required: true
	VariantID *float64 `json:"variant_id"`

	// URLs to download all product files.
	DownloadFileUrls []string `json:"download_file_urls"`

	// The URL for the combined downloads page.
	DownloadPageURL string `json:"download_page_url,omitempty"`

	// Combined download size, in human-readable style. E.g.: `30MB`.
	DownloadSize string `json:"download_size,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		CouponAmount float64 `json:"coupon_amount,omitempty"`

		Coupons []*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0 `json:"coupons"`

		DiscountAmount float64 `json:"discount_amount,omitempty"`

		Discounts []*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0DiscountsItems0 `json:"discounts"`

		ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

		ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

		ID string `json:"id,omitempty"`

		ImageURL strfmt.URI `json:"image_url,omitempty"`

		IsTaxable bool `json:"is_taxable,omitempty"`

		ListPrice float64 `json:"list_price,omitempty"`

		Name string `json:"name,omitempty"`

		Options []*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0OptionsItems0 `json:"options"`

		ProductID *float64 `json:"product_id"`

		Quantity *float64 `json:"quantity"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`

		URL strfmt.URI `json:"url,omitempty"`

		VariantID *float64 `json:"variant_id"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	o.CouponAmount = dataAO0.CouponAmount

	o.Coupons = dataAO0.Coupons

	o.DiscountAmount = dataAO0.DiscountAmount

	o.Discounts = dataAO0.Discounts

	o.ExtendedListPrice = dataAO0.ExtendedListPrice

	o.ExtendedSalePrice = dataAO0.ExtendedSalePrice

	o.ID = dataAO0.ID

	o.ImageURL = dataAO0.ImageURL

	o.IsTaxable = dataAO0.IsTaxable

	o.ListPrice = dataAO0.ListPrice

	o.Name = dataAO0.Name

	o.Options = dataAO0.Options

	o.ProductID = dataAO0.ProductID

	o.Quantity = dataAO0.Quantity

	o.SalePrice = dataAO0.SalePrice

	o.Sku = dataAO0.Sku

	o.URL = dataAO0.URL

	o.VariantID = dataAO0.VariantID

	// AO1
	var dataAO1 struct {
		DownloadFileUrls []string `json:"download_file_urls"`

		DownloadPageURL string `json:"download_page_url,omitempty"`

		DownloadSize string `json:"download_size,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.DownloadFileUrls = dataAO1.DownloadFileUrls

	o.DownloadPageURL = dataAO1.DownloadPageURL

	o.DownloadSize = dataAO1.DownloadSize

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		CouponAmount float64 `json:"coupon_amount,omitempty"`

		Coupons []*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0 `json:"coupons"`

		DiscountAmount float64 `json:"discount_amount,omitempty"`

		Discounts []*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0DiscountsItems0 `json:"discounts"`

		ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

		ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

		ID string `json:"id,omitempty"`

		ImageURL strfmt.URI `json:"image_url,omitempty"`

		IsTaxable bool `json:"is_taxable,omitempty"`

		ListPrice float64 `json:"list_price,omitempty"`

		Name string `json:"name,omitempty"`

		Options []*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0OptionsItems0 `json:"options"`

		ProductID *float64 `json:"product_id"`

		Quantity *float64 `json:"quantity"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`

		URL strfmt.URI `json:"url,omitempty"`

		VariantID *float64 `json:"variant_id"`
	}

	dataAO0.CouponAmount = o.CouponAmount

	dataAO0.Coupons = o.Coupons

	dataAO0.DiscountAmount = o.DiscountAmount

	dataAO0.Discounts = o.Discounts

	dataAO0.ExtendedListPrice = o.ExtendedListPrice

	dataAO0.ExtendedSalePrice = o.ExtendedSalePrice

	dataAO0.ID = o.ID

	dataAO0.ImageURL = o.ImageURL

	dataAO0.IsTaxable = o.IsTaxable

	dataAO0.ListPrice = o.ListPrice

	dataAO0.Name = o.Name

	dataAO0.Options = o.Options

	dataAO0.ProductID = o.ProductID

	dataAO0.Quantity = o.Quantity

	dataAO0.SalePrice = o.SalePrice

	dataAO0.Sku = o.Sku

	dataAO0.URL = o.URL

	dataAO0.VariantID = o.VariantID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		DownloadFileUrls []string `json:"download_file_urls"`

		DownloadPageURL string `json:"download_page_url,omitempty"`

		DownloadSize string `json:"download_size,omitempty"`
	}

	dataAO1.DownloadFileUrls = o.DownloadFileUrls

	dataAO1.DownloadPageURL = o.DownloadPageURL

	dataAO1.DownloadSize = o.DownloadSize

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this update a cart created body line items items0 digital items items0
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDiscounts(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateImageURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateProductID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateVariantID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(o.Coupons) { // not required
		return nil
	}

	for i := 0; i < len(o.Coupons); i++ {
		if swag.IsZero(o.Coupons[i]) { // not required
			continue
		}

		if o.Coupons[i] != nil {
			if err := o.Coupons[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("coupons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) validateDiscounts(formats strfmt.Registry) error {

	if swag.IsZero(o.Discounts) { // not required
		return nil
	}

	for i := 0; i < len(o.Discounts); i++ {
		if swag.IsZero(o.Discounts[i]) { // not required
			continue
		}

		if o.Discounts[i] != nil {
			if err := o.Discounts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("discounts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) validateImageURL(formats strfmt.Registry) error {

	if swag.IsZero(o.ImageURL) { // not required
		return nil
	}

	if err := validate.FormatOf("image_url", "body", "uri", o.ImageURL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) validateOptions(formats strfmt.Registry) error {

	if swag.IsZero(o.Options) { // not required
		return nil
	}

	for i := 0; i < len(o.Options); i++ {
		if swag.IsZero(o.Options[i]) { // not required
			continue
		}

		if o.Options[i] != nil {
			if err := o.Options[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("options" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) validateProductID(formats strfmt.Registry) error {

	if err := validate.Required("product_id", "body", o.ProductID); err != nil {
		return err
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", o.Quantity); err != nil {
		return err
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) validateURL(formats strfmt.Registry) error {

	if swag.IsZero(o.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("url", "body", "uri", o.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) validateVariantID(formats strfmt.Registry) error {

	if err := validate.Required("variant_id", "body", o.VariantID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0 Applied Coupon
swagger:model UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0
*/
type UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0 struct {

	// coupons
	Coupons *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0Coupons `json:"coupons,omitempty"`
}

// Validate validates this update a cart created body line items items0 digital items items0 coupons items0
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(o.Coupons) { // not required
		return nil
	}

	if o.Coupons != nil {
		if err := o.Coupons.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coupons")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0Coupons Required in a
swagger:model UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0Coupons
*/
type UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0Coupons struct {

	// coupon code
	// Required: true
	CouponCode *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCode `json:"coupon_code"`
}

// Validate validates this update a cart created body line items items0 digital items items0 coupons items0 coupons
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0Coupons) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCouponCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0Coupons) validateCouponCode(formats strfmt.Registry) error {

	if err := validate.Required("coupons"+"."+"coupon_code", "body", o.CouponCode); err != nil {
		return err
	}

	if o.CouponCode != nil {
		if err := o.CouponCode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coupons" + "." + "coupon_code")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0Coupons) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0Coupons) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0Coupons
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCode The coupon code
swagger:model UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCode
*/
type UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCode struct {

	// The coupon code. Required in a /POST request.
	Code string `json:"code,omitempty"`

	// The amount of the discount based on the coupoon. For example 3 percent off will show a 3.
	DiscountAmount int64 `json:"discountAmount,omitempty"`

	// The discount type.
	//
	// - type 0: per_item_discount
	// - type 1: percentage_discount
	// - type 2: per_total_discount
	// - type 3: shipping_discount
	// - type 4: free_shipping
	// Enum: [0 1 2 3 4]
	DiscountType int64 `json:"discountType,omitempty"`

	// Returns 0 if a expiration date is not set
	ExpiresDate int64 `json:"expiresDate,omitempty"`

	// Coupon Id
	ID int64 `json:"id,omitempty"`

	// Name given to the coupon in the Control Panel
	Name string `json:"name,omitempty"`

	// Total discount amount off cart
	TotalDiscount float64 `json:"totalDiscount,omitempty"`
}

// Validate validates this update a cart created body line items items0 digital items items0 coupons items0 coupons coupon code
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDiscountType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var updateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[0,1,2,3,4]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum = append(updateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum, v)
	}
}

// prop value enum
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCode) validateDiscountTypeEnum(path, location string, value int64) error {
	if err := validate.EnumCase(path, location, value, updateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCode) validateDiscountType(formats strfmt.Registry) error {

	if swag.IsZero(o.DiscountType) { // not required
		return nil
	}

	// value enum
	if err := o.validateDiscountTypeEnum("coupons"+"."+"coupon_code"+"."+"discountType", "body", o.DiscountType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCode) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCode) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0CouponsItems0CouponsCouponCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0DiscountsItems0 Applied Discount
//
// Example as part of a Cart response:
//
// ```
// "discounts": [
// 		{
// 				"id": 2,
// 				"discounted_amount": 2
// 		},
// 		{
// 				"id": "coupon",
// 				"discounted_amount": 0.42
// 		}
// ]
// ```
swagger:model UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0DiscountsItems0
*/
type UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0DiscountsItems0 struct {

	// The discounted amount.
	DiscountedAmount float64 `json:"discounted_amount,omitempty"`

	// ID of the applied discount. Will return
	ID float64 `json:"id,omitempty"`
}

// Validate validates this update a cart created body line items items0 digital items items0 discounts items0
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0DiscountsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0DiscountsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0DiscountsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0DiscountsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0OptionsItems0 Product Option
swagger:model UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0OptionsItems0
*/
type UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0OptionsItems0 struct {

	// The product option name. For example, Color or Size
	Name string `json:"name,omitempty"`

	// The product option identifier.
	NameID float64 `json:"name_id,omitempty"`

	// The product option value. For example, Red or Medium
	Value string `json:"value,omitempty"`

	// The product option value identifier.
	ValueID float64 `json:"value_id,omitempty"`
}

// Validate validates this update a cart created body line items items0 digital items items0 options items0
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0OptionsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0OptionsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0OptionsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0DigitalItemsItems0OptionsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0 Item Gift Certificate
swagger:model UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0
*/
type UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0 struct {

	// Value must be between 1.00 and 1,000.00 in the store's default currency.
	// Required: true
	Amount *float64 `json:"amount"`

	// id
	ID string `json:"id,omitempty"`

	// is taxable
	IsTaxable bool `json:"is_taxable,omitempty"`

	// Limited to 200 characters.
	Message string `json:"message,omitempty"`

	// GiftCertificate-provided name that will appear in the control panel.
	Name string `json:"name,omitempty"`

	// recipient
	// Required: true
	Recipient *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Recipient `json:"recipient"`

	// sender
	// Required: true
	Sender *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Sender `json:"sender"`

	// Currently supports `Birthday`, `Boy`, `Celebration`, `Christmas`, `General`, and `Girl`.
	// Required: true
	Theme *string `json:"theme"`
}

// Validate validates this update a cart created body line items items0 gift certificates items0
func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateRecipient(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSender(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTheme(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", o.Amount); err != nil {
		return err
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0) validateRecipient(formats strfmt.Registry) error {

	if err := validate.Required("recipient", "body", o.Recipient); err != nil {
		return err
	}

	if o.Recipient != nil {
		if err := o.Recipient.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("recipient")
			}
			return err
		}
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0) validateSender(formats strfmt.Registry) error {

	if err := validate.Required("sender", "body", o.Sender); err != nil {
		return err
	}

	if o.Sender != nil {
		if err := o.Sender.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sender")
			}
			return err
		}
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0) validateTheme(formats strfmt.Registry) error {

	if err := validate.Required("theme", "body", o.Theme); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Recipient Contact Entity
swagger:model UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Recipient
*/
type UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Recipient struct {

	// email
	Email string `json:"email,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this update a cart created body line items items0 gift certificates items0 recipient
func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Recipient) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Recipient) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Recipient) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Recipient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Sender Contact Entity
swagger:model UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Sender
*/
type UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Sender struct {

	// email
	Email string `json:"email,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this update a cart created body line items items0 gift certificates items0 sender
func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Sender) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Sender) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Sender) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0GiftCertificatesItems0Sender
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0 Item Physical
swagger:model UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0
*/
type UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0 struct {

	// The total value of all coupons applied to this item.
	CouponAmount float64 `json:"coupon_amount,omitempty"`

	// coupons
	Coupons []*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0 `json:"coupons"`

	// The total value of all discounts applied to this item. This includes coupons and cart level discounts
	DiscountAmount float64 `json:"discount_amount,omitempty"`

	// discounts
	Discounts []*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0DiscountsItems0 `json:"discounts"`

	// Item's list price multiplied by the quantity.
	ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

	// Item's sale price multiplied by the quantity.
	ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

	// The line-item ID.
	ID string `json:"id,omitempty"`

	// Image of the product or variant.
	// Format: uri
	ImageURL strfmt.URI `json:"image_url,omitempty"`

	// Whether the item is taxable.
	IsTaxable bool `json:"is_taxable,omitempty"`

	// Item's list price, as quoted by the manufacturer/distributor.
	ListPrice float64 `json:"list_price,omitempty"`

	// The item's product name.
	Name string `json:"name,omitempty"`

	// The list of selected options for this product.
	Options []*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0OptionsItems0 `json:"options"`

	// The id of the product. Required in a /POST
	// Required: true
	ProductID *float64 `json:"product_id"`

	// Quantity of this item in the cart.
	// Required: true
	Quantity *float64 `json:"quantity"`

	// Item's price after all discounts are applied. (The final price before tax calculation.)
	SalePrice float64 `json:"sale_price,omitempty"`

	// SKU of the variant.
	Sku string `json:"sku,omitempty"`

	// The product URL.
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`

	// The id of the variant. Required in the /PUT or /POST if the product has variants.
	// Required: true
	VariantID *float64 `json:"variant_id"`

	// gift wrapping
	GiftWrapping *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0AO1GiftWrapping `json:"gift_wrapping,omitempty"`

	// is require shipping
	IsRequireShipping bool `json:"is_require_shipping,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		CouponAmount float64 `json:"coupon_amount,omitempty"`

		Coupons []*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0 `json:"coupons"`

		DiscountAmount float64 `json:"discount_amount,omitempty"`

		Discounts []*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0DiscountsItems0 `json:"discounts"`

		ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

		ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

		ID string `json:"id,omitempty"`

		ImageURL strfmt.URI `json:"image_url,omitempty"`

		IsTaxable bool `json:"is_taxable,omitempty"`

		ListPrice float64 `json:"list_price,omitempty"`

		Name string `json:"name,omitempty"`

		Options []*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0OptionsItems0 `json:"options"`

		ProductID *float64 `json:"product_id"`

		Quantity *float64 `json:"quantity"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`

		URL strfmt.URI `json:"url,omitempty"`

		VariantID *float64 `json:"variant_id"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	o.CouponAmount = dataAO0.CouponAmount

	o.Coupons = dataAO0.Coupons

	o.DiscountAmount = dataAO0.DiscountAmount

	o.Discounts = dataAO0.Discounts

	o.ExtendedListPrice = dataAO0.ExtendedListPrice

	o.ExtendedSalePrice = dataAO0.ExtendedSalePrice

	o.ID = dataAO0.ID

	o.ImageURL = dataAO0.ImageURL

	o.IsTaxable = dataAO0.IsTaxable

	o.ListPrice = dataAO0.ListPrice

	o.Name = dataAO0.Name

	o.Options = dataAO0.Options

	o.ProductID = dataAO0.ProductID

	o.Quantity = dataAO0.Quantity

	o.SalePrice = dataAO0.SalePrice

	o.Sku = dataAO0.Sku

	o.URL = dataAO0.URL

	o.VariantID = dataAO0.VariantID

	// AO1
	var dataAO1 struct {
		GiftWrapping *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0AO1GiftWrapping `json:"gift_wrapping,omitempty"`

		IsRequireShipping bool `json:"is_require_shipping,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.GiftWrapping = dataAO1.GiftWrapping

	o.IsRequireShipping = dataAO1.IsRequireShipping

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		CouponAmount float64 `json:"coupon_amount,omitempty"`

		Coupons []*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0 `json:"coupons"`

		DiscountAmount float64 `json:"discount_amount,omitempty"`

		Discounts []*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0DiscountsItems0 `json:"discounts"`

		ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

		ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

		ID string `json:"id,omitempty"`

		ImageURL strfmt.URI `json:"image_url,omitempty"`

		IsTaxable bool `json:"is_taxable,omitempty"`

		ListPrice float64 `json:"list_price,omitempty"`

		Name string `json:"name,omitempty"`

		Options []*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0OptionsItems0 `json:"options"`

		ProductID *float64 `json:"product_id"`

		Quantity *float64 `json:"quantity"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`

		URL strfmt.URI `json:"url,omitempty"`

		VariantID *float64 `json:"variant_id"`
	}

	dataAO0.CouponAmount = o.CouponAmount

	dataAO0.Coupons = o.Coupons

	dataAO0.DiscountAmount = o.DiscountAmount

	dataAO0.Discounts = o.Discounts

	dataAO0.ExtendedListPrice = o.ExtendedListPrice

	dataAO0.ExtendedSalePrice = o.ExtendedSalePrice

	dataAO0.ID = o.ID

	dataAO0.ImageURL = o.ImageURL

	dataAO0.IsTaxable = o.IsTaxable

	dataAO0.ListPrice = o.ListPrice

	dataAO0.Name = o.Name

	dataAO0.Options = o.Options

	dataAO0.ProductID = o.ProductID

	dataAO0.Quantity = o.Quantity

	dataAO0.SalePrice = o.SalePrice

	dataAO0.Sku = o.Sku

	dataAO0.URL = o.URL

	dataAO0.VariantID = o.VariantID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		GiftWrapping *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0AO1GiftWrapping `json:"gift_wrapping,omitempty"`

		IsRequireShipping bool `json:"is_require_shipping,omitempty"`
	}

	dataAO1.GiftWrapping = o.GiftWrapping

	dataAO1.IsRequireShipping = o.IsRequireShipping

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this update a cart created body line items items0 physical items items0
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDiscounts(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateImageURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateProductID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateVariantID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateGiftWrapping(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(o.Coupons) { // not required
		return nil
	}

	for i := 0; i < len(o.Coupons); i++ {
		if swag.IsZero(o.Coupons[i]) { // not required
			continue
		}

		if o.Coupons[i] != nil {
			if err := o.Coupons[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("coupons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) validateDiscounts(formats strfmt.Registry) error {

	if swag.IsZero(o.Discounts) { // not required
		return nil
	}

	for i := 0; i < len(o.Discounts); i++ {
		if swag.IsZero(o.Discounts[i]) { // not required
			continue
		}

		if o.Discounts[i] != nil {
			if err := o.Discounts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("discounts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) validateImageURL(formats strfmt.Registry) error {

	if swag.IsZero(o.ImageURL) { // not required
		return nil
	}

	if err := validate.FormatOf("image_url", "body", "uri", o.ImageURL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) validateOptions(formats strfmt.Registry) error {

	if swag.IsZero(o.Options) { // not required
		return nil
	}

	for i := 0; i < len(o.Options); i++ {
		if swag.IsZero(o.Options[i]) { // not required
			continue
		}

		if o.Options[i] != nil {
			if err := o.Options[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("options" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) validateProductID(formats strfmt.Registry) error {

	if err := validate.Required("product_id", "body", o.ProductID); err != nil {
		return err
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", o.Quantity); err != nil {
		return err
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) validateURL(formats strfmt.Registry) error {

	if swag.IsZero(o.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("url", "body", "uri", o.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) validateVariantID(formats strfmt.Registry) error {

	if err := validate.Required("variant_id", "body", o.VariantID); err != nil {
		return err
	}

	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) validateGiftWrapping(formats strfmt.Registry) error {

	if swag.IsZero(o.GiftWrapping) { // not required
		return nil
	}

	if o.GiftWrapping != nil {
		if err := o.GiftWrapping.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gift_wrapping")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0AO1GiftWrapping Gift Wrapping
swagger:model UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0AO1GiftWrapping
*/
type UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0AO1GiftWrapping struct {

	// amount
	Amount float32 `json:"amount,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this update a cart created body line items items0 physical items items0 a o1 gift wrapping
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0AO1GiftWrapping) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0AO1GiftWrapping) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0AO1GiftWrapping) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0AO1GiftWrapping
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0 Applied Coupon
swagger:model UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0
*/
type UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0 struct {

	// coupons
	Coupons *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0Coupons `json:"coupons,omitempty"`
}

// Validate validates this update a cart created body line items items0 physical items items0 coupons items0
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(o.Coupons) { // not required
		return nil
	}

	if o.Coupons != nil {
		if err := o.Coupons.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coupons")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0Coupons Required in a
swagger:model UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0Coupons
*/
type UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0Coupons struct {

	// coupon code
	// Required: true
	CouponCode *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCode `json:"coupon_code"`
}

// Validate validates this update a cart created body line items items0 physical items items0 coupons items0 coupons
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0Coupons) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCouponCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0Coupons) validateCouponCode(formats strfmt.Registry) error {

	if err := validate.Required("coupons"+"."+"coupon_code", "body", o.CouponCode); err != nil {
		return err
	}

	if o.CouponCode != nil {
		if err := o.CouponCode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coupons" + "." + "coupon_code")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0Coupons) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0Coupons) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0Coupons
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCode The coupon code
swagger:model UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCode
*/
type UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCode struct {

	// The coupon code. Required in a /POST request.
	Code string `json:"code,omitempty"`

	// The amount of the discount based on the coupoon. For example 3 percent off will show a 3.
	DiscountAmount int64 `json:"discountAmount,omitempty"`

	// The discount type.
	//
	// - type 0: per_item_discount
	// - type 1: percentage_discount
	// - type 2: per_total_discount
	// - type 3: shipping_discount
	// - type 4: free_shipping
	// Enum: [0 1 2 3 4]
	DiscountType int64 `json:"discountType,omitempty"`

	// Returns 0 if a expiration date is not set
	ExpiresDate int64 `json:"expiresDate,omitempty"`

	// Coupon Id
	ID int64 `json:"id,omitempty"`

	// Name given to the coupon in the Control Panel
	Name string `json:"name,omitempty"`

	// Total discount amount off cart
	TotalDiscount float64 `json:"totalDiscount,omitempty"`
}

// Validate validates this update a cart created body line items items0 physical items items0 coupons items0 coupons coupon code
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDiscountType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var updateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[0,1,2,3,4]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		updateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum = append(updateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum, v)
	}
}

// prop value enum
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCode) validateDiscountTypeEnum(path, location string, value int64) error {
	if err := validate.EnumCase(path, location, value, updateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCode) validateDiscountType(formats strfmt.Registry) error {

	if swag.IsZero(o.DiscountType) { // not required
		return nil
	}

	// value enum
	if err := o.validateDiscountTypeEnum("coupons"+"."+"coupon_code"+"."+"discountType", "body", o.DiscountType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCode) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCode) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0CouponsItems0CouponsCouponCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0DiscountsItems0 Applied Discount
//
// Example as part of a Cart response:
//
// ```
// "discounts": [
// 		{
// 				"id": 2,
// 				"discounted_amount": 2
// 		},
// 		{
// 				"id": "coupon",
// 				"discounted_amount": 0.42
// 		}
// ]
// ```
swagger:model UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0DiscountsItems0
*/
type UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0DiscountsItems0 struct {

	// The discounted amount.
	DiscountedAmount float64 `json:"discounted_amount,omitempty"`

	// ID of the applied discount. Will return
	ID float64 `json:"id,omitempty"`
}

// Validate validates this update a cart created body line items items0 physical items items0 discounts items0
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0DiscountsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0DiscountsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0DiscountsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0DiscountsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0OptionsItems0 Product Option
swagger:model UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0OptionsItems0
*/
type UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0OptionsItems0 struct {

	// The product option name. For example, Color or Size
	Name string `json:"name,omitempty"`

	// The product option identifier.
	NameID float64 `json:"name_id,omitempty"`

	// The product option value. For example, Red or Medium
	Value string `json:"value,omitempty"`

	// The product option value identifier.
	ValueID float64 `json:"value_id,omitempty"`
}

// Validate validates this update a cart created body line items items0 physical items items0 options items0
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0OptionsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0OptionsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0OptionsItems0) UnmarshalBinary(b []byte) error {
	var res UpdateACartCreatedBodyLineItemsItems0PhysicalItemsItems0OptionsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
