// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BaseItem Base Item
//
// swagger:model BaseItem
type BaseItem struct {

	// The total value of all coupons applied to this item.
	CouponAmount float64 `json:"coupon_amount,omitempty"`

	// coupons
	Coupons []*BaseItemCouponsItems0 `json:"coupons"`

	// The total value of all discounts applied to this item. This includes coupons and cart level discounts
	DiscountAmount float64 `json:"discount_amount,omitempty"`

	// discounts
	Discounts []*BaseItemDiscountsItems0 `json:"discounts"`

	// Item's list price multiplied by the quantity.
	ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

	// Item's sale price multiplied by the quantity.
	ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

	// The line-item ID.
	ID string `json:"id,omitempty"`

	// Image of the product or variant.
	// Format: uri
	ImageURL strfmt.URI `json:"image_url,omitempty"`

	// Whether the item is taxable.
	IsTaxable bool `json:"is_taxable,omitempty"`

	// Item's list price, as quoted by the manufacturer/distributor.
	ListPrice float64 `json:"list_price,omitempty"`

	// The item's product name.
	Name string `json:"name,omitempty"`

	// The list of selected options for this product.
	Options []*BaseItemOptionsItems0 `json:"options"`

	// The id of the product. Required in a /POST
	// Required: true
	ProductID *float64 `json:"product_id"`

	// Quantity of this item in the cart.
	// Required: true
	Quantity *float64 `json:"quantity"`

	// Item's price after all discounts are applied. (The final price before tax calculation.)
	SalePrice float64 `json:"sale_price,omitempty"`

	// SKU of the variant.
	Sku string `json:"sku,omitempty"`

	// The product URL.
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`

	// The id of the variant. Required in the /PUT or /POST if the product has variants.
	// Required: true
	VariantID *float64 `json:"variant_id"`
}

// Validate validates this base item
func (m *BaseItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDiscounts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImageURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProductID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVariantID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BaseItem) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(m.Coupons) { // not required
		return nil
	}

	for i := 0; i < len(m.Coupons); i++ {
		if swag.IsZero(m.Coupons[i]) { // not required
			continue
		}

		if m.Coupons[i] != nil {
			if err := m.Coupons[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("coupons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BaseItem) validateDiscounts(formats strfmt.Registry) error {

	if swag.IsZero(m.Discounts) { // not required
		return nil
	}

	for i := 0; i < len(m.Discounts); i++ {
		if swag.IsZero(m.Discounts[i]) { // not required
			continue
		}

		if m.Discounts[i] != nil {
			if err := m.Discounts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("discounts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BaseItem) validateImageURL(formats strfmt.Registry) error {

	if swag.IsZero(m.ImageURL) { // not required
		return nil
	}

	if err := validate.FormatOf("image_url", "body", "uri", m.ImageURL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *BaseItem) validateOptions(formats strfmt.Registry) error {

	if swag.IsZero(m.Options) { // not required
		return nil
	}

	for i := 0; i < len(m.Options); i++ {
		if swag.IsZero(m.Options[i]) { // not required
			continue
		}

		if m.Options[i] != nil {
			if err := m.Options[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("options" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BaseItem) validateProductID(formats strfmt.Registry) error {

	if err := validate.Required("product_id", "body", m.ProductID); err != nil {
		return err
	}

	return nil
}

func (m *BaseItem) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

func (m *BaseItem) validateURL(formats strfmt.Registry) error {

	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("url", "body", "uri", m.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *BaseItem) validateVariantID(formats strfmt.Registry) error {

	if err := validate.Required("variant_id", "body", m.VariantID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BaseItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseItem) UnmarshalBinary(b []byte) error {
	var res BaseItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// BaseItemCouponsItems0 Applied Coupon
//
// swagger:model BaseItemCouponsItems0
type BaseItemCouponsItems0 struct {

	// coupons
	Coupons *BaseItemCouponsItems0Coupons `json:"coupons,omitempty"`
}

// Validate validates this base item coupons items0
func (m *BaseItemCouponsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BaseItemCouponsItems0) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(m.Coupons) { // not required
		return nil
	}

	if m.Coupons != nil {
		if err := m.Coupons.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coupons")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BaseItemCouponsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseItemCouponsItems0) UnmarshalBinary(b []byte) error {
	var res BaseItemCouponsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// BaseItemCouponsItems0Coupons Required in a
//
// swagger:model BaseItemCouponsItems0Coupons
type BaseItemCouponsItems0Coupons struct {

	// coupon code
	// Required: true
	CouponCode *BaseItemCouponsItems0CouponsCouponCode `json:"coupon_code"`
}

// Validate validates this base item coupons items0 coupons
func (m *BaseItemCouponsItems0Coupons) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCouponCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BaseItemCouponsItems0Coupons) validateCouponCode(formats strfmt.Registry) error {

	if err := validate.Required("coupons"+"."+"coupon_code", "body", m.CouponCode); err != nil {
		return err
	}

	if m.CouponCode != nil {
		if err := m.CouponCode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coupons" + "." + "coupon_code")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BaseItemCouponsItems0Coupons) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseItemCouponsItems0Coupons) UnmarshalBinary(b []byte) error {
	var res BaseItemCouponsItems0Coupons
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// BaseItemCouponsItems0CouponsCouponCode The coupon code
//
// swagger:model BaseItemCouponsItems0CouponsCouponCode
type BaseItemCouponsItems0CouponsCouponCode struct {

	// The coupon code. Required in a /POST request.
	Code string `json:"code,omitempty"`

	// The amount of the discount based on the coupoon. For example 3 percent off will show a 3.
	DiscountAmount int64 `json:"discountAmount,omitempty"`

	// The discount type.
	//
	// - type 0: per_item_discount
	// - type 1: percentage_discount
	// - type 2: per_total_discount
	// - type 3: shipping_discount
	// - type 4: free_shipping
	// Enum: [0 1 2 3 4]
	DiscountType int64 `json:"discountType,omitempty"`

	// Returns 0 if a expiration date is not set
	ExpiresDate int64 `json:"expiresDate,omitempty"`

	// Coupon Id
	ID int64 `json:"id,omitempty"`

	// Name given to the coupon in the Control Panel
	Name string `json:"name,omitempty"`

	// Total discount amount off cart
	TotalDiscount float64 `json:"totalDiscount,omitempty"`
}

// Validate validates this base item coupons items0 coupons coupon code
func (m *BaseItemCouponsItems0CouponsCouponCode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDiscountType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var baseItemCouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[0,1,2,3,4]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		baseItemCouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum = append(baseItemCouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum, v)
	}
}

// prop value enum
func (m *BaseItemCouponsItems0CouponsCouponCode) validateDiscountTypeEnum(path, location string, value int64) error {
	if err := validate.EnumCase(path, location, value, baseItemCouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *BaseItemCouponsItems0CouponsCouponCode) validateDiscountType(formats strfmt.Registry) error {

	if swag.IsZero(m.DiscountType) { // not required
		return nil
	}

	// value enum
	if err := m.validateDiscountTypeEnum("coupons"+"."+"coupon_code"+"."+"discountType", "body", m.DiscountType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BaseItemCouponsItems0CouponsCouponCode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseItemCouponsItems0CouponsCouponCode) UnmarshalBinary(b []byte) error {
	var res BaseItemCouponsItems0CouponsCouponCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// BaseItemDiscountsItems0 Applied Discount
//
// Example as part of a Cart response:
//
// ```
// "discounts": [
// 		{
// 				"id": 2,
// 				"discounted_amount": 2
// 		},
// 		{
// 				"id": "coupon",
// 				"discounted_amount": 0.42
// 		}
// ]
// ```
//
// swagger:model BaseItemDiscountsItems0
type BaseItemDiscountsItems0 struct {

	// The discounted amount.
	DiscountedAmount float64 `json:"discounted_amount,omitempty"`

	// ID of the applied discount. Will return
	ID string `json:"id,omitempty"`
}

// Validate validates this base item discounts items0
func (m *BaseItemDiscountsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BaseItemDiscountsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseItemDiscountsItems0) UnmarshalBinary(b []byte) error {
	var res BaseItemDiscountsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// BaseItemOptionsItems0 Product Option
//
// swagger:model BaseItemOptionsItems0
type BaseItemOptionsItems0 struct {

	// The product option name. For example, Color or Size
	Name string `json:"name,omitempty"`

	// The product option identifier.
	NameID float64 `json:"name_id,omitempty"`

	// The product option value. For example, Red or Medium
	Value string `json:"value,omitempty"`

	// The product option value identifier.
	ValueID float64 `json:"value_id,omitempty"`
}

// Validate validates this base item options items0
func (m *BaseItemOptionsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BaseItemOptionsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseItemOptionsItems0) UnmarshalBinary(b []byte) error {
	var res BaseItemOptionsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
