// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CartPostCustomItem cart_PostCustomItem
//
// swagger:model cart_PostCustomItem
type CartPostCustomItem []*CartPostCustomItemItems0

// Validate validates this cart post custom item
func (m CartPostCustomItem) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// CartPostCustomItemItems0 cart post custom item items0
//
// swagger:model CartPostCustomItemItems0
type CartPostCustomItemItems0 struct {

	// list price
	ListPrice float64 `json:"list_price,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// quantity
	Quantity float64 `json:"quantity,omitempty"`

	// sku
	Sku string `json:"sku,omitempty"`
}

// Validate validates this cart post custom item items0
func (m *CartPostCustomItemItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CartPostCustomItemItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CartPostCustomItemItems0) UnmarshalBinary(b []byte) error {
	var res CartPostCustomItemItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
