// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LineItem Line Item
//
// swagger:model LineItem
type LineItem struct {

	// digital items
	// Required: true
	DigitalItems []*LineItemDigitalItemsItems0 `json:"digital_items"`

	// gift certificates
	GiftCertificates []*LineItemGiftCertificatesItems0 `json:"gift_certificates"`

	// physical items
	// Required: true
	PhysicalItems []*LineItemPhysicalItemsItems0 `json:"physical_items"`

	// virtual items
	VirtualItems []*LineItemVirtualItemsItems0 `json:"virtual_items"`
}

// Validate validates this line item
func (m *LineItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDigitalItems(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGiftCertificates(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePhysicalItems(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVirtualItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LineItem) validateDigitalItems(formats strfmt.Registry) error {

	if err := validate.Required("digital_items", "body", m.DigitalItems); err != nil {
		return err
	}

	for i := 0; i < len(m.DigitalItems); i++ {
		if swag.IsZero(m.DigitalItems[i]) { // not required
			continue
		}

		if m.DigitalItems[i] != nil {
			if err := m.DigitalItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("digital_items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LineItem) validateGiftCertificates(formats strfmt.Registry) error {

	if swag.IsZero(m.GiftCertificates) { // not required
		return nil
	}

	for i := 0; i < len(m.GiftCertificates); i++ {
		if swag.IsZero(m.GiftCertificates[i]) { // not required
			continue
		}

		if m.GiftCertificates[i] != nil {
			if err := m.GiftCertificates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("gift_certificates" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LineItem) validatePhysicalItems(formats strfmt.Registry) error {

	if err := validate.Required("physical_items", "body", m.PhysicalItems); err != nil {
		return err
	}

	for i := 0; i < len(m.PhysicalItems); i++ {
		if swag.IsZero(m.PhysicalItems[i]) { // not required
			continue
		}

		if m.PhysicalItems[i] != nil {
			if err := m.PhysicalItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("physical_items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LineItem) validateVirtualItems(formats strfmt.Registry) error {

	if swag.IsZero(m.VirtualItems) { // not required
		return nil
	}

	for i := 0; i < len(m.VirtualItems); i++ {
		if swag.IsZero(m.VirtualItems[i]) { // not required
			continue
		}

		if m.VirtualItems[i] != nil {
			if err := m.VirtualItems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("virtual_items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LineItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItem) UnmarshalBinary(b []byte) error {
	var res LineItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemDigitalItemsItems0 Item Digital
//
// swagger:model LineItemDigitalItemsItems0
type LineItemDigitalItemsItems0 struct {

	// The total value of all coupons applied to this item.
	CouponAmount float64 `json:"coupon_amount,omitempty"`

	// coupons
	Coupons []*LineItemDigitalItemsItems0CouponsItems0 `json:"coupons"`

	// The total value of all discounts applied to this item. This includes coupons and cart level discounts
	DiscountAmount float64 `json:"discount_amount,omitempty"`

	// discounts
	Discounts []*LineItemDigitalItemsItems0DiscountsItems0 `json:"discounts"`

	// Item's list price multiplied by the quantity.
	ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

	// Item's sale price multiplied by the quantity.
	ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

	// The line-item ID.
	ID string `json:"id,omitempty"`

	// Image of the product or variant.
	// Format: uri
	ImageURL strfmt.URI `json:"image_url,omitempty"`

	// Whether the item is taxable.
	IsTaxable bool `json:"is_taxable,omitempty"`

	// Item's list price, as quoted by the manufacturer/distributor. Optional price override.
	ListPrice float64 `json:"list_price,omitempty"`

	// The item's product name.
	Name string `json:"name,omitempty"`

	// The list of selected options for this product.
	Options []*LineItemDigitalItemsItems0OptionsItems0 `json:"options"`

	// The id of the product. Required in a /POST
	// Required: true
	ProductID *float64 `json:"product_id"`

	// Quantity of this item in the cart.
	// Required: true
	Quantity *float64 `json:"quantity"`

	// Item's price after all discounts are applied. (The final price before tax calculation.)
	SalePrice float64 `json:"sale_price,omitempty"`

	// SKU of the variant.
	Sku string `json:"sku,omitempty"`

	// The product URL.
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`

	// The id of the variant. Required in the /PUT or /POST if the product has variants.
	// Required: true
	VariantID *float64 `json:"variant_id"`

	// URLs to download all product files.
	DownloadFileUrls []string `json:"download_file_urls"`

	// The URL for the combined downloads page.
	DownloadPageURL string `json:"download_page_url,omitempty"`

	// Combined download size, in human-readable style. E.g.: `30MB`.
	DownloadSize string `json:"download_size,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *LineItemDigitalItemsItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		CouponAmount float64 `json:"coupon_amount,omitempty"`

		Coupons []*LineItemDigitalItemsItems0CouponsItems0 `json:"coupons"`

		DiscountAmount float64 `json:"discount_amount,omitempty"`

		Discounts []*LineItemDigitalItemsItems0DiscountsItems0 `json:"discounts"`

		ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

		ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

		ID string `json:"id,omitempty"`

		ImageURL strfmt.URI `json:"image_url,omitempty"`

		IsTaxable bool `json:"is_taxable,omitempty"`

		ListPrice float64 `json:"list_price,omitempty"`

		Name string `json:"name,omitempty"`

		Options []*LineItemDigitalItemsItems0OptionsItems0 `json:"options"`

		ProductID *float64 `json:"product_id"`

		Quantity *float64 `json:"quantity"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`

		URL strfmt.URI `json:"url,omitempty"`

		VariantID *float64 `json:"variant_id"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.CouponAmount = dataAO0.CouponAmount

	m.Coupons = dataAO0.Coupons

	m.DiscountAmount = dataAO0.DiscountAmount

	m.Discounts = dataAO0.Discounts

	m.ExtendedListPrice = dataAO0.ExtendedListPrice

	m.ExtendedSalePrice = dataAO0.ExtendedSalePrice

	m.ID = dataAO0.ID

	m.ImageURL = dataAO0.ImageURL

	m.IsTaxable = dataAO0.IsTaxable

	m.ListPrice = dataAO0.ListPrice

	m.Name = dataAO0.Name

	m.Options = dataAO0.Options

	m.ProductID = dataAO0.ProductID

	m.Quantity = dataAO0.Quantity

	m.SalePrice = dataAO0.SalePrice

	m.Sku = dataAO0.Sku

	m.URL = dataAO0.URL

	m.VariantID = dataAO0.VariantID

	// AO1
	var dataAO1 struct {
		DownloadFileUrls []string `json:"download_file_urls"`

		DownloadPageURL string `json:"download_page_url,omitempty"`

		DownloadSize string `json:"download_size,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.DownloadFileUrls = dataAO1.DownloadFileUrls

	m.DownloadPageURL = dataAO1.DownloadPageURL

	m.DownloadSize = dataAO1.DownloadSize

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m LineItemDigitalItemsItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		CouponAmount float64 `json:"coupon_amount,omitempty"`

		Coupons []*LineItemDigitalItemsItems0CouponsItems0 `json:"coupons"`

		DiscountAmount float64 `json:"discount_amount,omitempty"`

		Discounts []*LineItemDigitalItemsItems0DiscountsItems0 `json:"discounts"`

		ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

		ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

		ID string `json:"id,omitempty"`

		ImageURL strfmt.URI `json:"image_url,omitempty"`

		IsTaxable bool `json:"is_taxable,omitempty"`

		ListPrice float64 `json:"list_price,omitempty"`

		Name string `json:"name,omitempty"`

		Options []*LineItemDigitalItemsItems0OptionsItems0 `json:"options"`

		ProductID *float64 `json:"product_id"`

		Quantity *float64 `json:"quantity"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`

		URL strfmt.URI `json:"url,omitempty"`

		VariantID *float64 `json:"variant_id"`
	}

	dataAO0.CouponAmount = m.CouponAmount

	dataAO0.Coupons = m.Coupons

	dataAO0.DiscountAmount = m.DiscountAmount

	dataAO0.Discounts = m.Discounts

	dataAO0.ExtendedListPrice = m.ExtendedListPrice

	dataAO0.ExtendedSalePrice = m.ExtendedSalePrice

	dataAO0.ID = m.ID

	dataAO0.ImageURL = m.ImageURL

	dataAO0.IsTaxable = m.IsTaxable

	dataAO0.ListPrice = m.ListPrice

	dataAO0.Name = m.Name

	dataAO0.Options = m.Options

	dataAO0.ProductID = m.ProductID

	dataAO0.Quantity = m.Quantity

	dataAO0.SalePrice = m.SalePrice

	dataAO0.Sku = m.Sku

	dataAO0.URL = m.URL

	dataAO0.VariantID = m.VariantID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		DownloadFileUrls []string `json:"download_file_urls"`

		DownloadPageURL string `json:"download_page_url,omitempty"`

		DownloadSize string `json:"download_size,omitempty"`
	}

	dataAO1.DownloadFileUrls = m.DownloadFileUrls

	dataAO1.DownloadPageURL = m.DownloadPageURL

	dataAO1.DownloadSize = m.DownloadSize

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this line item digital items items0
func (m *LineItemDigitalItemsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDiscounts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImageURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProductID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVariantID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LineItemDigitalItemsItems0) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(m.Coupons) { // not required
		return nil
	}

	for i := 0; i < len(m.Coupons); i++ {
		if swag.IsZero(m.Coupons[i]) { // not required
			continue
		}

		if m.Coupons[i] != nil {
			if err := m.Coupons[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("coupons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LineItemDigitalItemsItems0) validateDiscounts(formats strfmt.Registry) error {

	if swag.IsZero(m.Discounts) { // not required
		return nil
	}

	for i := 0; i < len(m.Discounts); i++ {
		if swag.IsZero(m.Discounts[i]) { // not required
			continue
		}

		if m.Discounts[i] != nil {
			if err := m.Discounts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("discounts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LineItemDigitalItemsItems0) validateImageURL(formats strfmt.Registry) error {

	if swag.IsZero(m.ImageURL) { // not required
		return nil
	}

	if err := validate.FormatOf("image_url", "body", "uri", m.ImageURL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *LineItemDigitalItemsItems0) validateOptions(formats strfmt.Registry) error {

	if swag.IsZero(m.Options) { // not required
		return nil
	}

	for i := 0; i < len(m.Options); i++ {
		if swag.IsZero(m.Options[i]) { // not required
			continue
		}

		if m.Options[i] != nil {
			if err := m.Options[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("options" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LineItemDigitalItemsItems0) validateProductID(formats strfmt.Registry) error {

	if err := validate.Required("product_id", "body", m.ProductID); err != nil {
		return err
	}

	return nil
}

func (m *LineItemDigitalItemsItems0) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

func (m *LineItemDigitalItemsItems0) validateURL(formats strfmt.Registry) error {

	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("url", "body", "uri", m.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *LineItemDigitalItemsItems0) validateVariantID(formats strfmt.Registry) error {

	if err := validate.Required("variant_id", "body", m.VariantID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0) UnmarshalBinary(b []byte) error {
	var res LineItemDigitalItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemDigitalItemsItems0CouponsItems0 Applied Coupon
//
// swagger:model LineItemDigitalItemsItems0CouponsItems0
type LineItemDigitalItemsItems0CouponsItems0 struct {

	// coupons
	Coupons *LineItemDigitalItemsItems0CouponsItems0Coupons `json:"coupons,omitempty"`
}

// Validate validates this line item digital items items0 coupons items0
func (m *LineItemDigitalItemsItems0CouponsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LineItemDigitalItemsItems0CouponsItems0) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(m.Coupons) { // not required
		return nil
	}

	if m.Coupons != nil {
		if err := m.Coupons.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coupons")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0CouponsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0CouponsItems0) UnmarshalBinary(b []byte) error {
	var res LineItemDigitalItemsItems0CouponsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemDigitalItemsItems0CouponsItems0Coupons Required in a
//
// swagger:model LineItemDigitalItemsItems0CouponsItems0Coupons
type LineItemDigitalItemsItems0CouponsItems0Coupons struct {

	// coupon code
	// Required: true
	CouponCode *LineItemDigitalItemsItems0CouponsItems0CouponsCouponCode `json:"coupon_code"`
}

// Validate validates this line item digital items items0 coupons items0 coupons
func (m *LineItemDigitalItemsItems0CouponsItems0Coupons) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCouponCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LineItemDigitalItemsItems0CouponsItems0Coupons) validateCouponCode(formats strfmt.Registry) error {

	if err := validate.Required("coupons"+"."+"coupon_code", "body", m.CouponCode); err != nil {
		return err
	}

	if m.CouponCode != nil {
		if err := m.CouponCode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coupons" + "." + "coupon_code")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0CouponsItems0Coupons) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0CouponsItems0Coupons) UnmarshalBinary(b []byte) error {
	var res LineItemDigitalItemsItems0CouponsItems0Coupons
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemDigitalItemsItems0CouponsItems0CouponsCouponCode The coupon code
//
// swagger:model LineItemDigitalItemsItems0CouponsItems0CouponsCouponCode
type LineItemDigitalItemsItems0CouponsItems0CouponsCouponCode struct {

	// The coupon code. Required in a /POST request.
	Code string `json:"code,omitempty"`

	// The amount of the discount based on the coupoon. For example 3 percent off will show a 3.
	DiscountAmount int64 `json:"discountAmount,omitempty"`

	// The discount type.
	//
	// - type 0: per_item_discount
	// - type 1: percentage_discount
	// - type 2: per_total_discount
	// - type 3: shipping_discount
	// - type 4: free_shipping
	// Enum: [0 1 2 3 4]
	DiscountType int64 `json:"discountType,omitempty"`

	// Returns 0 if a expiration date is not set
	ExpiresDate int64 `json:"expiresDate,omitempty"`

	// Coupon Id
	ID int64 `json:"id,omitempty"`

	// Name given to the coupon in the Control Panel
	Name string `json:"name,omitempty"`

	// Total discount amount off cart
	TotalDiscount float64 `json:"totalDiscount,omitempty"`
}

// Validate validates this line item digital items items0 coupons items0 coupons coupon code
func (m *LineItemDigitalItemsItems0CouponsItems0CouponsCouponCode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDiscountType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var lineItemDigitalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[0,1,2,3,4]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		lineItemDigitalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum = append(lineItemDigitalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum, v)
	}
}

// prop value enum
func (m *LineItemDigitalItemsItems0CouponsItems0CouponsCouponCode) validateDiscountTypeEnum(path, location string, value int64) error {
	if err := validate.EnumCase(path, location, value, lineItemDigitalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *LineItemDigitalItemsItems0CouponsItems0CouponsCouponCode) validateDiscountType(formats strfmt.Registry) error {

	if swag.IsZero(m.DiscountType) { // not required
		return nil
	}

	// value enum
	if err := m.validateDiscountTypeEnum("coupons"+"."+"coupon_code"+"."+"discountType", "body", m.DiscountType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0CouponsItems0CouponsCouponCode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0CouponsItems0CouponsCouponCode) UnmarshalBinary(b []byte) error {
	var res LineItemDigitalItemsItems0CouponsItems0CouponsCouponCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemDigitalItemsItems0DiscountsItems0 Applied Discount
//
// Example as part of a Cart response:
//
// ```
// "discounts": [
// 		{
// 				"id": 2,
// 				"discounted_amount": 2
// 		},
// 		{
// 				"id": "coupon",
// 				"discounted_amount": 0.42
// 		}
// ]
// ```
//
// swagger:model LineItemDigitalItemsItems0DiscountsItems0
type LineItemDigitalItemsItems0DiscountsItems0 struct {

	// The discounted amount.
	DiscountedAmount float64 `json:"discounted_amount,omitempty"`

	// ID of the applied discount. Will return
	ID string `json:"id,omitempty"`
}

// Validate validates this line item digital items items0 discounts items0
func (m *LineItemDigitalItemsItems0DiscountsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0DiscountsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0DiscountsItems0) UnmarshalBinary(b []byte) error {
	var res LineItemDigitalItemsItems0DiscountsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemDigitalItemsItems0OptionsItems0 Product Option
//
// swagger:model LineItemDigitalItemsItems0OptionsItems0
type LineItemDigitalItemsItems0OptionsItems0 struct {

	// The product option name. For example, Color or Size
	Name string `json:"name,omitempty"`

	// The product option identifier.
	NameID float64 `json:"name_id,omitempty"`

	// The product option value. For example, Red or Medium
	Value string `json:"value,omitempty"`

	// The product option value identifier.
	ValueID float64 `json:"value_id,omitempty"`
}

// Validate validates this line item digital items items0 options items0
func (m *LineItemDigitalItemsItems0OptionsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0OptionsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemDigitalItemsItems0OptionsItems0) UnmarshalBinary(b []byte) error {
	var res LineItemDigitalItemsItems0OptionsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemGiftCertificatesItems0 Item Gift Certificate
//
// swagger:model LineItemGiftCertificatesItems0
type LineItemGiftCertificatesItems0 struct {

	// Value must be between 1.00 and 1,000.00 in the store's default currency.
	// Required: true
	Amount *float64 `json:"amount"`

	// id
	ID string `json:"id,omitempty"`

	// is taxable
	IsTaxable bool `json:"is_taxable,omitempty"`

	// Limited to 200 characters.
	Message string `json:"message,omitempty"`

	// GiftCertificate-provided name that will appear in the control panel.
	Name string `json:"name,omitempty"`

	// recipient
	// Required: true
	Recipient *LineItemGiftCertificatesItems0Recipient `json:"recipient"`

	// sender
	// Required: true
	Sender *LineItemGiftCertificatesItems0Sender `json:"sender"`

	// Currently supports `Birthday`, `Boy`, `Celebration`, `Christmas`, `General`, and `Girl`.
	// Required: true
	Theme *string `json:"theme"`
}

// Validate validates this line item gift certificates items0
func (m *LineItemGiftCertificatesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecipient(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSender(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTheme(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LineItemGiftCertificatesItems0) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *LineItemGiftCertificatesItems0) validateRecipient(formats strfmt.Registry) error {

	if err := validate.Required("recipient", "body", m.Recipient); err != nil {
		return err
	}

	if m.Recipient != nil {
		if err := m.Recipient.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("recipient")
			}
			return err
		}
	}

	return nil
}

func (m *LineItemGiftCertificatesItems0) validateSender(formats strfmt.Registry) error {

	if err := validate.Required("sender", "body", m.Sender); err != nil {
		return err
	}

	if m.Sender != nil {
		if err := m.Sender.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("sender")
			}
			return err
		}
	}

	return nil
}

func (m *LineItemGiftCertificatesItems0) validateTheme(formats strfmt.Registry) error {

	if err := validate.Required("theme", "body", m.Theme); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LineItemGiftCertificatesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemGiftCertificatesItems0) UnmarshalBinary(b []byte) error {
	var res LineItemGiftCertificatesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemGiftCertificatesItems0Recipient Contact Entity
//
// swagger:model LineItemGiftCertificatesItems0Recipient
type LineItemGiftCertificatesItems0Recipient struct {

	// email
	Email string `json:"email,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this line item gift certificates items0 recipient
func (m *LineItemGiftCertificatesItems0Recipient) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LineItemGiftCertificatesItems0Recipient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemGiftCertificatesItems0Recipient) UnmarshalBinary(b []byte) error {
	var res LineItemGiftCertificatesItems0Recipient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemGiftCertificatesItems0Sender Contact Entity
//
// swagger:model LineItemGiftCertificatesItems0Sender
type LineItemGiftCertificatesItems0Sender struct {

	// email
	Email string `json:"email,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this line item gift certificates items0 sender
func (m *LineItemGiftCertificatesItems0Sender) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LineItemGiftCertificatesItems0Sender) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemGiftCertificatesItems0Sender) UnmarshalBinary(b []byte) error {
	var res LineItemGiftCertificatesItems0Sender
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemPhysicalItemsItems0 Item Physical
//
// swagger:model LineItemPhysicalItemsItems0
type LineItemPhysicalItemsItems0 struct {

	// The total value of all coupons applied to this item.
	CouponAmount float64 `json:"coupon_amount,omitempty"`

	// coupons
	Coupons []*LineItemPhysicalItemsItems0CouponsItems0 `json:"coupons"`

	// The total value of all discounts applied to this item. This includes coupons and cart level discounts
	DiscountAmount float64 `json:"discount_amount,omitempty"`

	// discounts
	Discounts []*LineItemPhysicalItemsItems0DiscountsItems0 `json:"discounts"`

	// Item's list price multiplied by the quantity.
	ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

	// Item's sale price multiplied by the quantity.
	ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

	// The line-item ID.
	ID string `json:"id,omitempty"`

	// Image of the product or variant.
	// Format: uri
	ImageURL strfmt.URI `json:"image_url,omitempty"`

	// Whether the item is taxable.
	IsTaxable bool `json:"is_taxable,omitempty"`

	// Item's list price, as quoted by the manufacturer/distributor. Optional price override.
	ListPrice float64 `json:"list_price,omitempty"`

	// The item's product name.
	Name string `json:"name,omitempty"`

	// The list of selected options for this product.
	Options []*LineItemPhysicalItemsItems0OptionsItems0 `json:"options"`

	// The id of the product. Required in a /POST
	// Required: true
	ProductID *float64 `json:"product_id"`

	// Quantity of this item in the cart.
	// Required: true
	Quantity *float64 `json:"quantity"`

	// Item's price after all discounts are applied. (The final price before tax calculation.)
	SalePrice float64 `json:"sale_price,omitempty"`

	// SKU of the variant.
	Sku string `json:"sku,omitempty"`

	// The product URL.
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`

	// The id of the variant. Required in the /PUT or /POST if the product has variants.
	// Required: true
	VariantID *float64 `json:"variant_id"`

	// gift wrapping
	GiftWrapping *LineItemPhysicalItemsItems0AO1GiftWrapping `json:"gift_wrapping,omitempty"`

	// is require shipping
	IsRequireShipping bool `json:"is_require_shipping,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *LineItemPhysicalItemsItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		CouponAmount float64 `json:"coupon_amount,omitempty"`

		Coupons []*LineItemPhysicalItemsItems0CouponsItems0 `json:"coupons"`

		DiscountAmount float64 `json:"discount_amount,omitempty"`

		Discounts []*LineItemPhysicalItemsItems0DiscountsItems0 `json:"discounts"`

		ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

		ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

		ID string `json:"id,omitempty"`

		ImageURL strfmt.URI `json:"image_url,omitempty"`

		IsTaxable bool `json:"is_taxable,omitempty"`

		ListPrice float64 `json:"list_price,omitempty"`

		Name string `json:"name,omitempty"`

		Options []*LineItemPhysicalItemsItems0OptionsItems0 `json:"options"`

		ProductID *float64 `json:"product_id"`

		Quantity *float64 `json:"quantity"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`

		URL strfmt.URI `json:"url,omitempty"`

		VariantID *float64 `json:"variant_id"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.CouponAmount = dataAO0.CouponAmount

	m.Coupons = dataAO0.Coupons

	m.DiscountAmount = dataAO0.DiscountAmount

	m.Discounts = dataAO0.Discounts

	m.ExtendedListPrice = dataAO0.ExtendedListPrice

	m.ExtendedSalePrice = dataAO0.ExtendedSalePrice

	m.ID = dataAO0.ID

	m.ImageURL = dataAO0.ImageURL

	m.IsTaxable = dataAO0.IsTaxable

	m.ListPrice = dataAO0.ListPrice

	m.Name = dataAO0.Name

	m.Options = dataAO0.Options

	m.ProductID = dataAO0.ProductID

	m.Quantity = dataAO0.Quantity

	m.SalePrice = dataAO0.SalePrice

	m.Sku = dataAO0.Sku

	m.URL = dataAO0.URL

	m.VariantID = dataAO0.VariantID

	// AO1
	var dataAO1 struct {
		GiftWrapping *LineItemPhysicalItemsItems0AO1GiftWrapping `json:"gift_wrapping,omitempty"`

		IsRequireShipping bool `json:"is_require_shipping,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.GiftWrapping = dataAO1.GiftWrapping

	m.IsRequireShipping = dataAO1.IsRequireShipping

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m LineItemPhysicalItemsItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		CouponAmount float64 `json:"coupon_amount,omitempty"`

		Coupons []*LineItemPhysicalItemsItems0CouponsItems0 `json:"coupons"`

		DiscountAmount float64 `json:"discount_amount,omitempty"`

		Discounts []*LineItemPhysicalItemsItems0DiscountsItems0 `json:"discounts"`

		ExtendedListPrice float64 `json:"extended_list_price,omitempty"`

		ExtendedSalePrice float64 `json:"extended_sale_price,omitempty"`

		ID string `json:"id,omitempty"`

		ImageURL strfmt.URI `json:"image_url,omitempty"`

		IsTaxable bool `json:"is_taxable,omitempty"`

		ListPrice float64 `json:"list_price,omitempty"`

		Name string `json:"name,omitempty"`

		Options []*LineItemPhysicalItemsItems0OptionsItems0 `json:"options"`

		ProductID *float64 `json:"product_id"`

		Quantity *float64 `json:"quantity"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`

		URL strfmt.URI `json:"url,omitempty"`

		VariantID *float64 `json:"variant_id"`
	}

	dataAO0.CouponAmount = m.CouponAmount

	dataAO0.Coupons = m.Coupons

	dataAO0.DiscountAmount = m.DiscountAmount

	dataAO0.Discounts = m.Discounts

	dataAO0.ExtendedListPrice = m.ExtendedListPrice

	dataAO0.ExtendedSalePrice = m.ExtendedSalePrice

	dataAO0.ID = m.ID

	dataAO0.ImageURL = m.ImageURL

	dataAO0.IsTaxable = m.IsTaxable

	dataAO0.ListPrice = m.ListPrice

	dataAO0.Name = m.Name

	dataAO0.Options = m.Options

	dataAO0.ProductID = m.ProductID

	dataAO0.Quantity = m.Quantity

	dataAO0.SalePrice = m.SalePrice

	dataAO0.Sku = m.Sku

	dataAO0.URL = m.URL

	dataAO0.VariantID = m.VariantID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		GiftWrapping *LineItemPhysicalItemsItems0AO1GiftWrapping `json:"gift_wrapping,omitempty"`

		IsRequireShipping bool `json:"is_require_shipping,omitempty"`
	}

	dataAO1.GiftWrapping = m.GiftWrapping

	dataAO1.IsRequireShipping = m.IsRequireShipping

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this line item physical items items0
func (m *LineItemPhysicalItemsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDiscounts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImageURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProductID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVariantID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGiftWrapping(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LineItemPhysicalItemsItems0) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(m.Coupons) { // not required
		return nil
	}

	for i := 0; i < len(m.Coupons); i++ {
		if swag.IsZero(m.Coupons[i]) { // not required
			continue
		}

		if m.Coupons[i] != nil {
			if err := m.Coupons[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("coupons" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LineItemPhysicalItemsItems0) validateDiscounts(formats strfmt.Registry) error {

	if swag.IsZero(m.Discounts) { // not required
		return nil
	}

	for i := 0; i < len(m.Discounts); i++ {
		if swag.IsZero(m.Discounts[i]) { // not required
			continue
		}

		if m.Discounts[i] != nil {
			if err := m.Discounts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("discounts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LineItemPhysicalItemsItems0) validateImageURL(formats strfmt.Registry) error {

	if swag.IsZero(m.ImageURL) { // not required
		return nil
	}

	if err := validate.FormatOf("image_url", "body", "uri", m.ImageURL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *LineItemPhysicalItemsItems0) validateOptions(formats strfmt.Registry) error {

	if swag.IsZero(m.Options) { // not required
		return nil
	}

	for i := 0; i < len(m.Options); i++ {
		if swag.IsZero(m.Options[i]) { // not required
			continue
		}

		if m.Options[i] != nil {
			if err := m.Options[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("options" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *LineItemPhysicalItemsItems0) validateProductID(formats strfmt.Registry) error {

	if err := validate.Required("product_id", "body", m.ProductID); err != nil {
		return err
	}

	return nil
}

func (m *LineItemPhysicalItemsItems0) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

func (m *LineItemPhysicalItemsItems0) validateURL(formats strfmt.Registry) error {

	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("url", "body", "uri", m.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *LineItemPhysicalItemsItems0) validateVariantID(formats strfmt.Registry) error {

	if err := validate.Required("variant_id", "body", m.VariantID); err != nil {
		return err
	}

	return nil
}

func (m *LineItemPhysicalItemsItems0) validateGiftWrapping(formats strfmt.Registry) error {

	if swag.IsZero(m.GiftWrapping) { // not required
		return nil
	}

	if m.GiftWrapping != nil {
		if err := m.GiftWrapping.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gift_wrapping")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0) UnmarshalBinary(b []byte) error {
	var res LineItemPhysicalItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemPhysicalItemsItems0AO1GiftWrapping Gift Wrapping
//
// swagger:model LineItemPhysicalItemsItems0AO1GiftWrapping
type LineItemPhysicalItemsItems0AO1GiftWrapping struct {

	// amount
	Amount float32 `json:"amount,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this line item physical items items0 a o1 gift wrapping
func (m *LineItemPhysicalItemsItems0AO1GiftWrapping) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0AO1GiftWrapping) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0AO1GiftWrapping) UnmarshalBinary(b []byte) error {
	var res LineItemPhysicalItemsItems0AO1GiftWrapping
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemPhysicalItemsItems0CouponsItems0 Applied Coupon
//
// swagger:model LineItemPhysicalItemsItems0CouponsItems0
type LineItemPhysicalItemsItems0CouponsItems0 struct {

	// coupons
	Coupons *LineItemPhysicalItemsItems0CouponsItems0Coupons `json:"coupons,omitempty"`
}

// Validate validates this line item physical items items0 coupons items0
func (m *LineItemPhysicalItemsItems0CouponsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCoupons(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LineItemPhysicalItemsItems0CouponsItems0) validateCoupons(formats strfmt.Registry) error {

	if swag.IsZero(m.Coupons) { // not required
		return nil
	}

	if m.Coupons != nil {
		if err := m.Coupons.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coupons")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0CouponsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0CouponsItems0) UnmarshalBinary(b []byte) error {
	var res LineItemPhysicalItemsItems0CouponsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemPhysicalItemsItems0CouponsItems0Coupons Required in a
//
// swagger:model LineItemPhysicalItemsItems0CouponsItems0Coupons
type LineItemPhysicalItemsItems0CouponsItems0Coupons struct {

	// coupon code
	// Required: true
	CouponCode *LineItemPhysicalItemsItems0CouponsItems0CouponsCouponCode `json:"coupon_code"`
}

// Validate validates this line item physical items items0 coupons items0 coupons
func (m *LineItemPhysicalItemsItems0CouponsItems0Coupons) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCouponCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LineItemPhysicalItemsItems0CouponsItems0Coupons) validateCouponCode(formats strfmt.Registry) error {

	if err := validate.Required("coupons"+"."+"coupon_code", "body", m.CouponCode); err != nil {
		return err
	}

	if m.CouponCode != nil {
		if err := m.CouponCode.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("coupons" + "." + "coupon_code")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0CouponsItems0Coupons) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0CouponsItems0Coupons) UnmarshalBinary(b []byte) error {
	var res LineItemPhysicalItemsItems0CouponsItems0Coupons
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemPhysicalItemsItems0CouponsItems0CouponsCouponCode The coupon code
//
// swagger:model LineItemPhysicalItemsItems0CouponsItems0CouponsCouponCode
type LineItemPhysicalItemsItems0CouponsItems0CouponsCouponCode struct {

	// The coupon code. Required in a /POST request.
	Code string `json:"code,omitempty"`

	// The amount of the discount based on the coupoon. For example 3 percent off will show a 3.
	DiscountAmount int64 `json:"discountAmount,omitempty"`

	// The discount type.
	//
	// - type 0: per_item_discount
	// - type 1: percentage_discount
	// - type 2: per_total_discount
	// - type 3: shipping_discount
	// - type 4: free_shipping
	// Enum: [0 1 2 3 4]
	DiscountType int64 `json:"discountType,omitempty"`

	// Returns 0 if a expiration date is not set
	ExpiresDate int64 `json:"expiresDate,omitempty"`

	// Coupon Id
	ID int64 `json:"id,omitempty"`

	// Name given to the coupon in the Control Panel
	Name string `json:"name,omitempty"`

	// Total discount amount off cart
	TotalDiscount float64 `json:"totalDiscount,omitempty"`
}

// Validate validates this line item physical items items0 coupons items0 coupons coupon code
func (m *LineItemPhysicalItemsItems0CouponsItems0CouponsCouponCode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDiscountType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var lineItemPhysicalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[0,1,2,3,4]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		lineItemPhysicalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum = append(lineItemPhysicalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum, v)
	}
}

// prop value enum
func (m *LineItemPhysicalItemsItems0CouponsItems0CouponsCouponCode) validateDiscountTypeEnum(path, location string, value int64) error {
	if err := validate.EnumCase(path, location, value, lineItemPhysicalItemsItems0CouponsItems0CouponsCouponCodeTypeDiscountTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *LineItemPhysicalItemsItems0CouponsItems0CouponsCouponCode) validateDiscountType(formats strfmt.Registry) error {

	if swag.IsZero(m.DiscountType) { // not required
		return nil
	}

	// value enum
	if err := m.validateDiscountTypeEnum("coupons"+"."+"coupon_code"+"."+"discountType", "body", m.DiscountType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0CouponsItems0CouponsCouponCode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0CouponsItems0CouponsCouponCode) UnmarshalBinary(b []byte) error {
	var res LineItemPhysicalItemsItems0CouponsItems0CouponsCouponCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemPhysicalItemsItems0DiscountsItems0 Applied Discount
//
// Example as part of a Cart response:
//
// ```
// "discounts": [
// 		{
// 				"id": 2,
// 				"discounted_amount": 2
// 		},
// 		{
// 				"id": "coupon",
// 				"discounted_amount": 0.42
// 		}
// ]
// ```
//
// swagger:model LineItemPhysicalItemsItems0DiscountsItems0
type LineItemPhysicalItemsItems0DiscountsItems0 struct {

	// The discounted amount.
	DiscountedAmount float64 `json:"discounted_amount,omitempty"`

	// ID of the applied discount. Will return
	ID string `json:"id,omitempty"`
}

// Validate validates this line item physical items items0 discounts items0
func (m *LineItemPhysicalItemsItems0DiscountsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0DiscountsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0DiscountsItems0) UnmarshalBinary(b []byte) error {
	var res LineItemPhysicalItemsItems0DiscountsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemPhysicalItemsItems0OptionsItems0 Product Option
//
// swagger:model LineItemPhysicalItemsItems0OptionsItems0
type LineItemPhysicalItemsItems0OptionsItems0 struct {

	// The product option name. For example, Color or Size
	Name string `json:"name,omitempty"`

	// The product option identifier.
	NameID float64 `json:"name_id,omitempty"`

	// The product option value. For example, Red or Medium
	Value string `json:"value,omitempty"`

	// The product option value identifier.
	ValueID float64 `json:"value_id,omitempty"`
}

// Validate validates this line item physical items items0 options items0
func (m *LineItemPhysicalItemsItems0OptionsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0OptionsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemPhysicalItemsItems0OptionsItems0) UnmarshalBinary(b []byte) error {
	var res LineItemPhysicalItemsItems0OptionsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LineItemVirtualItemsItems0 Item Custom
//
// Add a custom item to the shoppers cart.
//
// * Custom items are not added to the catalog.
// * The price should be set to match the store settings for taxes.
//
// swagger:model LineItemVirtualItemsItems0
type LineItemVirtualItemsItems0 struct {

	// Id of the custom item
	ID string `json:"id,omitempty"`

	// Price of the item. With or without tax depending on your stores set up. Optional price override.
	ListPrice string `json:"list_price,omitempty"`

	// Item name
	Name string `json:"name,omitempty"`

	// quantity
	Quantity string `json:"quantity,omitempty"`

	// Custom item sku
	Sku string `json:"sku,omitempty"`
}

// Validate validates this line item virtual items items0
func (m *LineItemVirtualItemsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LineItemVirtualItemsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LineItemVirtualItemsItems0) UnmarshalBinary(b []byte) error {
	var res LineItemVirtualItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
