// Code generated by go-swagger; DO NOT EDIT.

package site_routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PutSiteRouteReader is a Reader for the PutSiteRoute structure.
type PutSiteRouteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutSiteRouteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPutSiteRouteCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutSiteRouteCreated creates a PutSiteRouteCreated with default headers values
func NewPutSiteRouteCreated() *PutSiteRouteCreated {
	return &PutSiteRouteCreated{}
}

/*PutSiteRouteCreated handles this case with default header values.

PutSiteRouteCreated put site route created
*/
type PutSiteRouteCreated struct {
	Payload *PutSiteRouteCreatedBody
}

func (o *PutSiteRouteCreated) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/routes/{route_id}][%d] putSiteRouteCreated  %+v", 201, o.Payload)
}

func (o *PutSiteRouteCreated) GetPayload() *PutSiteRouteCreatedBody {
	return o.Payload
}

func (o *PutSiteRouteCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PutSiteRouteCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PutSiteRouteBody siteRoute_Full
//
// Route object used in responses.
swagger:model PutSiteRouteBody
*/
type PutSiteRouteBody struct {

	// Unique ID for this route. Required when updating an existing route
	ID int64 `json:"id,omitempty"`

	// (entity_id?) For a given type, which resources should match this route? e.g For a route with the type: "product" and matching: "5" this route would be used for the product with the ID of 5.
	//
	// Depending on the type of resource, this may be an ID (matching a specific item), or a "*" wildcard matching all items of that type.
	Matching string `json:"matching,omitempty"`

	// The route template that will be used to generate the URL for the requested resource.
	//
	// Supports several tokens:
	// - `{id}` The **ID** of the requested item
	// - `{slug}` The **slug** for the requested item (if available). Note: the `slug` value may contain `/` slash
	// - `{language}` The **language** string that the client is using
	Route string `json:"route,omitempty"`

	// The type of resource being routed to; [supported types](https://developer.bigcommerce.com/api-reference/cart-checkout/sites-routes-api#route-types).
	// Enum: [product brand category page blog home cart checkout search account login returns static]
	Type string `json:"type,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PutSiteRouteBody) UnmarshalJSON(raw []byte) error {
	// PutSiteRouteParamsBodyAO0
	var dataPutSiteRouteParamsBodyAO0 struct {
		ID int64 `json:"id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataPutSiteRouteParamsBodyAO0); err != nil {
		return err
	}

	o.ID = dataPutSiteRouteParamsBodyAO0.ID

	// PutSiteRouteParamsBodyAO1
	var dataPutSiteRouteParamsBodyAO1 struct {
		Matching string `json:"matching,omitempty"`

		Route string `json:"route,omitempty"`

		Type string `json:"type,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataPutSiteRouteParamsBodyAO1); err != nil {
		return err
	}

	o.Matching = dataPutSiteRouteParamsBodyAO1.Matching

	o.Route = dataPutSiteRouteParamsBodyAO1.Route

	o.Type = dataPutSiteRouteParamsBodyAO1.Type

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PutSiteRouteBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataPutSiteRouteParamsBodyAO0 struct {
		ID int64 `json:"id,omitempty"`
	}

	dataPutSiteRouteParamsBodyAO0.ID = o.ID

	jsonDataPutSiteRouteParamsBodyAO0, errPutSiteRouteParamsBodyAO0 := swag.WriteJSON(dataPutSiteRouteParamsBodyAO0)
	if errPutSiteRouteParamsBodyAO0 != nil {
		return nil, errPutSiteRouteParamsBodyAO0
	}
	_parts = append(_parts, jsonDataPutSiteRouteParamsBodyAO0)
	var dataPutSiteRouteParamsBodyAO1 struct {
		Matching string `json:"matching,omitempty"`

		Route string `json:"route,omitempty"`

		Type string `json:"type,omitempty"`
	}

	dataPutSiteRouteParamsBodyAO1.Matching = o.Matching

	dataPutSiteRouteParamsBodyAO1.Route = o.Route

	dataPutSiteRouteParamsBodyAO1.Type = o.Type

	jsonDataPutSiteRouteParamsBodyAO1, errPutSiteRouteParamsBodyAO1 := swag.WriteJSON(dataPutSiteRouteParamsBodyAO1)
	if errPutSiteRouteParamsBodyAO1 != nil {
		return nil, errPutSiteRouteParamsBodyAO1
	}
	_parts = append(_parts, jsonDataPutSiteRouteParamsBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this put site route body
func (o *PutSiteRouteBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var putSiteRouteBodyTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["product","brand","category","page","blog","home","cart","checkout","search","account","login","returns","static"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		putSiteRouteBodyTypeTypePropEnum = append(putSiteRouteBodyTypeTypePropEnum, v)
	}
}

// property enum
func (o *PutSiteRouteBody) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, putSiteRouteBodyTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PutSiteRouteBody) validateType(formats strfmt.Registry) error {

	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("body"+"."+"type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutSiteRouteBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutSiteRouteBody) UnmarshalBinary(b []byte) error {
	var res PutSiteRouteBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PutSiteRouteCreatedBody put site route created body
swagger:model PutSiteRouteCreatedBody
*/
type PutSiteRouteCreatedBody struct {

	// siteRoute_Full
	//
	// Route object used in responses.
	Data struct {

		// Unique ID for this route. Required when updating an existing route
		ID int64 `json:"id,omitempty"`

		// (entity_id?) For a given type, which resources should match this route? e.g For a route with the type: "product" and matching: "5" this route would be used for the product with the ID of 5.
		//
		// Depending on the type of resource, this may be an ID (matching a specific item), or a "*" wildcard matching all items of that type.
		Matching string `json:"matching,omitempty"`

		// The route template that will be used to generate the URL for the requested resource.
		//
		// Supports several tokens:
		// - `{id}` The **ID** of the requested item
		// - `{slug}` The **slug** for the requested item (if available). Note: the `slug` value may contain `/` slash
		// - `{language}` The **language** string that the client is using
		Route string `json:"route,omitempty"`

		// The type of resource being routed to; [supported types](https://developer.bigcommerce.com/api-reference/cart-checkout/sites-routes-api#route-types).
		// Enum: [product brand category page blog home cart checkout search account login returns static]
		Type string `json:"type,omitempty"`
	} `json:"data,omitempty"`

	// meta
	Meta interface{} `json:"meta,omitempty"`
}

// Validate validates this put site route created body
func (o *PutSiteRouteCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutSiteRouteCreatedBody) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, putSitesSiteIdRoutesOKBodyDataItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}


func (o *PutSiteRouteCreatedBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("putSiteRouteCreated"+"."+"data"+"."+"type", "body", o.Data.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutSiteRouteCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutSiteRouteCreatedBody) UnmarshalBinary(b []byte) error {
	var res PutSiteRouteCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
