// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"bigcommerce.com/apis/clients/ordersv2/client/order_coupons"
	"bigcommerce.com/apis/clients/ordersv2/client/order_messages"
	"bigcommerce.com/apis/clients/ordersv2/client/order_products"
	"bigcommerce.com/apis/clients/ordersv2/client/order_shipments"
	"bigcommerce.com/apis/clients/ordersv2/client/order_shipping_addresses"
	"bigcommerce.com/apis/clients/ordersv2/client/order_shipping_addresses_quotes"
	"bigcommerce.com/apis/clients/ordersv2/client/order_status"
	"bigcommerce.com/apis/clients/ordersv2/client/order_taxes"
	"bigcommerce.com/apis/clients/ordersv2/client/orders"
)

// Default orders HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.bigcommerce.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/stores/{$$.env.store_hash}/v2"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new orders HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Orders {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new orders HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Orders {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new orders client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Orders {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Orders)
	cli.Transport = transport
	cli.OrderCoupons = order_coupons.New(transport, formats)
	cli.OrderMessages = order_messages.New(transport, formats)
	cli.OrderProducts = order_products.New(transport, formats)
	cli.OrderShipments = order_shipments.New(transport, formats)
	cli.OrderShippingAddresses = order_shipping_addresses.New(transport, formats)
	cli.OrderShippingAddressesQuotes = order_shipping_addresses_quotes.New(transport, formats)
	cli.OrderStatus = order_status.New(transport, formats)
	cli.OrderTaxes = order_taxes.New(transport, formats)
	cli.Orders = orders.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Orders is a client for orders
type Orders struct {
	OrderCoupons order_coupons.ClientService

	OrderMessages order_messages.ClientService

	OrderProducts order_products.ClientService

	OrderShipments order_shipments.ClientService

	OrderShippingAddresses order_shipping_addresses.ClientService

	OrderShippingAddressesQuotes order_shipping_addresses_quotes.ClientService

	OrderStatus order_status.ClientService

	OrderTaxes order_taxes.ClientService

	Orders orders.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Orders) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.OrderCoupons.SetTransport(transport)
	c.OrderMessages.SetTransport(transport)
	c.OrderProducts.SetTransport(transport)
	c.OrderShipments.SetTransport(transport)
	c.OrderShippingAddresses.SetTransport(transport)
	c.OrderShippingAddressesQuotes.SetTransport(transport)
	c.OrderStatus.SetTransport(transport)
	c.OrderTaxes.SetTransport(transport)
	c.Orders.SetTransport(transport)
}
