// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Amount Amount
//
// A non-negative 2 decimal place rounded value that represents that amount that can be charged/refunded via payment providers
//
// swagger:model Amount
type Amount float32

// Validate validates this amount
func (m Amount) Validate(formats strfmt.Registry) error {
	return nil
}
