// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RefundRequestPost RefundRequest_Post
//
// Request body for refund requests.
//
// swagger:model RefundRequest_Post
type RefundRequestPost struct {

	// ItemsRefund
	// Required: true
	Items []interface{} `json:"items"`

	// Order id against which this refund will be created
	// Required: true
	OrderID *int64 `json:"order_id"`

	// payments
	// Required: true
	Payments []*RefundRequestPostPaymentsItems0 `json:"payments"`

	// Reason for refund
	Reason string `json:"reason,omitempty"`
}

// Validate validates this refund request post
func (m *RefundRequestPost) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePayments(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RefundRequestPost) validateItems(formats strfmt.Registry) error {

	if err := validate.Required("items", "body", m.Items); err != nil {
		return err
	}

	return nil
}

func (m *RefundRequestPost) validateOrderID(formats strfmt.Registry) error {

	if err := validate.Required("order_id", "body", m.OrderID); err != nil {
		return err
	}

	return nil
}

func (m *RefundRequestPost) validatePayments(formats strfmt.Registry) error {

	if err := validate.Required("payments", "body", m.Payments); err != nil {
		return err
	}

	for i := 0; i < len(m.Payments); i++ {
		if swag.IsZero(m.Payments[i]) { // not required
			continue
		}

		if m.Payments[i] != nil {
			if err := m.Payments[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("payments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RefundRequestPost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RefundRequestPost) UnmarshalBinary(b []byte) error {
	var res RefundRequestPost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// RefundRequestPostPaymentsItems0 Payment Request
//
// swagger:model RefundRequestPostPaymentsItems0
type RefundRequestPostPaymentsItems0 struct {

	// Amount refunded via this provider
	Amount float64 `json:"amount,omitempty"`

	// Whether the payment was marked as offline or performed through an online payment service.
	Offline bool `json:"offline,omitempty"`

	// Reference to payment provider
	ProviderID string `json:"provider_id,omitempty"`
}

// Validate validates this refund request post payments items0
func (m *RefundRequestPostPaymentsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RefundRequestPostPaymentsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RefundRequestPostPaymentsItems0) UnmarshalBinary(b []byte) error {
	var res RefundRequestPostPaymentsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
