// Code generated by go-swagger; DO NOT EDIT.

package placement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetPlacementsReader is a Reader for the GetPlacements structure.
type GetPlacementsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlacementsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlacementsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewGetPlacementsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPlacementsOK creates a GetPlacementsOK with default headers values
func NewGetPlacementsOK() *GetPlacementsOK {
	return &GetPlacementsOK{}
}

/*GetPlacementsOK handles this case with default header values.

GetPlacementsOK get placements o k
*/
type GetPlacementsOK struct {
	Payload *GetPlacementsOKBody
}

func (o *GetPlacementsOK) Error() string {
	return fmt.Sprintf("[GET /content/placements][%d] getPlacementsOK  %+v", 200, o.Payload)
}

func (o *GetPlacementsOK) GetPayload() *GetPlacementsOKBody {
	return o.Payload
}

func (o *GetPlacementsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPlacementsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPlacementsUnprocessableEntity creates a GetPlacementsUnprocessableEntity with default headers values
func NewGetPlacementsUnprocessableEntity() *GetPlacementsUnprocessableEntity {
	return &GetPlacementsUnprocessableEntity{}
}

/*GetPlacementsUnprocessableEntity handles this case with default header values.

This is the result of missing required fields, or of invalid data. See the response for more details.

*/
type GetPlacementsUnprocessableEntity struct {
	Payload *GetPlacementsUnprocessableEntityBody
}

func (o *GetPlacementsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /content/placements][%d] getPlacementsUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *GetPlacementsUnprocessableEntity) GetPayload() *GetPlacementsUnprocessableEntityBody {
	return o.Payload
}

func (o *GetPlacementsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPlacementsUnprocessableEntityBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetPlacementsOKBody get placements o k body
swagger:model GetPlacementsOKBody
*/
type GetPlacementsOKBody struct {

	// data
	Data []*GetPlacementsOKBodyDataItems0 `json:"data"`

	// meta
	Meta *GetPlacementsOKBodyMeta `json:"meta,omitempty"`
}

// Validate validates this get placements o k body
func (o *GetPlacementsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlacementsOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getPlacementsOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetPlacementsOKBody) validateMeta(formats strfmt.Registry) error {

	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getPlacementsOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPlacementsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlacementsOKBody) UnmarshalBinary(b []byte) error {
	var res GetPlacementsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPlacementsOKBodyDataItems0 placement_Full
swagger:model GetPlacementsOKBodyDataItems0
*/
type GetPlacementsOKBodyDataItems0 struct {

	// The date on which this object was initially created.
	// Format: datetime
	DateCreated strfmt.DateTime `json:"date_created,omitempty"`

	// The date on which this object was last updated.
	// Format: datetime
	DateModified strfmt.DateTime `json:"date_modified,omitempty"`

	// The template file that you would like to target.
	TemplateFile string `json:"template_file,omitempty"`

	// The primary identifier.
	// Format: uuid
	UUID strfmt.UUID `json:"uuid,omitempty"`

	// The identifier of a page you would like to target. For product pages, choose product ID. For category pages, choose category ID. Home page does not support `entity_id`.
	EntityID string `json:"entity_id,omitempty"`

	// The name of the region in which to insert content widgets.
	Region string `json:"region,omitempty"`

	// The sort order to control the position of a content widget in a region.
	SortOrder int64 `json:"sort_order,omitempty"`

	// Sets the placement as either inactive or active.
	// Enum: [inactive active]
	Status *string `json:"status,omitempty"`

	// widget_Full
	Widget struct {

		// The user-friendly description.
		Description string `json:"description,omitempty"`

		// The user-friendly name.
		Name string `json:"name,omitempty"`

		// The JSON data that populates the template.
		WidgetConfiguration interface{} `json:"widget_configuration,omitempty"`

		// The date on which this object was initially created.
		// Format: datetime
		DateCreated strfmt.DateTime `json:"date_created,omitempty"`

		// The date on which this object was last updated.
		// Format: datetime
		DateModified strfmt.DateTime `json:"date_modified,omitempty"`

		// The primary identifier.
		// Format: uuid
		UUID strfmt.UUID `json:"uuid,omitempty"`

		// The identifier of the widget template version associated with this widget.
		VersionUUID string `json:"version_uuid,omitempty"`

		// widgetTemplate_Full
		WidgetTemplate struct {

			// The user-friendly name.
			Name string `json:"name,omitempty"`

			// The schema for the widget's merchant-facing UI. For more information on the available schema settings, see [Widget UI Schema](https://developer.bigcommerce.com/stencil-docs/page-builder/widget-ui-schema).
			Schema []interface{} `json:"schema"`

			// The GraphQL Storefront API query that provides widget data.
			StorefrontAPIQuery string `json:"storefront_api_query,omitempty"`

			// The widget template HTML. Supports Handlebars and Paper helpers.
			Template string `json:"template,omitempty"`

			// The identifier to the current version of this widget template.
			CurrentVersionUUID string `json:"current_version_uuid,omitempty"`

			// The date on which this object was initially created.
			// Format: datetime
			DateCreated strfmt.DateTime `json:"date_created,omitempty"`

			// The date on which this object was last updated.
			// Format: datetime
			DateModified strfmt.DateTime `json:"date_modified,omitempty"`

			// A read-only value. Do not attempt to set or modify this value in a POST or PUT operation.
			IconName *string `json:"icon_name,omitempty"`

			// The kind of widget template.
			Kind string `json:"kind,omitempty"`

			// The primary identifier.
			// Format: uuid
			UUID strfmt.UUID `json:"uuid,omitempty"`
		} `json:"widget_template,omitempty"`
	} `json:"widget,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetPlacementsOKBodyDataItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		DateCreated strfmt.DateTime `json:"date_created,omitempty"`

		DateModified strfmt.DateTime `json:"date_modified,omitempty"`

		TemplateFile string `json:"template_file,omitempty"`

		UUID strfmt.UUID `json:"uuid,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	o.DateCreated = dataAO0.DateCreated

	o.DateModified = dataAO0.DateModified

	o.TemplateFile = dataAO0.TemplateFile

	o.UUID = dataAO0.UUID

	// AO1
	var dataAO1 struct {
		EntityID string `json:"entity_id,omitempty"`

		Region string `json:"region,omitempty"`

		SortOrder int64 `json:"sort_order,omitempty"`

		Status *string `json:"status,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.EntityID = dataAO1.EntityID

	o.Region = dataAO1.Region

	o.SortOrder = dataAO1.SortOrder

	o.Status = dataAO1.Status

	// AO2
	var dataAO2 struct {
		Widget struct {

			// The user-friendly description.
			Description string `json:"description,omitempty"`

			// The user-friendly name.
			Name string `json:"name,omitempty"`

			// The JSON data that populates the template.
			WidgetConfiguration interface{} `json:"widget_configuration,omitempty"`

			// The date on which this object was initially created.
			// Format: datetime
			DateCreated strfmt.DateTime `json:"date_created,omitempty"`

			// The date on which this object was last updated.
			// Format: datetime
			DateModified strfmt.DateTime `json:"date_modified,omitempty"`

			// The primary identifier.
			// Format: uuid
			UUID strfmt.UUID `json:"uuid,omitempty"`

			// The identifier of the widget template version associated with this widget.
			VersionUUID string `json:"version_uuid,omitempty"`

			// widgetTemplate_Full
			WidgetTemplate struct {

				// The user-friendly name.
				Name string `json:"name,omitempty"`

				// The schema for the widget's merchant-facing UI. For more information on the available schema settings, see [Widget UI Schema](https://developer.bigcommerce.com/stencil-docs/page-builder/widget-ui-schema).
				Schema []interface{} `json:"schema"`

				// The GraphQL Storefront API query that provides widget data.
				StorefrontAPIQuery string `json:"storefront_api_query,omitempty"`

				// The widget template HTML. Supports Handlebars and Paper helpers.
				Template string `json:"template,omitempty"`

				// The identifier to the current version of this widget template.
				CurrentVersionUUID string `json:"current_version_uuid,omitempty"`

				// The date on which this object was initially created.
				// Format: datetime
				DateCreated strfmt.DateTime `json:"date_created,omitempty"`

				// The date on which this object was last updated.
				// Format: datetime
				DateModified strfmt.DateTime `json:"date_modified,omitempty"`

				// A read-only value. Do not attempt to set or modify this value in a POST or PUT operation.
				IconName *string `json:"icon_name,omitempty"`

				// The kind of widget template.
				Kind string `json:"kind,omitempty"`

				// The primary identifier.
				// Format: uuid
				UUID strfmt.UUID `json:"uuid,omitempty"`
			} `json:"widget_template,omitempty"`
		} `json:"widget,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO2); err != nil {
		return err
	}

	o.Widget = dataAO2.Widget

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetPlacementsOKBodyDataItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	var dataAO0 struct {
		DateCreated strfmt.DateTime `json:"date_created,omitempty"`

		DateModified strfmt.DateTime `json:"date_modified,omitempty"`

		TemplateFile string `json:"template_file,omitempty"`

		UUID strfmt.UUID `json:"uuid,omitempty"`
	}

	dataAO0.DateCreated = o.DateCreated

	dataAO0.DateModified = o.DateModified

	dataAO0.TemplateFile = o.TemplateFile

	dataAO0.UUID = o.UUID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		EntityID string `json:"entity_id,omitempty"`

		Region string `json:"region,omitempty"`

		SortOrder int64 `json:"sort_order,omitempty"`

		Status *string `json:"status,omitempty"`
	}

	dataAO1.EntityID = o.EntityID

	dataAO1.Region = o.Region

	dataAO1.SortOrder = o.SortOrder

	dataAO1.Status = o.Status

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	var dataAO2 struct {
		Widget struct {

			// The user-friendly description.
			Description string `json:"description,omitempty"`

			// The user-friendly name.
			Name string `json:"name,omitempty"`

			// The JSON data that populates the template.
			WidgetConfiguration interface{} `json:"widget_configuration,omitempty"`

			// The date on which this object was initially created.
			// Format: datetime
			DateCreated strfmt.DateTime `json:"date_created,omitempty"`

			// The date on which this object was last updated.
			// Format: datetime
			DateModified strfmt.DateTime `json:"date_modified,omitempty"`

			// The primary identifier.
			// Format: uuid
			UUID strfmt.UUID `json:"uuid,omitempty"`

			// The identifier of the widget template version associated with this widget.
			VersionUUID string `json:"version_uuid,omitempty"`

			// widgetTemplate_Full
			WidgetTemplate struct {

				// The user-friendly name.
				Name string `json:"name,omitempty"`

				// The schema for the widget's merchant-facing UI. For more information on the available schema settings, see [Widget UI Schema](https://developer.bigcommerce.com/stencil-docs/page-builder/widget-ui-schema).
				Schema []interface{} `json:"schema"`

				// The GraphQL Storefront API query that provides widget data.
				StorefrontAPIQuery string `json:"storefront_api_query,omitempty"`

				// The widget template HTML. Supports Handlebars and Paper helpers.
				Template string `json:"template,omitempty"`

				// The identifier to the current version of this widget template.
				CurrentVersionUUID string `json:"current_version_uuid,omitempty"`

				// The date on which this object was initially created.
				// Format: datetime
				DateCreated strfmt.DateTime `json:"date_created,omitempty"`

				// The date on which this object was last updated.
				// Format: datetime
				DateModified strfmt.DateTime `json:"date_modified,omitempty"`

				// A read-only value. Do not attempt to set or modify this value in a POST or PUT operation.
				IconName *string `json:"icon_name,omitempty"`

				// The kind of widget template.
				Kind string `json:"kind,omitempty"`

				// The primary identifier.
				// Format: uuid
				UUID strfmt.UUID `json:"uuid,omitempty"`
			} `json:"widget_template,omitempty"`
		} `json:"widget,omitempty"`
	}

	dataAO2.Widget = o.Widget

	jsonDataAO2, errAO2 := swag.WriteJSON(dataAO2)
	if errAO2 != nil {
		return nil, errAO2
	}
	_parts = append(_parts, jsonDataAO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get placements o k body data items0
func (o *GetPlacementsOKBodyDataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDateModified(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateWidget(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlacementsOKBodyDataItems0) validateDateCreated(formats strfmt.Registry) error {

	if swag.IsZero(o.DateCreated) { // not required
		return nil
	}

	if err := validate.FormatOf("date_created", "body", "datetime", o.DateCreated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetPlacementsOKBodyDataItems0) validateDateModified(formats strfmt.Registry) error {

	if swag.IsZero(o.DateModified) { // not required
		return nil
	}

	if err := validate.FormatOf("date_modified", "body", "datetime", o.DateModified.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetPlacementsOKBodyDataItems0) validateUUID(formats strfmt.Registry) error {

	if swag.IsZero(o.UUID) { // not required
		return nil
	}

	if err := validate.FormatOf("uuid", "body", "uuid", o.UUID.String(), formats); err != nil {
		return err
	}

	return nil
}

var getPlacementsOKBodyDataItems0TypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["inactive","active"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getPlacementsOKBodyDataItems0TypeStatusPropEnum = append(getPlacementsOKBodyDataItems0TypeStatusPropEnum, v)
	}
}

// property enum
func (o *GetPlacementsOKBodyDataItems0) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getPlacementsOKBodyDataItems0TypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetPlacementsOKBodyDataItems0) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(o.Status) { // not required
		return nil
	}

	// value enum
	if err := o.validateStatusEnum("status", "body", *o.Status); err != nil {
		return err
	}

	return nil
}

func (o *GetPlacementsOKBodyDataItems0) validateWidget(formats strfmt.Registry) error {

	if swag.IsZero(o.Widget) { // not required
		return nil
	}

	if err := validate.FormatOf("widget"+"."+"date_created", "body", "datetime", o.Widget.DateCreated.String(), formats); err != nil {
		return err
	}

	if err := validate.FormatOf("widget"+"."+"date_modified", "body", "datetime", o.Widget.DateModified.String(), formats); err != nil {
		return err
	}

	if err := validate.FormatOf("widget"+"."+"uuid", "body", "uuid", o.Widget.UUID.String(), formats); err != nil {
		return err
	}

	if err := validate.FormatOf("widget"+"."+"widget_template"+"."+"date_created", "body", "datetime", o.Widget.WidgetTemplate.DateCreated.String(), formats); err != nil {
		return err
	}

	if err := validate.FormatOf("widget"+"."+"widget_template"+"."+"date_modified", "body", "datetime", o.Widget.WidgetTemplate.DateModified.String(), formats); err != nil {
		return err
	}

	if err := validate.FormatOf("widget"+"."+"widget_template"+"."+"uuid", "body", "uuid", o.Widget.WidgetTemplate.UUID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPlacementsOKBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlacementsOKBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res GetPlacementsOKBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPlacementsOKBodyMeta metaCollection
//
// Data about the response, including pagination and collection totals.
swagger:model GetPlacementsOKBodyMeta
*/
type GetPlacementsOKBodyMeta struct {

	// pagination
	Pagination *GetPlacementsOKBodyMetaPagination `json:"pagination,omitempty"`
}

// Validate validates this get placements o k body meta
func (o *GetPlacementsOKBodyMeta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePagination(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlacementsOKBodyMeta) validatePagination(formats strfmt.Registry) error {

	if swag.IsZero(o.Pagination) { // not required
		return nil
	}

	if o.Pagination != nil {
		if err := o.Pagination.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getPlacementsOK" + "." + "meta" + "." + "pagination")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPlacementsOKBodyMeta) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlacementsOKBodyMeta) UnmarshalBinary(b []byte) error {
	var res GetPlacementsOKBodyMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPlacementsOKBodyMetaPagination pagination
//
// Data about the response, including pagination and collection totals.
//
swagger:model GetPlacementsOKBodyMetaPagination
*/
type GetPlacementsOKBodyMetaPagination struct {

	// Total number of items in the collection response.
	//
	Count int64 `json:"count,omitempty"`

	// The page you are currently on within the collection.
	//
	CurrentPage int64 `json:"current_page,omitempty"`

	// links
	Links *GetPlacementsOKBodyMetaPaginationLinks `json:"links,omitempty"`

	// The amount of items returned in the collection per page, controlled by the limit parameter.
	//
	PerPage int64 `json:"per_page,omitempty"`

	// Total number of items in the result set.
	//
	Total int64 `json:"total,omitempty"`

	// The total number of pages in the collection.
	//
	TotalPages int64 `json:"total_pages,omitempty"`
}

// Validate validates this get placements o k body meta pagination
func (o *GetPlacementsOKBodyMetaPagination) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlacementsOKBodyMetaPagination) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getPlacementsOK" + "." + "meta" + "." + "pagination" + "." + "links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPlacementsOKBodyMetaPagination) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlacementsOKBodyMetaPagination) UnmarshalBinary(b []byte) error {
	var res GetPlacementsOKBodyMetaPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPlacementsOKBodyMetaPaginationLinks Pagination links for the previous and next parts of the whole collection.
//
swagger:model GetPlacementsOKBodyMetaPaginationLinks
*/
type GetPlacementsOKBodyMetaPaginationLinks struct {

	// Link to the current page returned in the response.
	//
	Current string `json:"current,omitempty"`

	// Link to the next page returned in the response.
	//
	Next string `json:"next,omitempty"`

	// Link to the previous page returned in the response.
	//
	Previous string `json:"previous,omitempty"`
}

// Validate validates this get placements o k body meta pagination links
func (o *GetPlacementsOKBodyMetaPaginationLinks) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPlacementsOKBodyMetaPaginationLinks) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlacementsOKBodyMetaPaginationLinks) UnmarshalBinary(b []byte) error {
	var res GetPlacementsOKBodyMetaPaginationLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPlacementsUnprocessableEntityBody error_Base
//
// Error payload for the BigCommerce API.
//
swagger:model GetPlacementsUnprocessableEntityBody
*/
type GetPlacementsUnprocessableEntityBody struct {

	// errors
	Errors interface{} `json:"errors,omitempty"`

	// instance
	Instance string `json:"instance,omitempty"`

	// The HTTP status code.
	//
	Status int64 `json:"status,omitempty"`

	// The error title describing the particular error.
	//
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this get placements unprocessable entity body
func (o *GetPlacementsUnprocessableEntityBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPlacementsUnprocessableEntityBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlacementsUnprocessableEntityBody) UnmarshalBinary(b []byte) error {
	var res GetPlacementsUnprocessableEntityBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
