// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"bigcommerce.com/apis/clients/channels/client/channel_currency_assignments"
	"bigcommerce.com/apis/clients/channels/client/channel_listings"
	"bigcommerce.com/apis/clients/channels/client/channel_site"
	"bigcommerce.com/apis/clients/channels/client/channels"
)

// Default channels HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.bigcommerce.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/stores/{$$.env.store_hash}/v3"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new channels HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Channels {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new channels HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Channels {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new channels client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Channels {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Channels)
	cli.Transport = transport
	cli.ChannelCurrencyAssignments = channel_currency_assignments.New(transport, formats)
	cli.ChannelListings = channel_listings.New(transport, formats)
	cli.ChannelSite = channel_site.New(transport, formats)
	cli.Channels = channels.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Channels is a client for channels
type Channels struct {
	ChannelCurrencyAssignments channel_currency_assignments.ClientService

	ChannelListings channel_listings.ClientService

	ChannelSite channel_site.ClientService

	Channels channels.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Channels) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.ChannelCurrencyAssignments.SetTransport(transport)
	c.ChannelListings.SetTransport(transport)
	c.ChannelSite.SetTransport(transport)
	c.Channels.SetTransport(transport)
}
