// Code generated by go-swagger; DO NOT EDIT.

package scripts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetScriptsReader is a Reader for the GetScripts structure.
type GetScriptsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScriptsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScriptsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewGetScriptsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetScriptsOK creates a GetScriptsOK with default headers values
func NewGetScriptsOK() *GetScriptsOK {
	return &GetScriptsOK{}
}

/*GetScriptsOK handles this case with default header values.

GetScriptsOK get scripts o k
*/
type GetScriptsOK struct {
	Payload *GetScriptsOKBody
}

func (o *GetScriptsOK) Error() string {
	return fmt.Sprintf("[GET /content/scripts][%d] getScriptsOK  %+v", 200, o.Payload)
}

func (o *GetScriptsOK) GetPayload() *GetScriptsOKBody {
	return o.Payload
}

func (o *GetScriptsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetScriptsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetScriptsUnprocessableEntity creates a GetScriptsUnprocessableEntity with default headers values
func NewGetScriptsUnprocessableEntity() *GetScriptsUnprocessableEntity {
	return &GetScriptsUnprocessableEntity{}
}

/*GetScriptsUnprocessableEntity handles this case with default header values.

This is the result of missing required fields, or of invalid data. See the response for more details.

*/
type GetScriptsUnprocessableEntity struct {
	Payload *GetScriptsUnprocessableEntityBody
}

func (o *GetScriptsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /content/scripts][%d] getScriptsUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *GetScriptsUnprocessableEntity) GetPayload() *GetScriptsUnprocessableEntityBody {
	return o.Payload
}

func (o *GetScriptsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetScriptsUnprocessableEntityBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetScriptsOKBody Scripts Response
swagger:model GetScriptsOKBody
*/
type GetScriptsOKBody struct {

	// data
	Data []*GetScriptsOKBodyDataItems0 `json:"data"`

	// meta
	Meta *GetScriptsOKBodyMeta `json:"meta,omitempty"`
}

// Validate validates this get scripts o k body
func (o *GetScriptsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetScriptsOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getScriptsOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetScriptsOKBody) validateMeta(formats strfmt.Registry) error {

	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getScriptsOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetScriptsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetScriptsOKBody) UnmarshalBinary(b []byte) error {
	var res GetScriptsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetScriptsOKBodyDataItems0 script_Full
swagger:model GetScriptsOKBodyDataItems0
*/
type GetScriptsOKBodyDataItems0 struct {

	// The date on which this object was initially created.
	// Format: date-time
	DateCreated strfmt.DateTime `json:"date_created,omitempty"`

	// The date on which this object was last updated.
	// Format: date-time
	DateModified strfmt.DateTime `json:"date_modified,omitempty"`

	// The primary identifier.
	// Format: uuid
	UUID strfmt.UUID `json:"uuid,omitempty"`

	// The client id of the API user that created this script, or blank if created by other means.
	APIClientID string `json:"api_client_id,omitempty"`

	// It will enable automatic cleanup of the script when the single click app is uninstalled or OAuth token is revoked.
	AutoUninstall bool `json:"auto_uninstall,omitempty"`

	// What category of script this is for the purposes of GDPR/CCPA compliance.
	// Enum: [essential functional analytics targeting]
	ConsentCategory string `json:"consent_category,omitempty"`

	// The user-friendly description.
	Description string `json:"description,omitempty"`

	// Indicates whether a script is enabled.
	Enabled bool `json:"enabled,omitempty"`

	// An html string containing exactly one `script` tag. Only present if `kind` is `script_tag`
	HTML string `json:"html,omitempty"`

	// What type of script this is.
	//
	// `src` - a `script` tag will be generated with its `src` attribute set to the value of `src`; For scripts that use the src url. By providing a path to the script, we can optimize and serve the script tag automatically for you.
	//
	// `script_tag` - The value of `html` will be injected directly onto the page.
	// For scripts which include a raw HTML script_tag to be inserted into the page. The load_method must be default.
	// Enum: [src script_tag]
	Kind string `json:"kind,omitempty"`

	// The load method to use for the script. Values are `default`, `async`, or `defer`. It determines how the script should be loaded into the page.
	// Enum: [default async defer]
	LoadMethod string `json:"load_method,omitempty"`

	// Where on the page to place the script. Values are `head` or `footer`.
	// Enum: [head footer]
	Location string `json:"location,omitempty"`

	// The `src` attribute of the script to load. Only present if `kind` is `src`.
	Src string `json:"src,omitempty"`

	// Which set of pages the script should load on.
	//
	// Please note that you need to have `Checkout content` scope to use `all_pages` and `checkout`.
	//
	// - The current visibility options are `storefront`, `checkout`, `all_pages` and `order_confirmation`.
	//
	//      `storefront`: All pages that are not `checkout` or `order_confirmation`.
	//
	// For a list of all locations visit [Scripts Visibility](https://developer.bigcommerce.com/api-docs/storefront/scripts-overview#scripts_scripts-visibility).
	// Enum: [storefront all_pages checkout order_confirmation]
	Visibility string `json:"visibility,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetScriptsOKBodyDataItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		DateCreated strfmt.DateTime `json:"date_created,omitempty"`

		DateModified strfmt.DateTime `json:"date_modified,omitempty"`

		UUID strfmt.UUID `json:"uuid,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	o.DateCreated = dataAO0.DateCreated

	o.DateModified = dataAO0.DateModified

	o.UUID = dataAO0.UUID

	// AO1
	var dataAO1 struct {
		APIClientID string `json:"api_client_id,omitempty"`

		AutoUninstall bool `json:"auto_uninstall,omitempty"`

		ConsentCategory string `json:"consent_category,omitempty"`

		Description string `json:"description,omitempty"`

		Enabled bool `json:"enabled,omitempty"`

		HTML string `json:"html,omitempty"`

		Kind string `json:"kind,omitempty"`

		LoadMethod string `json:"load_method,omitempty"`

		Location string `json:"location,omitempty"`

		Src string `json:"src,omitempty"`

		Visibility string `json:"visibility,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.APIClientID = dataAO1.APIClientID

	o.AutoUninstall = dataAO1.AutoUninstall

	o.ConsentCategory = dataAO1.ConsentCategory

	o.Description = dataAO1.Description

	o.Enabled = dataAO1.Enabled

	o.HTML = dataAO1.HTML

	o.Kind = dataAO1.Kind

	o.LoadMethod = dataAO1.LoadMethod

	o.Location = dataAO1.Location

	o.Src = dataAO1.Src

	o.Visibility = dataAO1.Visibility

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetScriptsOKBodyDataItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		DateCreated strfmt.DateTime `json:"date_created,omitempty"`

		DateModified strfmt.DateTime `json:"date_modified,omitempty"`

		UUID strfmt.UUID `json:"uuid,omitempty"`
	}

	dataAO0.DateCreated = o.DateCreated

	dataAO0.DateModified = o.DateModified

	dataAO0.UUID = o.UUID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		APIClientID string `json:"api_client_id,omitempty"`

		AutoUninstall bool `json:"auto_uninstall,omitempty"`

		ConsentCategory string `json:"consent_category,omitempty"`

		Description string `json:"description,omitempty"`

		Enabled bool `json:"enabled,omitempty"`

		HTML string `json:"html,omitempty"`

		Kind string `json:"kind,omitempty"`

		LoadMethod string `json:"load_method,omitempty"`

		Location string `json:"location,omitempty"`

		Src string `json:"src,omitempty"`

		Visibility string `json:"visibility,omitempty"`
	}

	dataAO1.APIClientID = o.APIClientID

	dataAO1.AutoUninstall = o.AutoUninstall

	dataAO1.ConsentCategory = o.ConsentCategory

	dataAO1.Description = o.Description

	dataAO1.Enabled = o.Enabled

	dataAO1.HTML = o.HTML

	dataAO1.Kind = o.Kind

	dataAO1.LoadMethod = o.LoadMethod

	dataAO1.Location = o.Location

	dataAO1.Src = o.Src

	dataAO1.Visibility = o.Visibility

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get scripts o k body data items0
func (o *GetScriptsOKBodyDataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDateModified(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateConsentCategory(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateKind(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLoadMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLocation(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateVisibility(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetScriptsOKBodyDataItems0) validateDateCreated(formats strfmt.Registry) error {

	if swag.IsZero(o.DateCreated) { // not required
		return nil
	}

	if err := validate.FormatOf("date_created", "body", "date-time", o.DateCreated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetScriptsOKBodyDataItems0) validateDateModified(formats strfmt.Registry) error {

	if swag.IsZero(o.DateModified) { // not required
		return nil
	}

	if err := validate.FormatOf("date_modified", "body", "date-time", o.DateModified.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetScriptsOKBodyDataItems0) validateUUID(formats strfmt.Registry) error {

	if swag.IsZero(o.UUID) { // not required
		return nil
	}

	if err := validate.FormatOf("uuid", "body", "uuid", o.UUID.String(), formats); err != nil {
		return err
	}

	return nil
}

var getScriptsOKBodyDataItems0TypeConsentCategoryPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["essential","functional","analytics","targeting"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getScriptsOKBodyDataItems0TypeConsentCategoryPropEnum = append(getScriptsOKBodyDataItems0TypeConsentCategoryPropEnum, v)
	}
}

// property enum
func (o *GetScriptsOKBodyDataItems0) validateConsentCategoryEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getScriptsOKBodyDataItems0TypeConsentCategoryPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetScriptsOKBodyDataItems0) validateConsentCategory(formats strfmt.Registry) error {

	if swag.IsZero(o.ConsentCategory) { // not required
		return nil
	}

	// value enum
	if err := o.validateConsentCategoryEnum("consent_category", "body", o.ConsentCategory); err != nil {
		return err
	}

	return nil
}

var getScriptsOKBodyDataItems0TypeKindPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["src","script_tag"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getScriptsOKBodyDataItems0TypeKindPropEnum = append(getScriptsOKBodyDataItems0TypeKindPropEnum, v)
	}
}

// property enum
func (o *GetScriptsOKBodyDataItems0) validateKindEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getScriptsOKBodyDataItems0TypeKindPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetScriptsOKBodyDataItems0) validateKind(formats strfmt.Registry) error {

	if swag.IsZero(o.Kind) { // not required
		return nil
	}

	// value enum
	if err := o.validateKindEnum("kind", "body", o.Kind); err != nil {
		return err
	}

	return nil
}

var getScriptsOKBodyDataItems0TypeLoadMethodPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["default","async","defer"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getScriptsOKBodyDataItems0TypeLoadMethodPropEnum = append(getScriptsOKBodyDataItems0TypeLoadMethodPropEnum, v)
	}
}

// property enum
func (o *GetScriptsOKBodyDataItems0) validateLoadMethodEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getScriptsOKBodyDataItems0TypeLoadMethodPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetScriptsOKBodyDataItems0) validateLoadMethod(formats strfmt.Registry) error {

	if swag.IsZero(o.LoadMethod) { // not required
		return nil
	}

	// value enum
	if err := o.validateLoadMethodEnum("load_method", "body", o.LoadMethod); err != nil {
		return err
	}

	return nil
}

var getScriptsOKBodyDataItems0TypeLocationPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["head","footer"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getScriptsOKBodyDataItems0TypeLocationPropEnum = append(getScriptsOKBodyDataItems0TypeLocationPropEnum, v)
	}
}

// property enum
func (o *GetScriptsOKBodyDataItems0) validateLocationEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getScriptsOKBodyDataItems0TypeLocationPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetScriptsOKBodyDataItems0) validateLocation(formats strfmt.Registry) error {

	if swag.IsZero(o.Location) { // not required
		return nil
	}

	// value enum
	if err := o.validateLocationEnum("location", "body", o.Location); err != nil {
		return err
	}

	return nil
}

var getScriptsOKBodyDataItems0TypeVisibilityPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["storefront","all_pages","checkout","order_confirmation"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getScriptsOKBodyDataItems0TypeVisibilityPropEnum = append(getScriptsOKBodyDataItems0TypeVisibilityPropEnum, v)
	}
}

// property enum
func (o *GetScriptsOKBodyDataItems0) validateVisibilityEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getScriptsOKBodyDataItems0TypeVisibilityPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetScriptsOKBodyDataItems0) validateVisibility(formats strfmt.Registry) error {

	if swag.IsZero(o.Visibility) { // not required
		return nil
	}

	// value enum
	if err := o.validateVisibilityEnum("visibility", "body", o.Visibility); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetScriptsOKBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetScriptsOKBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res GetScriptsOKBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetScriptsOKBodyMeta Collection Meta
//
// Data about the response, including pagination and collection totals.
swagger:model GetScriptsOKBodyMeta
*/
type GetScriptsOKBodyMeta struct {

	// pagination
	Pagination *GetScriptsOKBodyMetaPagination `json:"pagination,omitempty"`
}

// Validate validates this get scripts o k body meta
func (o *GetScriptsOKBodyMeta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePagination(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetScriptsOKBodyMeta) validatePagination(formats strfmt.Registry) error {

	if swag.IsZero(o.Pagination) { // not required
		return nil
	}

	if o.Pagination != nil {
		if err := o.Pagination.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getScriptsOK" + "." + "meta" + "." + "pagination")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetScriptsOKBodyMeta) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetScriptsOKBodyMeta) UnmarshalBinary(b []byte) error {
	var res GetScriptsOKBodyMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetScriptsOKBodyMetaPagination Pagination
//
// Data about the response, including pagination and collection totals.
swagger:model GetScriptsOKBodyMetaPagination
*/
type GetScriptsOKBodyMetaPagination struct {

	// Total number of items in the collection response.
	//
	Count int64 `json:"count,omitempty"`

	// The page you are currently on within the collection.
	//
	CurrentPage int64 `json:"current_page,omitempty"`

	// links
	Links *GetScriptsOKBodyMetaPaginationLinks `json:"links,omitempty"`

	// The amount of items returned in the collection per page, controlled by the limit parameter.
	//
	PerPage int64 `json:"per_page,omitempty"`

	// Total number of items in the result set.
	//
	Total int64 `json:"total,omitempty"`

	// The total number of pages in the collection.
	//
	TotalPages int64 `json:"total_pages,omitempty"`
}

// Validate validates this get scripts o k body meta pagination
func (o *GetScriptsOKBodyMetaPagination) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetScriptsOKBodyMetaPagination) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getScriptsOK" + "." + "meta" + "." + "pagination" + "." + "links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetScriptsOKBodyMetaPagination) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetScriptsOKBodyMetaPagination) UnmarshalBinary(b []byte) error {
	var res GetScriptsOKBodyMetaPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetScriptsOKBodyMetaPaginationLinks Pagination links for the previous and next parts of the whole collection.
//
swagger:model GetScriptsOKBodyMetaPaginationLinks
*/
type GetScriptsOKBodyMetaPaginationLinks struct {

	// Link to the current page returned in the response.
	//
	Current string `json:"current,omitempty"`

	// Link to the next page returned in the response.
	//
	Next string `json:"next,omitempty"`

	// Link to the previous page returned in the response.
	//
	Previous string `json:"previous,omitempty"`
}

// Validate validates this get scripts o k body meta pagination links
func (o *GetScriptsOKBodyMetaPaginationLinks) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetScriptsOKBodyMetaPaginationLinks) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetScriptsOKBodyMetaPaginationLinks) UnmarshalBinary(b []byte) error {
	var res GetScriptsOKBodyMetaPaginationLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetScriptsUnprocessableEntityBody Error Response
swagger:model GetScriptsUnprocessableEntityBody
*/
type GetScriptsUnprocessableEntityBody struct {

	// instance
	Instance string `json:"instance,omitempty"`

	// The HTTP status code.
	//
	Status int64 `json:"status,omitempty"`

	// The error title describing the particular error.
	//
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// DetailedErrors
	Errors map[string]string `json:"errors,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetScriptsUnprocessableEntityBody) UnmarshalJSON(raw []byte) error {
	// GetScriptsUnprocessableEntityBodyAO0
	var dataGetScriptsUnprocessableEntityBodyAO0 struct {
		Instance string `json:"instance,omitempty"`

		Status int64 `json:"status,omitempty"`

		Title string `json:"title,omitempty"`

		Type string `json:"type,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetScriptsUnprocessableEntityBodyAO0); err != nil {
		return err
	}

	o.Instance = dataGetScriptsUnprocessableEntityBodyAO0.Instance

	o.Status = dataGetScriptsUnprocessableEntityBodyAO0.Status

	o.Title = dataGetScriptsUnprocessableEntityBodyAO0.Title

	o.Type = dataGetScriptsUnprocessableEntityBodyAO0.Type

	// GetScriptsUnprocessableEntityBodyAO1
	var dataGetScriptsUnprocessableEntityBodyAO1 struct {
		Errors map[string]string `json:"errors,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataGetScriptsUnprocessableEntityBodyAO1); err != nil {
		return err
	}

	o.Errors = dataGetScriptsUnprocessableEntityBodyAO1.Errors

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetScriptsUnprocessableEntityBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataGetScriptsUnprocessableEntityBodyAO0 struct {
		Instance string `json:"instance,omitempty"`

		Status int64 `json:"status,omitempty"`

		Title string `json:"title,omitempty"`

		Type string `json:"type,omitempty"`
	}

	dataGetScriptsUnprocessableEntityBodyAO0.Instance = o.Instance

	dataGetScriptsUnprocessableEntityBodyAO0.Status = o.Status

	dataGetScriptsUnprocessableEntityBodyAO0.Title = o.Title

	dataGetScriptsUnprocessableEntityBodyAO0.Type = o.Type

	jsonDataGetScriptsUnprocessableEntityBodyAO0, errGetScriptsUnprocessableEntityBodyAO0 := swag.WriteJSON(dataGetScriptsUnprocessableEntityBodyAO0)
	if errGetScriptsUnprocessableEntityBodyAO0 != nil {
		return nil, errGetScriptsUnprocessableEntityBodyAO0
	}
	_parts = append(_parts, jsonDataGetScriptsUnprocessableEntityBodyAO0)
	var dataGetScriptsUnprocessableEntityBodyAO1 struct {
		Errors map[string]string `json:"errors,omitempty"`
	}

	dataGetScriptsUnprocessableEntityBodyAO1.Errors = o.Errors

	jsonDataGetScriptsUnprocessableEntityBodyAO1, errGetScriptsUnprocessableEntityBodyAO1 := swag.WriteJSON(dataGetScriptsUnprocessableEntityBodyAO1)
	if errGetScriptsUnprocessableEntityBodyAO1 != nil {
		return nil, errGetScriptsUnprocessableEntityBodyAO1
	}
	_parts = append(_parts, jsonDataGetScriptsUnprocessableEntityBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get scripts unprocessable entity body
func (o *GetScriptsUnprocessableEntityBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *GetScriptsUnprocessableEntityBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetScriptsUnprocessableEntityBody) UnmarshalBinary(b []byte) error {
	var res GetScriptsUnprocessableEntityBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
