// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OrderCustomProduct orderCustomProduct
//
// swagger:model orderCustomProduct
type OrderCustomProduct struct {

	// name
	// Required: true
	Name *string `json:"name"`

	// price ex tax
	// Required: true
	PriceExTax *float64 `json:"price_ex_tax"`

	// price inc tax
	// Required: true
	PriceIncTax *float64 `json:"price_inc_tax"`

	// quantity
	// Required: true
	Quantity *float64 `json:"quantity"`

	// sku
	Sku string `json:"sku,omitempty"`

	// upc
	Upc string `json:"upc,omitempty"`
}

// Validate validates this order custom product
func (m *OrderCustomProduct) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePriceExTax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePriceIncTax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuantity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderCustomProduct) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *OrderCustomProduct) validatePriceExTax(formats strfmt.Registry) error {

	if err := validate.Required("price_ex_tax", "body", m.PriceExTax); err != nil {
		return err
	}

	return nil
}

func (m *OrderCustomProduct) validatePriceIncTax(formats strfmt.Registry) error {

	if err := validate.Required("price_inc_tax", "body", m.PriceIncTax); err != nil {
		return err
	}

	return nil
}

func (m *OrderCustomProduct) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("quantity", "body", m.Quantity); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderCustomProduct) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderCustomProduct) UnmarshalBinary(b []byte) error {
	var res OrderCustomProduct
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
