// Code generated by go-swagger; DO NOT EDIT.

package cart_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateCartLineItemParams creates a new UpdateCartLineItemParams object
// with the default values initialized.
func NewUpdateCartLineItemParams() *UpdateCartLineItemParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &UpdateCartLineItemParams{
		Accept:      acceptDefault,
		ContentType: contentTypeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCartLineItemParamsWithTimeout creates a new UpdateCartLineItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCartLineItemParamsWithTimeout(timeout time.Duration) *UpdateCartLineItemParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &UpdateCartLineItemParams{
		Accept:      acceptDefault,
		ContentType: contentTypeDefault,

		timeout: timeout,
	}
}

// NewUpdateCartLineItemParamsWithContext creates a new UpdateCartLineItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCartLineItemParamsWithContext(ctx context.Context) *UpdateCartLineItemParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &UpdateCartLineItemParams{
		Accept:      acceptDefault,
		ContentType: contentTypeDefault,

		Context: ctx,
	}
}

// NewUpdateCartLineItemParamsWithHTTPClient creates a new UpdateCartLineItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCartLineItemParamsWithHTTPClient(client *http.Client) *UpdateCartLineItemParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &UpdateCartLineItemParams{
		Accept:      acceptDefault,
		ContentType: contentTypeDefault,
		HTTPClient:  client,
	}
}

/*UpdateCartLineItemParams contains all the parameters to send to the API endpoint
for the update cart line item operation typically these are written to a http.Request
*/
type UpdateCartLineItemParams struct {

	/*Accept*/
	Accept string
	/*ContentType*/
	ContentType string
	/*CartID*/
	CartID string
	/*Include
	  * `redirect_urls`: Create a direct link to a Cart. This can be used during the /POST request for Carts.
	* `line_items.physical_items.options`: The Cart returns an abbreviated result. Use this to return physical items product options. Can also be used in a /POST to have the extended Cart object return.
	* `line_items.digital_items.options`: The Cart returns an abbreviated result. Use this to return digital items product options.  Can also be used in a /POST to have the extended Cart object return.

	*/
	Include *string
	/*ItemID*/
	ItemID string
	/*LineItem*/
	LineItem UpdateCartLineItemBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update cart line item params
func (o *UpdateCartLineItemParams) WithTimeout(timeout time.Duration) *UpdateCartLineItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update cart line item params
func (o *UpdateCartLineItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update cart line item params
func (o *UpdateCartLineItemParams) WithContext(ctx context.Context) *UpdateCartLineItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update cart line item params
func (o *UpdateCartLineItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update cart line item params
func (o *UpdateCartLineItemParams) WithHTTPClient(client *http.Client) *UpdateCartLineItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update cart line item params
func (o *UpdateCartLineItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccept adds the accept to the update cart line item params
func (o *UpdateCartLineItemParams) WithAccept(accept string) *UpdateCartLineItemParams {
	o.SetAccept(accept)
	return o
}

// SetAccept adds the accept to the update cart line item params
func (o *UpdateCartLineItemParams) SetAccept(accept string) {
	o.Accept = accept
}

// WithContentType adds the contentType to the update cart line item params
func (o *UpdateCartLineItemParams) WithContentType(contentType string) *UpdateCartLineItemParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the update cart line item params
func (o *UpdateCartLineItemParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithCartID adds the cartID to the update cart line item params
func (o *UpdateCartLineItemParams) WithCartID(cartID string) *UpdateCartLineItemParams {
	o.SetCartID(cartID)
	return o
}

// SetCartID adds the cartId to the update cart line item params
func (o *UpdateCartLineItemParams) SetCartID(cartID string) {
	o.CartID = cartID
}

// WithInclude adds the include to the update cart line item params
func (o *UpdateCartLineItemParams) WithInclude(include *string) *UpdateCartLineItemParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the update cart line item params
func (o *UpdateCartLineItemParams) SetInclude(include *string) {
	o.Include = include
}

// WithItemID adds the itemID to the update cart line item params
func (o *UpdateCartLineItemParams) WithItemID(itemID string) *UpdateCartLineItemParams {
	o.SetItemID(itemID)
	return o
}

// SetItemID adds the itemId to the update cart line item params
func (o *UpdateCartLineItemParams) SetItemID(itemID string) {
	o.ItemID = itemID
}

// WithLineItem adds the lineItem to the update cart line item params
func (o *UpdateCartLineItemParams) WithLineItem(lineItem UpdateCartLineItemBody) *UpdateCartLineItemParams {
	o.SetLineItem(lineItem)
	return o
}

// SetLineItem adds the lineItem to the update cart line item params
func (o *UpdateCartLineItemParams) SetLineItem(lineItem UpdateCartLineItemBody) {
	o.LineItem = lineItem
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCartLineItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Accept
	if err := r.SetHeaderParam("Accept", o.Accept); err != nil {
		return err
	}

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// path param cartId
	if err := r.SetPathParam("cartId", o.CartID); err != nil {
		return err
	}

	if o.Include != nil {

		// query param include
		var qrInclude string
		if o.Include != nil {
			qrInclude = *o.Include
		}
		qInclude := qrInclude
		if qInclude != "" {
			if err := r.SetQueryParam("include", qInclude); err != nil {
				return err
			}
		}

	}

	// path param itemId
	if err := r.SetPathParam("itemId", o.ItemID); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.LineItem); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
