// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BaseError Base Error
//
// Error payload for the BigCommerce API.
//
//
// swagger:model BaseError
type BaseError struct {

	// instance
	Instance string `json:"instance,omitempty"`

	// The HTTP status code.
	//
	Status int64 `json:"status,omitempty"`

	// The error title describing the particular error.
	//
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this base error
func (m *BaseError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BaseError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseError) UnmarshalBinary(b []byte) error {
	var res BaseError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
