// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestHeaders Request Headers
//
// These are the minium request headers needed for BigCommerce.
//
// swagger:model RequestHeaders
type RequestHeaders struct {

	// accepts
	Accepts *string `json:"Accepts,omitempty"`

	// x auth client
	XAuthClient string `json:"X-Auth-Client,omitempty"`
}

// Validate validates this request headers
func (m *RequestHeaders) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestHeaders) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestHeaders) UnmarshalBinary(b []byte) error {
	var res RequestHeaders
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
