// Code generated by go-swagger; DO NOT EDIT.

package price_lists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetPriceListCollectionReader is a Reader for the GetPriceListCollection structure.
type GetPriceListCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPriceListCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPriceListCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPriceListCollectionOK creates a GetPriceListCollectionOK with default headers values
func NewGetPriceListCollectionOK() *GetPriceListCollectionOK {
	return &GetPriceListCollectionOK{}
}

/*GetPriceListCollectionOK handles this case with default header values.

GetPriceListCollectionOK get price list collection o k
*/
type GetPriceListCollectionOK struct {
	Payload *GetPriceListCollectionOKBody
}

func (o *GetPriceListCollectionOK) Error() string {
	return fmt.Sprintf("[GET /pricelists][%d] getPriceListCollectionOK  %+v", 200, o.Payload)
}

func (o *GetPriceListCollectionOK) GetPayload() *GetPriceListCollectionOKBody {
	return o.Payload
}

func (o *GetPriceListCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPriceListCollectionOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetPriceListCollectionOKBody PriceList Collection Response
//
// Get All PriceLists.
swagger:model GetPriceListCollectionOKBody
*/
type GetPriceListCollectionOKBody struct {

	// data
	Data []*GetPriceListCollectionOKBodyDataItems0 `json:"data"`

	// meta
	Meta *GetPriceListCollectionOKBodyMeta `json:"meta,omitempty"`
}

// Validate validates this get price list collection o k body
func (o *GetPriceListCollectionOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPriceListCollectionOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getPriceListCollectionOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetPriceListCollectionOKBody) validateMeta(formats strfmt.Registry) error {

	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getPriceListCollectionOK" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPriceListCollectionOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPriceListCollectionOKBody) UnmarshalBinary(b []byte) error {
	var res GetPriceListCollectionOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPriceListCollectionOKBodyDataItems0 Price List
swagger:model GetPriceListCollectionOKBodyDataItems0
*/
type GetPriceListCollectionOKBodyDataItems0 struct {

	// The date on which the `Price List` was created.
	//
	// Format: date-time
	DateCreated strfmt.DateTime `json:"date_created,omitempty"`

	// The date on which the `Price List` was created.
	//
	// Format: date-time
	DateModified strfmt.DateTime `json:"date_modified,omitempty"`

	// The unique numeric ID of the `Price List`; increments sequentially.
	//
	ID int64 `json:"id,omitempty"`

	// Whether or not this `Price List` and its prices are active.  Defaults to `true`.
	//
	Active bool `json:"active,omitempty"`

	// The unique name of the Price List. Required in /POST.
	//
	// Required: true
	Name *string `json:"name"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetPriceListCollectionOKBodyDataItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		DateCreated strfmt.DateTime `json:"date_created,omitempty"`

		DateModified strfmt.DateTime `json:"date_modified,omitempty"`

		ID int64 `json:"id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	o.DateCreated = dataAO0.DateCreated

	o.DateModified = dataAO0.DateModified

	o.ID = dataAO0.ID

	// AO1
	var dataAO1 struct {
		Active bool `json:"active,omitempty"`

		Name *string `json:"name"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.Active = dataAO1.Active

	o.Name = dataAO1.Name

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetPriceListCollectionOKBodyDataItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		DateCreated strfmt.DateTime `json:"date_created,omitempty"`

		DateModified strfmt.DateTime `json:"date_modified,omitempty"`

		ID int64 `json:"id,omitempty"`
	}

	dataAO0.DateCreated = o.DateCreated

	dataAO0.DateModified = o.DateModified

	dataAO0.ID = o.ID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		Active bool `json:"active,omitempty"`

		Name *string `json:"name"`
	}

	dataAO1.Active = o.Active

	dataAO1.Name = o.Name

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get price list collection o k body data items0
func (o *GetPriceListCollectionOKBodyDataItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDateModified(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPriceListCollectionOKBodyDataItems0) validateDateCreated(formats strfmt.Registry) error {

	if swag.IsZero(o.DateCreated) { // not required
		return nil
	}

	if err := validate.FormatOf("date_created", "body", "date-time", o.DateCreated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetPriceListCollectionOKBodyDataItems0) validateDateModified(formats strfmt.Registry) error {

	if swag.IsZero(o.DateModified) { // not required
		return nil
	}

	if err := validate.FormatOf("date_modified", "body", "date-time", o.DateModified.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetPriceListCollectionOKBodyDataItems0) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPriceListCollectionOKBodyDataItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPriceListCollectionOKBodyDataItems0) UnmarshalBinary(b []byte) error {
	var res GetPriceListCollectionOKBodyDataItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPriceListCollectionOKBodyMeta Collection Meta
//
// Data about the response, including pagination and collection totals.
swagger:model GetPriceListCollectionOKBodyMeta
*/
type GetPriceListCollectionOKBodyMeta struct {

	// pagination
	Pagination *GetPriceListCollectionOKBodyMetaPagination `json:"pagination,omitempty"`
}

// Validate validates this get price list collection o k body meta
func (o *GetPriceListCollectionOKBodyMeta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePagination(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPriceListCollectionOKBodyMeta) validatePagination(formats strfmt.Registry) error {

	if swag.IsZero(o.Pagination) { // not required
		return nil
	}

	if o.Pagination != nil {
		if err := o.Pagination.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getPriceListCollectionOK" + "." + "meta" + "." + "pagination")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPriceListCollectionOKBodyMeta) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPriceListCollectionOKBodyMeta) UnmarshalBinary(b []byte) error {
	var res GetPriceListCollectionOKBodyMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPriceListCollectionOKBodyMetaPagination Pagination
//
// Data about the response, including pagination and collection totals.
swagger:model GetPriceListCollectionOKBodyMetaPagination
*/
type GetPriceListCollectionOKBodyMetaPagination struct {

	// Total number of items in the collection response.
	//
	Count int64 `json:"count,omitempty"`

	// The page you are currently on within the collection.
	//
	CurrentPage int64 `json:"current_page,omitempty"`

	// links
	Links *GetPriceListCollectionOKBodyMetaPaginationLinks `json:"links,omitempty"`

	// The amount of items returned in the collection per page, controlled by the limit parameter.
	//
	PerPage int64 `json:"per_page,omitempty"`

	// Total number of items in the result set.
	//
	Total int64 `json:"total,omitempty"`

	// The total number of pages in the collection.
	//
	TotalPages int64 `json:"total_pages,omitempty"`
}

// Validate validates this get price list collection o k body meta pagination
func (o *GetPriceListCollectionOKBodyMetaPagination) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPriceListCollectionOKBodyMetaPagination) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getPriceListCollectionOK" + "." + "meta" + "." + "pagination" + "." + "links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPriceListCollectionOKBodyMetaPagination) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPriceListCollectionOKBodyMetaPagination) UnmarshalBinary(b []byte) error {
	var res GetPriceListCollectionOKBodyMetaPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPriceListCollectionOKBodyMetaPaginationLinks Pagination links for the previous and next parts of the whole collection.
//
swagger:model GetPriceListCollectionOKBodyMetaPaginationLinks
*/
type GetPriceListCollectionOKBodyMetaPaginationLinks struct {

	// Link to the current page returned in the response.
	//
	Current string `json:"current,omitempty"`

	// Link to the next page returned in the response.
	//
	Next string `json:"next,omitempty"`

	// Link to the previous page returned in the response.
	//
	Previous string `json:"previous,omitempty"`
}

// Validate validates this get price list collection o k body meta pagination links
func (o *GetPriceListCollectionOKBodyMetaPaginationLinks) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPriceListCollectionOKBodyMetaPaginationLinks) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPriceListCollectionOKBodyMetaPaginationLinks) UnmarshalBinary(b []byte) error {
	var res GetPriceListCollectionOKBodyMetaPaginationLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
