// Code generated by go-swagger; DO NOT EDIT.

package price_lists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetPriceListReader is a Reader for the GetPriceList structure.
type GetPriceListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPriceListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPriceListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPriceListOK creates a GetPriceListOK with default headers values
func NewGetPriceListOK() *GetPriceListOK {
	return &GetPriceListOK{}
}

/*GetPriceListOK handles this case with default header values.

GetPriceListOK get price list o k
*/
type GetPriceListOK struct {
	Payload *GetPriceListOKBody
}

func (o *GetPriceListOK) Error() string {
	return fmt.Sprintf("[GET /pricelists/{price_list_id}][%d] getPriceListOK  %+v", 200, o.Payload)
}

func (o *GetPriceListOK) GetPayload() *GetPriceListOKBody {
	return o.Payload
}

func (o *GetPriceListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPriceListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetPriceListOKBody Price List Response
//
// PriceList Reponse returns for:
//
// * Create a PriceList
// * Get a PriceList
// * Update a PriceList
swagger:model GetPriceListOKBody
*/
type GetPriceListOKBody struct {

	// data
	Data *GetPriceListOKBodyData `json:"data,omitempty"`

	// Meta
	//
	// Empty meta object; may be used later.
	Meta interface{} `json:"meta,omitempty"`
}

// Validate validates this get price list o k body
func (o *GetPriceListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPriceListOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getPriceListOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPriceListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPriceListOKBody) UnmarshalBinary(b []byte) error {
	var res GetPriceListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPriceListOKBodyData Price List
//
// Common Price List properties.
swagger:model GetPriceListOKBodyData
*/
type GetPriceListOKBodyData struct {

	// Whether or not this `Price List` and its prices are active.  Defaults to `true`.
	//
	Active bool `json:"active,omitempty"`

	// The date on which the `Price List` was created.
	//
	// Format: date-time
	DateCreated strfmt.DateTime `json:"date_created,omitempty"`

	// The date on which the `Price List` was created.
	//
	// Format: date-time
	DateModified strfmt.DateTime `json:"date_modified,omitempty"`

	// The unique numeric ID of the `Price List`; increments sequentially.
	//
	ID int64 `json:"id,omitempty"`

	// The unique name of the Price List. Required in /POST.
	//
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this get price list o k body data
func (o *GetPriceListOKBodyData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDateModified(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPriceListOKBodyData) validateDateCreated(formats strfmt.Registry) error {

	if swag.IsZero(o.DateCreated) { // not required
		return nil
	}

	if err := validate.FormatOf("getPriceListOK"+"."+"data"+"."+"date_created", "body", "date-time", o.DateCreated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetPriceListOKBodyData) validateDateModified(formats strfmt.Registry) error {

	if swag.IsZero(o.DateModified) { // not required
		return nil
	}

	if err := validate.FormatOf("getPriceListOK"+"."+"data"+"."+"date_modified", "body", "date-time", o.DateModified.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *GetPriceListOKBodyData) validateName(formats strfmt.Registry) error {

	if err := validate.Required("getPriceListOK"+"."+"data"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPriceListOKBodyData) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPriceListOKBodyData) UnmarshalBinary(b []byte) error {
	var res GetPriceListOKBodyData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
