// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Pagination pagination
//
// Data about the response, including pagination and collection totals.
//
// swagger:model pagination
type Pagination struct {

	// Total number of items in the collection response.
	Count int32 `json:"count,omitempty"`

	// The page you are currently on within the collection.
	CurrentPage int32 `json:"current_page,omitempty"`

	// The amount of items returned in the collection per page, controlled by the limit parameter.
	PerPage int32 `json:"per_page,omitempty"`

	// Total number of items in the result set.
	Total int32 `json:"total,omitempty"`

	// The total number of pages in the collection.
	TotalPages int32 `json:"total_pages,omitempty"`
}

// Validate validates this pagination
func (m *Pagination) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Pagination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pagination) UnmarshalBinary(b []byte) error {
	var res Pagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
