// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WishlistItemFull wishlistItem_Full
//
// swagger:model wishlistItem_Full
type WishlistItemFull struct {

	// The ID of the item.
	ID int32 `json:"id,omitempty"`

	// The ID of the product.
	ProductID int32 `json:"product_id,omitempty"`

	// The variant ID of the product.
	VariantID int32 `json:"variant_id,omitempty"`
}

// Validate validates this wishlist item full
func (m *WishlistItemFull) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WishlistItemFull) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WishlistItemFull) UnmarshalBinary(b []byte) error {
	var res WishlistItemFull
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
