// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PriceRecord Price Record
//
// The Price Record object.
//
// swagger:model PriceRecord
type PriceRecord struct {

	// The price of the variant as seen on the storefront if a price record is in effect. It will be equal to the `sale_price`, if set, and the `price` if there is not a `sale_price`.  Read only.
	//
	CalculatedPrice float64 `json:"calculated_price,omitempty"`

	// The date on which the Price entry was created.
	//
	// Format: date-time
	DateCreated strfmt.DateTime `json:"date_created,omitempty"`

	// The date on which the Price entry was created.
	//
	// Format: date-time
	DateModified strfmt.DateTime `json:"date_modified,omitempty"`

	// The id of the `Product` this `Price Record`'s variant_id is associated with.  Read only.
	//
	ProductID int64 `json:"product_id,omitempty"`

	PriceRecordAllOf1

	// bulk pricing tiers
	BulkPricingTiers []*PriceRecordBulkPricingTiersItems0 `json:"bulk_pricing_tiers"`

	// The MAP (Manufacturer's Advertised Price) for the variant mapped in a Price List. Overrides any existing or Catalog MAP price for the variant/product. If empty, the MAP price will be treated as not being set on this variant.
	//
	MapPrice float64 `json:"map_price,omitempty"`

	// The list price for the variant mapped in a Price List. Overrides any existing or Catalog list price for the variant/product.
	//
	Price float64 `json:"price,omitempty"`

	// The retail price for the variant mapped in a Price List. Overrides any existing or Catalog retail price for the variant/product.  If empty, the retail price will be treated as not being set on this variant.
	//
	RetailPrice float64 `json:"retail_price,omitempty"`

	// The sale price for the variant mapped in a Price List. Overrides any existing or Catalog sale price for the variant/product. If empty, the sale price will be treated as not being set on this variant.
	//
	SalePrice float64 `json:"sale_price,omitempty"`

	// The SKU code associated with this `Price Record` if requested and it exists.
	//
	Sku string `json:"sku,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PriceRecord) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		CalculatedPrice float64 `json:"calculated_price,omitempty"`

		DateCreated strfmt.DateTime `json:"date_created,omitempty"`

		DateModified strfmt.DateTime `json:"date_modified,omitempty"`

		ProductID int64 `json:"product_id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.CalculatedPrice = dataAO0.CalculatedPrice

	m.DateCreated = dataAO0.DateCreated

	m.DateModified = dataAO0.DateModified

	m.ProductID = dataAO0.ProductID

	// AO1
	var aO1 PriceRecordAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.PriceRecordAllOf1 = aO1

	// AO2
	var dataAO2 struct {
		BulkPricingTiers []*PriceRecordBulkPricingTiersItems0 `json:"bulk_pricing_tiers"`

		MapPrice float64 `json:"map_price,omitempty"`

		Price float64 `json:"price,omitempty"`

		RetailPrice float64 `json:"retail_price,omitempty"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO2); err != nil {
		return err
	}

	m.BulkPricingTiers = dataAO2.BulkPricingTiers

	m.MapPrice = dataAO2.MapPrice

	m.Price = dataAO2.Price

	m.RetailPrice = dataAO2.RetailPrice

	m.SalePrice = dataAO2.SalePrice

	m.Sku = dataAO2.Sku

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PriceRecord) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	var dataAO0 struct {
		CalculatedPrice float64 `json:"calculated_price,omitempty"`

		DateCreated strfmt.DateTime `json:"date_created,omitempty"`

		DateModified strfmt.DateTime `json:"date_modified,omitempty"`

		ProductID int64 `json:"product_id,omitempty"`
	}

	dataAO0.CalculatedPrice = m.CalculatedPrice

	dataAO0.DateCreated = m.DateCreated

	dataAO0.DateModified = m.DateModified

	dataAO0.ProductID = m.ProductID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)

	aO1, err := swag.WriteJSON(m.PriceRecordAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	var dataAO2 struct {
		BulkPricingTiers []*PriceRecordBulkPricingTiersItems0 `json:"bulk_pricing_tiers"`

		MapPrice float64 `json:"map_price,omitempty"`

		Price float64 `json:"price,omitempty"`

		RetailPrice float64 `json:"retail_price,omitempty"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`
	}

	dataAO2.BulkPricingTiers = m.BulkPricingTiers

	dataAO2.MapPrice = m.MapPrice

	dataAO2.Price = m.Price

	dataAO2.RetailPrice = m.RetailPrice

	dataAO2.SalePrice = m.SalePrice

	dataAO2.Sku = m.Sku

	jsonDataAO2, errAO2 := swag.WriteJSON(dataAO2)
	if errAO2 != nil {
		return nil, errAO2
	}
	_parts = append(_parts, jsonDataAO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this price record
func (m *PriceRecord) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDateModified(formats); err != nil {
		res = append(res, err)
	}

	// validation for a type composition with PriceRecordAllOf1
	if err := m.PriceRecordAllOf1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBulkPricingTiers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PriceRecord) validateDateCreated(formats strfmt.Registry) error {

	if swag.IsZero(m.DateCreated) { // not required
		return nil
	}

	if err := validate.FormatOf("date_created", "body", "date-time", m.DateCreated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PriceRecord) validateDateModified(formats strfmt.Registry) error {

	if swag.IsZero(m.DateModified) { // not required
		return nil
	}

	if err := validate.FormatOf("date_modified", "body", "date-time", m.DateModified.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PriceRecord) validateBulkPricingTiers(formats strfmt.Registry) error {

	if swag.IsZero(m.BulkPricingTiers) { // not required
		return nil
	}

	for i := 0; i < len(m.BulkPricingTiers); i++ {
		if swag.IsZero(m.BulkPricingTiers[i]) { // not required
			continue
		}

		if m.BulkPricingTiers[i] != nil {
			if err := m.BulkPricingTiers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("bulk_pricing_tiers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PriceRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PriceRecord) UnmarshalBinary(b []byte) error {
	var res PriceRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PriceRecordAllOf1 Price Record Identifiers
//
// Price Record object used in batch create or update.
//
// swagger:model PriceRecordAllOf1
type PriceRecordAllOf1 struct {

	// The 3-letter currency code with which this price set is associated.
	//
	Currency string `json:"currency,omitempty"`

	// The Price List with which this price set is associated.
	//
	PriceListID int64 `json:"price_list_id,omitempty"`

	// The variant with which this price set is associated. Either sku or variant_id is required.
	//
	Sku string `json:"sku,omitempty"`

	// The variant with which this price set is associated. Either variant_id or sku is required.
	//
	VariantID int64 `json:"variant_id,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PriceRecordAllOf1) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		Currency string `json:"currency,omitempty"`

		PriceListID int64 `json:"price_list_id,omitempty"`

		Sku string `json:"sku,omitempty"`

		VariantID int64 `json:"variant_id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.Currency = dataAO0.Currency

	m.PriceListID = dataAO0.PriceListID

	m.Sku = dataAO0.Sku

	m.VariantID = dataAO0.VariantID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PriceRecordAllOf1) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		Currency string `json:"currency,omitempty"`

		PriceListID int64 `json:"price_list_id,omitempty"`

		Sku string `json:"sku,omitempty"`

		VariantID int64 `json:"variant_id,omitempty"`
	}

	dataAO0.Currency = m.Currency

	dataAO0.PriceListID = m.PriceListID

	dataAO0.Sku = m.Sku

	dataAO0.VariantID = m.VariantID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this price record all of1
func (m *PriceRecordAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PriceRecordAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PriceRecordAllOf1) UnmarshalBinary(b []byte) error {
	var res PriceRecordAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PriceRecordBulkPricingTiersItems0 Bulk Pricing Tier
//
// swagger:model PriceRecordBulkPricingTiersItems0
type PriceRecordBulkPricingTiersItems0 struct {

	// The price adjustment amount. This value along with the type will decide the price per variant for the pricing tier.
	//
	Amount float64 `json:"amount,omitempty"`

	// The maximum allowed quantity of associated variant in the cart to qualify for this tiers pricing.
	//
	QuantityMax int64 `json:"quantity_max,omitempty"`

	// The minimum quantity of associated variant in the cart needed to qualify for this tiers pricing.
	//
	QuantityMin int64 `json:"quantity_min,omitempty"`

	// The type of adjustment that is made. Acceptable values: price – the adjustment amount per product; percent – the adjustment as a percentage of the original price; fixed – the adjusted absolute price of the product.
	//
	// Enum: [fixed price percent]
	Type string `json:"type,omitempty"`
}

// Validate validates this price record bulk pricing tiers items0
func (m *PriceRecordBulkPricingTiersItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var priceRecordBulkPricingTiersItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["fixed","price","percent"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		priceRecordBulkPricingTiersItems0TypeTypePropEnum = append(priceRecordBulkPricingTiersItems0TypeTypePropEnum, v)
	}
}

const (

	// PriceRecordBulkPricingTiersItems0TypeFixed captures enum value "fixed"
	PriceRecordBulkPricingTiersItems0TypeFixed string = "fixed"

	// PriceRecordBulkPricingTiersItems0TypePrice captures enum value "price"
	PriceRecordBulkPricingTiersItems0TypePrice string = "price"

	// PriceRecordBulkPricingTiersItems0TypePercent captures enum value "percent"
	PriceRecordBulkPricingTiersItems0TypePercent string = "percent"
)

// prop value enum
func (m *PriceRecordBulkPricingTiersItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, priceRecordBulkPricingTiersItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PriceRecordBulkPricingTiersItems0) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PriceRecordBulkPricingTiersItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PriceRecordBulkPricingTiersItems0) UnmarshalBinary(b []byte) error {
	var res PriceRecordBulkPricingTiersItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
