// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SubscriberPost subscriber_Post
//
// The model for a POST to create a subscriber.
//
//
// swagger:model subscriber_Post
type SubscriberPost struct {

	// The channel ID where the subscriber was created.
	// Maximum: 2.147483647e+09
	// Minimum: 1
	ChannelID int64 `json:"channel_id,omitempty"`

	// The email of the subscriber. Must be unique.
	//
	Email string `json:"email,omitempty"`

	// The first name of the subscriber.
	//
	// Max Length: 255
	// Min Length: 0
	FirstName *string `json:"first_name,omitempty"`

	// The last name of the subscriber.
	//
	// Max Length: 255
	// Min Length: 0
	LastName *string `json:"last_name,omitempty"`

	// The ID of the source order, if source was an order.
	//
	// Maximum: 2.147483647e+09
	// Minimum: 1
	OrderID *int64 `json:"order_id,omitempty"`

	// The source of the subscriber. Values are: `storefront`, `order`, or `custom`.
	//
	// Max Length: 255
	// Min Length: 0
	Source *string `json:"source,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SubscriberPost) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		ChannelID int64 `json:"channel_id,omitempty"`

		Email string `json:"email,omitempty"`

		FirstName *string `json:"first_name,omitempty"`

		LastName *string `json:"last_name,omitempty"`

		OrderID *int64 `json:"order_id,omitempty"`

		Source *string `json:"source,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.ChannelID = dataAO0.ChannelID

	m.Email = dataAO0.Email

	m.FirstName = dataAO0.FirstName

	m.LastName = dataAO0.LastName

	m.OrderID = dataAO0.OrderID

	m.Source = dataAO0.Source

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SubscriberPost) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		ChannelID int64 `json:"channel_id,omitempty"`

		Email string `json:"email,omitempty"`

		FirstName *string `json:"first_name,omitempty"`

		LastName *string `json:"last_name,omitempty"`

		OrderID *int64 `json:"order_id,omitempty"`

		Source *string `json:"source,omitempty"`
	}

	dataAO0.ChannelID = m.ChannelID

	dataAO0.Email = m.Email

	dataAO0.FirstName = m.FirstName

	dataAO0.LastName = m.LastName

	dataAO0.OrderID = m.OrderID

	dataAO0.Source = m.Source

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this subscriber post
func (m *SubscriberPost) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChannelID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFirstName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrderID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubscriberPost) validateChannelID(formats strfmt.Registry) error {

	if swag.IsZero(m.ChannelID) { // not required
		return nil
	}

	if err := validate.MinimumInt("channel_id", "body", int64(m.ChannelID), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("channel_id", "body", int64(m.ChannelID), 2.147483647e+09, false); err != nil {
		return err
	}

	return nil
}

func (m *SubscriberPost) validateFirstName(formats strfmt.Registry) error {

	if swag.IsZero(m.FirstName) { // not required
		return nil
	}

	if err := validate.MinLength("first_name", "body", string(*m.FirstName), 0); err != nil {
		return err
	}

	if err := validate.MaxLength("first_name", "body", string(*m.FirstName), 255); err != nil {
		return err
	}

	return nil
}

func (m *SubscriberPost) validateLastName(formats strfmt.Registry) error {

	if swag.IsZero(m.LastName) { // not required
		return nil
	}

	if err := validate.MinLength("last_name", "body", string(*m.LastName), 0); err != nil {
		return err
	}

	if err := validate.MaxLength("last_name", "body", string(*m.LastName), 255); err != nil {
		return err
	}

	return nil
}

func (m *SubscriberPost) validateOrderID(formats strfmt.Registry) error {

	if swag.IsZero(m.OrderID) { // not required
		return nil
	}

	if err := validate.MinimumInt("order_id", "body", int64(*m.OrderID), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("order_id", "body", int64(*m.OrderID), 2.147483647e+09, false); err != nil {
		return err
	}

	return nil
}

func (m *SubscriberPost) validateSource(formats strfmt.Registry) error {

	if swag.IsZero(m.Source) { // not required
		return nil
	}

	if err := validate.MinLength("source", "body", string(*m.Source), 0); err != nil {
		return err
	}

	if err := validate.MaxLength("source", "body", string(*m.Source), 255); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SubscriberPost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscriberPost) UnmarshalBinary(b []byte) error {
	var res SubscriberPost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
