// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewModel new model
//
// swagger:model new-model
type NewModel []*NewModelItems0

// Validate validates this new model
func (m NewModel) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// NewModelItems0 new model items0
//
// swagger:model NewModelItems0
type NewModelItems0 struct {

	// conditional
	Conditional *NewModelItems0Conditional `json:"conditional,omitempty"`

	// default
	Default int64 `json:"default,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// label
	Label string `json:"label,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// type meta
	TypeMeta string `json:"typeMeta,omitempty"`
}

// Validate validates this new model items0
func (m *NewModelItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConditional(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NewModelItems0) validateConditional(formats strfmt.Registry) error {

	if swag.IsZero(m.Conditional) { // not required
		return nil
	}

	if m.Conditional != nil {
		if err := m.Conditional.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("conditional")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NewModelItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewModelItems0) UnmarshalBinary(b []byte) error {
	var res NewModelItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// NewModelItems0Conditional widgetSchemaConditional
//
// An optional property that can be added to each setting to control whether it should be displayed to the user while editing in Page Builder. This does not clear the value in the setting, just controls the display of the setting.
//
// swagger:model NewModelItems0Conditional
type NewModelItems0Conditional struct {

	// The ID of the `setting` object the conditional attribute is related to.
	Key string `json:"key,omitempty"`

	// Specifies the operation used to determine whether to display the setting. The `IN` operator is currently the only supported operator. The setting will be displayed if the conditional’s `value` property is equal to the selected value of the `selectOptions`.
	Operator string `json:"operator,omitempty"`

	// A single-object array containing a value from the `typeMeta`'s `selectOptions`.
	Value []interface{} `json:"value"`
}

// Validate validates this new model items0 conditional
func (m *NewModelItems0Conditional) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewModelItems0Conditional) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewModelItems0Conditional) UnmarshalBinary(b []byte) error {
	var res NewModelItems0Conditional
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
