// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlacementPost placement_Post
//
// swagger:model placement_Post
type PlacementPost struct {

	// The template file that you would like to target.
	// Required: true
	TemplateFile *string `json:"template_file"`

	// A widget identifier.
	// Required: true
	WidgetUUID *string `json:"widget_uuid"`

	// The identifier of a page you would like to target. For product pages, choose product ID. For category pages, choose category ID. Home page does not support `entity_id`.
	EntityID string `json:"entity_id,omitempty"`

	// The name of the region in which to insert content widgets.
	Region string `json:"region,omitempty"`

	// The sort order to control the position of a content widget in a region.
	SortOrder int64 `json:"sort_order,omitempty"`

	// Sets the placement as either inactive or active.
	// Enum: [inactive active]
	Status *string `json:"status,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PlacementPost) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		TemplateFile *string `json:"template_file"`

		WidgetUUID *string `json:"widget_uuid"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.TemplateFile = dataAO0.TemplateFile

	m.WidgetUUID = dataAO0.WidgetUUID

	// AO1
	var dataAO1 struct {
		EntityID string `json:"entity_id,omitempty"`

		Region string `json:"region,omitempty"`

		SortOrder int64 `json:"sort_order,omitempty"`

		Status *string `json:"status,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.EntityID = dataAO1.EntityID

	m.Region = dataAO1.Region

	m.SortOrder = dataAO1.SortOrder

	m.Status = dataAO1.Status

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PlacementPost) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		TemplateFile *string `json:"template_file"`

		WidgetUUID *string `json:"widget_uuid"`
	}

	dataAO0.TemplateFile = m.TemplateFile

	dataAO0.WidgetUUID = m.WidgetUUID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		EntityID string `json:"entity_id,omitempty"`

		Region string `json:"region,omitempty"`

		SortOrder int64 `json:"sort_order,omitempty"`

		Status *string `json:"status,omitempty"`
	}

	dataAO1.EntityID = m.EntityID

	dataAO1.Region = m.Region

	dataAO1.SortOrder = m.SortOrder

	dataAO1.Status = m.Status

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this placement post
func (m *PlacementPost) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTemplateFile(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWidgetUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlacementPost) validateTemplateFile(formats strfmt.Registry) error {

	if err := validate.Required("template_file", "body", m.TemplateFile); err != nil {
		return err
	}

	return nil
}

func (m *PlacementPost) validateWidgetUUID(formats strfmt.Registry) error {

	if err := validate.Required("widget_uuid", "body", m.WidgetUUID); err != nil {
		return err
	}

	return nil
}

var placementPostTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["inactive","active"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		placementPostTypeStatusPropEnum = append(placementPostTypeStatusPropEnum, v)
	}
}

// property enum
func (m *PlacementPost) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, placementPostTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PlacementPost) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlacementPost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlacementPost) UnmarshalBinary(b []byte) error {
	var res PlacementPost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
