// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WidgetSchemaHidden widgetSchemaHidden
//
// **Hidden.** Use the **hidden** settings type to create controls that have no user interface drawn in Page Builder. Hidden settings are not grouped into any other tabs or arrays.
//
// swagger:model widgetSchemaHidden
type WidgetSchemaHidden struct {

	// settings
	Settings []*WidgetSchemaHiddenSettingsItems0 `json:"settings"`

	// type
	Type string `json:"type,omitempty"`
}

// for schema
var widgetSchemaHiddenEnum []interface{}

func init() {
	var res []WidgetSchemaHidden
	if err := json.Unmarshal([]byte(`["hidden"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		widgetSchemaHiddenEnum = append(widgetSchemaHiddenEnum, v)
	}
}

func (m *WidgetSchemaHidden) validateWidgetSchemaHiddenEnum(path, location string, value *WidgetSchemaHidden) error {
	if err := validate.EnumCase(path, location, value, widgetSchemaHiddenEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this widget schema hidden
func (m *WidgetSchemaHidden) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSettings(formats); err != nil {
		res = append(res, err)
	}

	// value enum
	if err := m.validateWidgetSchemaHiddenEnum("", "body", m); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WidgetSchemaHidden) validateSettings(formats strfmt.Registry) error {

	if swag.IsZero(m.Settings) { // not required
		return nil
	}

	for i := 0; i < len(m.Settings); i++ {
		if swag.IsZero(m.Settings[i]) { // not required
			continue
		}

		if m.Settings[i] != nil {
			if err := m.Settings[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("settings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *WidgetSchemaHidden) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetSchemaHidden) UnmarshalBinary(b []byte) error {
	var res WidgetSchemaHidden
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// WidgetSchemaHiddenSettingsItems0 widgetSchemaSetting_Base
//
// For examples of each type of setting, see [Page Builder > Schema Settings](https://developer.bigcommerce.com/stencil-docs/page-builder/schema-settings/alignment) in Theme Docs.
//
// swagger:model WidgetSchemaHiddenSettingsItems0
type WidgetSchemaHiddenSettingsItems0 struct {

	// conditional
	Conditional *WidgetSchemaHiddenSettingsItems0Conditional `json:"conditional,omitempty"`

	// The default value to use when rendering the widget for the first time. Make sure to set sensible defaults to make your widget easier to use.
	Default string `json:"default,omitempty"`

	// The variable name where the setting value will be available in the widget template.
	ID string `json:"id,omitempty"`

	// The user friendly message to inform the user how this setting will be used.
	Label string `json:"label,omitempty"`

	// The type of setting component to display. You can view the list of elements below to discover which are available to use.
	//
	// For examples of each type of setting, see [Page Builder > Schema Settings](https://developer.bigcommerce.com/stencil-docs/page-builder/schema-settings/alignment) in Theme Docs.
	// Enum: [alignment boolean boxModel code color imageManager input number productId productImage range regexInput select text toggle]
	Type string `json:"type,omitempty"`

	// type meta
	TypeMeta *WidgetSchemaHiddenSettingsItems0TypeMeta `json:"typeMeta,omitempty"`
}

// Validate validates this widget schema hidden settings items0
func (m *WidgetSchemaHiddenSettingsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConditional(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTypeMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WidgetSchemaHiddenSettingsItems0) validateConditional(formats strfmt.Registry) error {

	if swag.IsZero(m.Conditional) { // not required
		return nil
	}

	if m.Conditional != nil {
		if err := m.Conditional.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("conditional")
			}
			return err
		}
	}

	return nil
}

var widgetSchemaHiddenSettingsItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["alignment","boolean","boxModel","code","color","imageManager","input","number","productId","productImage","range","regexInput","select","text","toggle"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		widgetSchemaHiddenSettingsItems0TypeTypePropEnum = append(widgetSchemaHiddenSettingsItems0TypeTypePropEnum, v)
	}
}

const (

	// WidgetSchemaHiddenSettingsItems0TypeAlignment captures enum value "alignment"
	WidgetSchemaHiddenSettingsItems0TypeAlignment string = "alignment"

	// WidgetSchemaHiddenSettingsItems0TypeBoolean captures enum value "boolean"
	WidgetSchemaHiddenSettingsItems0TypeBoolean string = "boolean"

	// WidgetSchemaHiddenSettingsItems0TypeBoxModel captures enum value "boxModel"
	WidgetSchemaHiddenSettingsItems0TypeBoxModel string = "boxModel"

	// WidgetSchemaHiddenSettingsItems0TypeCode captures enum value "code"
	WidgetSchemaHiddenSettingsItems0TypeCode string = "code"

	// WidgetSchemaHiddenSettingsItems0TypeColor captures enum value "color"
	WidgetSchemaHiddenSettingsItems0TypeColor string = "color"

	// WidgetSchemaHiddenSettingsItems0TypeImageManager captures enum value "imageManager"
	WidgetSchemaHiddenSettingsItems0TypeImageManager string = "imageManager"

	// WidgetSchemaHiddenSettingsItems0TypeInput captures enum value "input"
	WidgetSchemaHiddenSettingsItems0TypeInput string = "input"

	// WidgetSchemaHiddenSettingsItems0TypeNumber captures enum value "number"
	WidgetSchemaHiddenSettingsItems0TypeNumber string = "number"

	// WidgetSchemaHiddenSettingsItems0TypeProductID captures enum value "productId"
	WidgetSchemaHiddenSettingsItems0TypeProductID string = "productId"

	// WidgetSchemaHiddenSettingsItems0TypeProductImage captures enum value "productImage"
	WidgetSchemaHiddenSettingsItems0TypeProductImage string = "productImage"

	// WidgetSchemaHiddenSettingsItems0TypeRange captures enum value "range"
	WidgetSchemaHiddenSettingsItems0TypeRange string = "range"

	// WidgetSchemaHiddenSettingsItems0TypeRegexInput captures enum value "regexInput"
	WidgetSchemaHiddenSettingsItems0TypeRegexInput string = "regexInput"

	// WidgetSchemaHiddenSettingsItems0TypeSelect captures enum value "select"
	WidgetSchemaHiddenSettingsItems0TypeSelect string = "select"

	// WidgetSchemaHiddenSettingsItems0TypeText captures enum value "text"
	WidgetSchemaHiddenSettingsItems0TypeText string = "text"

	// WidgetSchemaHiddenSettingsItems0TypeToggle captures enum value "toggle"
	WidgetSchemaHiddenSettingsItems0TypeToggle string = "toggle"
)

// prop value enum
func (m *WidgetSchemaHiddenSettingsItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, widgetSchemaHiddenSettingsItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WidgetSchemaHiddenSettingsItems0) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *WidgetSchemaHiddenSettingsItems0) validateTypeMeta(formats strfmt.Registry) error {

	if swag.IsZero(m.TypeMeta) { // not required
		return nil
	}

	if m.TypeMeta != nil {
		if err := m.TypeMeta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("typeMeta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WidgetSchemaHiddenSettingsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetSchemaHiddenSettingsItems0) UnmarshalBinary(b []byte) error {
	var res WidgetSchemaHiddenSettingsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// WidgetSchemaHiddenSettingsItems0Conditional widgetSchemaConditional
//
// An optional property that can be added to each setting to control whether it should be displayed to the user while editing in Page Builder. This does not clear the value in the setting, just controls the display of the setting.
//
// swagger:model WidgetSchemaHiddenSettingsItems0Conditional
type WidgetSchemaHiddenSettingsItems0Conditional struct {

	// The ID of the `setting` object the conditional attribute is related to.
	Key string `json:"key,omitempty"`

	// Specifies the operation used to determine whether to display the setting. The `IN` operator is currently the only supported operator. The setting will be displayed if the conditional’s `value` property is equal to the selected value of the `selectOptions`.
	Operator string `json:"operator,omitempty"`

	// A single-object array containing a value from the `typeMeta`'s `selectOptions`.
	Value []interface{} `json:"value"`
}

// Validate validates this widget schema hidden settings items0 conditional
func (m *WidgetSchemaHiddenSettingsItems0Conditional) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WidgetSchemaHiddenSettingsItems0Conditional) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetSchemaHiddenSettingsItems0Conditional) UnmarshalBinary(b []byte) error {
	var res WidgetSchemaHiddenSettingsItems0Conditional
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// WidgetSchemaHiddenSettingsItems0TypeMeta Additional information needed based on the selected setting type.
//
// swagger:model WidgetSchemaHiddenSettingsItems0TypeMeta
type WidgetSchemaHiddenSettingsItems0TypeMeta struct {

	// select options
	SelectOptions []*WidgetSchemaHiddenSettingsItems0TypeMetaSelectOptionsItems0 `json:"selectOptions"`
}

// Validate validates this widget schema hidden settings items0 type meta
func (m *WidgetSchemaHiddenSettingsItems0TypeMeta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSelectOptions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WidgetSchemaHiddenSettingsItems0TypeMeta) validateSelectOptions(formats strfmt.Registry) error {

	if swag.IsZero(m.SelectOptions) { // not required
		return nil
	}

	for i := 0; i < len(m.SelectOptions); i++ {
		if swag.IsZero(m.SelectOptions[i]) { // not required
			continue
		}

		if m.SelectOptions[i] != nil {
			if err := m.SelectOptions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("typeMeta" + "." + "selectOptions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *WidgetSchemaHiddenSettingsItems0TypeMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetSchemaHiddenSettingsItems0TypeMeta) UnmarshalBinary(b []byte) error {
	var res WidgetSchemaHiddenSettingsItems0TypeMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// WidgetSchemaHiddenSettingsItems0TypeMetaSelectOptionsItems0 widget schema hidden settings items0 type meta select options items0
//
// swagger:model WidgetSchemaHiddenSettingsItems0TypeMetaSelectOptionsItems0
type WidgetSchemaHiddenSettingsItems0TypeMetaSelectOptionsItems0 struct {

	// label
	Label string `json:"label,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this widget schema hidden settings items0 type meta select options items0
func (m *WidgetSchemaHiddenSettingsItems0TypeMetaSelectOptionsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WidgetSchemaHiddenSettingsItems0TypeMetaSelectOptionsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetSchemaHiddenSettingsItems0TypeMetaSelectOptionsItems0) UnmarshalBinary(b []byte) error {
	var res WidgetSchemaHiddenSettingsItems0TypeMetaSelectOptionsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
