// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WidgetTemplateBase widgetTemplate_Base
//
// swagger:model widgetTemplate_Base
type WidgetTemplateBase struct {

	// The user-friendly name.
	Name string `json:"name,omitempty"`

	// The schema for the widget's merchant-facing UI. For more information on the available schema settings, see [Widget UI Schema](https://developer.bigcommerce.com/stencil-docs/page-builder/widget-ui-schema).
	Schema []interface{} `json:"schema"`

	// The GraphQL Storefront API query that provides widget data.
	StorefrontAPIQuery string `json:"storefront_api_query,omitempty"`

	// The widget template HTML. Supports Handlebars and Paper helpers.
	Template string `json:"template,omitempty"`
}

// Validate validates this widget template base
func (m *WidgetTemplateBase) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WidgetTemplateBase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetTemplateBase) UnmarshalBinary(b []byte) error {
	var res WidgetTemplateBase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
