// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WidgetBase widget_Base
//
// swagger:model widget_Base
type WidgetBase struct {

	// The user-friendly description.
	Description string `json:"description,omitempty"`

	// The user-friendly name.
	Name string `json:"name,omitempty"`

	// The JSON data that populates the template.
	WidgetConfiguration interface{} `json:"widget_configuration,omitempty"`
}

// Validate validates this widget base
func (m *WidgetBase) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WidgetBase) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetBase) UnmarshalBinary(b []byte) error {
	var res WidgetBase
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
