// Code generated by go-swagger; DO NOT EDIT.

package order_shipping_addresses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetAllShippingAddressesReader is a Reader for the GetAllShippingAddresses structure.
type GetAllShippingAddressesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllShippingAddressesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllShippingAddressesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllShippingAddressesOK creates a GetAllShippingAddressesOK with default headers values
func NewGetAllShippingAddressesOK() *GetAllShippingAddressesOK {
	return &GetAllShippingAddressesOK{}
}

/*GetAllShippingAddressesOK handles this case with default header values.

GetAllShippingAddressesOK get all shipping addresses o k
*/
type GetAllShippingAddressesOK struct {
	Payload []*GetAllShippingAddressesOKBodyItems0
}

func (o *GetAllShippingAddressesOK) Error() string {
	return fmt.Sprintf("[GET /orders/{order_id}/shipping_addresses][%d] getAllShippingAddressesOK  %+v", 200, o.Payload)
}

func (o *GetAllShippingAddressesOK) GetPayload() []*GetAllShippingAddressesOKBodyItems0 {
	return o.Payload
}

func (o *GetAllShippingAddressesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetAllShippingAddressesOKBodyItems0 orderShippingAddress
swagger:model GetAllShippingAddressesOKBodyItems0
*/
type GetAllShippingAddressesOKBodyItems0 struct {

	// The base value of the order’s items. (Float, Float-As-String, Integer)
	BaseCost string `json:"base_cost,omitempty"`

	// The base handling charge. (Float, Float-As-String, Integer)
	BaseHandlingCost string `json:"base_handling_cost,omitempty"`

	// The value of the order’s items, excluding tax. (Float, Float-As-String, Integer)
	CostExTax string `json:"cost_ex_tax,omitempty"`

	// The value of the order’s items, including tax. (Float, Float-As-String, Integer)
	CostIncTax string `json:"cost_inc_tax,omitempty"`

	// The tax amount on the order. (Float, Float-As-String, Integer)
	CostTax string `json:"cost_tax,omitempty"`

	// The ID of the tax class applied to the product. (NOTE: Value ignored if automatic tax is enabled.)
	CostTaxClassID int64 `json:"cost_tax_class_id,omitempty"`

	// form fields
	FormFields []*GetAllShippingAddressesOKBodyItems0FormFieldsItems0 `json:"form_fields"`

	// The handling charge, excluding tax. (Float, Float-As-String, Integer)
	HandlingCostExTax string `json:"handling_cost_ex_tax,omitempty"`

	// The handling charge, including tax. (Float, Float-As-String, Integer)
	HandlingCostIncTax string `json:"handling_cost_inc_tax,omitempty"`

	// handling cost tax
	HandlingCostTax string `json:"handling_cost_tax,omitempty"`

	// A read-only value. Do not attempt to set or modify this value in a POST or PUT operation. (NOTE: Value ignored if automatic tax is enabled on the store.)
	HandlingCostTaxClassID int64 `json:"handling_cost_tax_class_id,omitempty"`

	// ID of this shipping address.
	ID int64 `json:"id,omitempty"`

	// The number of items that have been shipped.
	ItemsShipped float64 `json:"items_shipped,omitempty"`

	// The total number of items in the order.
	ItemsTotal float64 `json:"items_total,omitempty"`

	// ID of the order.
	OrderID int64 `json:"order_id,omitempty"`

	// Text code identifying the BigCommerce shipping module selected by the customer.
	ShippingMethod string `json:"shipping_method,omitempty"`

	// shipping quotes
	ShippingQuotes *GetAllShippingAddressesOKBodyItems0AO0ShippingQuotes `json:"shipping_quotes,omitempty"`

	// Numeric ID of the shipping zone.
	ShippingZoneID float64 `json:"shipping_zone_id,omitempty"`

	// Name of the shipping zone.
	ShippingZoneName string `json:"shipping_zone_name,omitempty"`

	// city
	City string `json:"city,omitempty"`

	// company
	Company string `json:"company,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// 2-letter ISO Alpha-2 code for the country.
	CountryIso2 string `json:"country_iso2,omitempty"`

	// Recipient's email address.
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// Recipient's telephone number.
	Phone string `json:"phone,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// Street address (first line).
	Street1 string `json:"street_1,omitempty"`

	// Street address (second line).
	Street2 string `json:"street_2,omitempty"`

	// Zip or postal code, as a string.
	Zip string `json:"zip,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetAllShippingAddressesOKBodyItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		BaseCost string `json:"base_cost,omitempty"`

		BaseHandlingCost string `json:"base_handling_cost,omitempty"`

		CostExTax string `json:"cost_ex_tax,omitempty"`

		CostIncTax string `json:"cost_inc_tax,omitempty"`

		CostTax string `json:"cost_tax,omitempty"`

		CostTaxClassID int64 `json:"cost_tax_class_id,omitempty"`

		FormFields []*GetAllShippingAddressesOKBodyItems0FormFieldsItems0 `json:"form_fields"`

		HandlingCostExTax string `json:"handling_cost_ex_tax,omitempty"`

		HandlingCostIncTax string `json:"handling_cost_inc_tax,omitempty"`

		HandlingCostTax string `json:"handling_cost_tax,omitempty"`

		HandlingCostTaxClassID int64 `json:"handling_cost_tax_class_id,omitempty"`

		ID int64 `json:"id,omitempty"`

		ItemsShipped float64 `json:"items_shipped,omitempty"`

		ItemsTotal float64 `json:"items_total,omitempty"`

		OrderID int64 `json:"order_id,omitempty"`

		ShippingMethod string `json:"shipping_method,omitempty"`

		ShippingQuotes *GetAllShippingAddressesOKBodyItems0AO0ShippingQuotes `json:"shipping_quotes,omitempty"`

		ShippingZoneID float64 `json:"shipping_zone_id,omitempty"`

		ShippingZoneName string `json:"shipping_zone_name,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	o.BaseCost = dataAO0.BaseCost

	o.BaseHandlingCost = dataAO0.BaseHandlingCost

	o.CostExTax = dataAO0.CostExTax

	o.CostIncTax = dataAO0.CostIncTax

	o.CostTax = dataAO0.CostTax

	o.CostTaxClassID = dataAO0.CostTaxClassID

	o.FormFields = dataAO0.FormFields

	o.HandlingCostExTax = dataAO0.HandlingCostExTax

	o.HandlingCostIncTax = dataAO0.HandlingCostIncTax

	o.HandlingCostTax = dataAO0.HandlingCostTax

	o.HandlingCostTaxClassID = dataAO0.HandlingCostTaxClassID

	o.ID = dataAO0.ID

	o.ItemsShipped = dataAO0.ItemsShipped

	o.ItemsTotal = dataAO0.ItemsTotal

	o.OrderID = dataAO0.OrderID

	o.ShippingMethod = dataAO0.ShippingMethod

	o.ShippingQuotes = dataAO0.ShippingQuotes

	o.ShippingZoneID = dataAO0.ShippingZoneID

	o.ShippingZoneName = dataAO0.ShippingZoneName

	// AO1
	var dataAO1 struct {
		City string `json:"city,omitempty"`

		Company string `json:"company,omitempty"`

		Country string `json:"country,omitempty"`

		CountryIso2 string `json:"country_iso2,omitempty"`

		Email string `json:"email,omitempty"`

		FirstName string `json:"first_name,omitempty"`

		LastName string `json:"last_name,omitempty"`

		Phone string `json:"phone,omitempty"`

		State string `json:"state,omitempty"`

		Street1 string `json:"street_1,omitempty"`

		Street2 string `json:"street_2,omitempty"`

		Zip string `json:"zip,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	o.City = dataAO1.City

	o.Company = dataAO1.Company

	o.Country = dataAO1.Country

	o.CountryIso2 = dataAO1.CountryIso2

	o.Email = dataAO1.Email

	o.FirstName = dataAO1.FirstName

	o.LastName = dataAO1.LastName

	o.Phone = dataAO1.Phone

	o.State = dataAO1.State

	o.Street1 = dataAO1.Street1

	o.Street2 = dataAO1.Street2

	o.Zip = dataAO1.Zip

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetAllShippingAddressesOKBodyItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		BaseCost string `json:"base_cost,omitempty"`

		BaseHandlingCost string `json:"base_handling_cost,omitempty"`

		CostExTax string `json:"cost_ex_tax,omitempty"`

		CostIncTax string `json:"cost_inc_tax,omitempty"`

		CostTax string `json:"cost_tax,omitempty"`

		CostTaxClassID int64 `json:"cost_tax_class_id,omitempty"`

		FormFields []*GetAllShippingAddressesOKBodyItems0FormFieldsItems0 `json:"form_fields"`

		HandlingCostExTax string `json:"handling_cost_ex_tax,omitempty"`

		HandlingCostIncTax string `json:"handling_cost_inc_tax,omitempty"`

		HandlingCostTax string `json:"handling_cost_tax,omitempty"`

		HandlingCostTaxClassID int64 `json:"handling_cost_tax_class_id,omitempty"`

		ID int64 `json:"id,omitempty"`

		ItemsShipped float64 `json:"items_shipped,omitempty"`

		ItemsTotal float64 `json:"items_total,omitempty"`

		OrderID int64 `json:"order_id,omitempty"`

		ShippingMethod string `json:"shipping_method,omitempty"`

		ShippingQuotes *GetAllShippingAddressesOKBodyItems0AO0ShippingQuotes `json:"shipping_quotes,omitempty"`

		ShippingZoneID float64 `json:"shipping_zone_id,omitempty"`

		ShippingZoneName string `json:"shipping_zone_name,omitempty"`
	}

	dataAO0.BaseCost = o.BaseCost

	dataAO0.BaseHandlingCost = o.BaseHandlingCost

	dataAO0.CostExTax = o.CostExTax

	dataAO0.CostIncTax = o.CostIncTax

	dataAO0.CostTax = o.CostTax

	dataAO0.CostTaxClassID = o.CostTaxClassID

	dataAO0.FormFields = o.FormFields

	dataAO0.HandlingCostExTax = o.HandlingCostExTax

	dataAO0.HandlingCostIncTax = o.HandlingCostIncTax

	dataAO0.HandlingCostTax = o.HandlingCostTax

	dataAO0.HandlingCostTaxClassID = o.HandlingCostTaxClassID

	dataAO0.ID = o.ID

	dataAO0.ItemsShipped = o.ItemsShipped

	dataAO0.ItemsTotal = o.ItemsTotal

	dataAO0.OrderID = o.OrderID

	dataAO0.ShippingMethod = o.ShippingMethod

	dataAO0.ShippingQuotes = o.ShippingQuotes

	dataAO0.ShippingZoneID = o.ShippingZoneID

	dataAO0.ShippingZoneName = o.ShippingZoneName

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		City string `json:"city,omitempty"`

		Company string `json:"company,omitempty"`

		Country string `json:"country,omitempty"`

		CountryIso2 string `json:"country_iso2,omitempty"`

		Email string `json:"email,omitempty"`

		FirstName string `json:"first_name,omitempty"`

		LastName string `json:"last_name,omitempty"`

		Phone string `json:"phone,omitempty"`

		State string `json:"state,omitempty"`

		Street1 string `json:"street_1,omitempty"`

		Street2 string `json:"street_2,omitempty"`

		Zip string `json:"zip,omitempty"`
	}

	dataAO1.City = o.City

	dataAO1.Company = o.Company

	dataAO1.Country = o.Country

	dataAO1.CountryIso2 = o.CountryIso2

	dataAO1.Email = o.Email

	dataAO1.FirstName = o.FirstName

	dataAO1.LastName = o.LastName

	dataAO1.Phone = o.Phone

	dataAO1.State = o.State

	dataAO1.Street1 = o.Street1

	dataAO1.Street2 = o.Street2

	dataAO1.Zip = o.Zip

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get all shipping addresses o k body items0
func (o *GetAllShippingAddressesOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateFormFields(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateShippingQuotes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAllShippingAddressesOKBodyItems0) validateFormFields(formats strfmt.Registry) error {

	if swag.IsZero(o.FormFields) { // not required
		return nil
	}

	for i := 0; i < len(o.FormFields); i++ {
		if swag.IsZero(o.FormFields[i]) { // not required
			continue
		}

		if o.FormFields[i] != nil {
			if err := o.FormFields[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("form_fields" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetAllShippingAddressesOKBodyItems0) validateShippingQuotes(formats strfmt.Registry) error {

	if swag.IsZero(o.ShippingQuotes) { // not required
		return nil
	}

	if o.ShippingQuotes != nil {
		if err := o.ShippingQuotes.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("shipping_quotes")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAllShippingAddressesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAllShippingAddressesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetAllShippingAddressesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAllShippingAddressesOKBodyItems0AO0ShippingQuotes shippingQuotes_Resource
swagger:model GetAllShippingAddressesOKBodyItems0AO0ShippingQuotes
*/
type GetAllShippingAddressesOKBodyItems0AO0ShippingQuotes struct {

	// This URL will return a 204 for shipping quotes. To return shipping quotes:
	// `/shipping_addresses/shipping_address_id/shipping_quotes`
	// Read Only: true
	Resource string `json:"resource,omitempty"`

	// This URL will return a 204 for shipping quotes. To return shipping quotes:
	// `/shipping_addresses/shipping_address_id/shipping_quotes`
	// Read Only: true
	URL string `json:"url,omitempty"`
}

// Validate validates this get all shipping addresses o k body items0 a o0 shipping quotes
func (o *GetAllShippingAddressesOKBodyItems0AO0ShippingQuotes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAllShippingAddressesOKBodyItems0AO0ShippingQuotes) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAllShippingAddressesOKBodyItems0AO0ShippingQuotes) UnmarshalBinary(b []byte) error {
	var res GetAllShippingAddressesOKBodyItems0AO0ShippingQuotes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetAllShippingAddressesOKBodyItems0FormFieldsItems0 formFields
//
// Read-Only. If you have required address form fields they will need to be set as optional before creating an order via API.
swagger:model GetAllShippingAddressesOKBodyItems0FormFieldsItems0
*/
type GetAllShippingAddressesOKBodyItems0FormFieldsItems0 struct {

	// Read-Only. If you have required address form fields they will need to be set as optional before creating an order via API.
	// Read Only: true
	Name string `json:"name,omitempty"`

	// Read-Only. If you have required address form fields they will need to be set as optional before creating an order via API.
	// Read Only: true
	Value string `json:"value,omitempty"`
}

// Validate validates this get all shipping addresses o k body items0 form fields items0
func (o *GetAllShippingAddressesOKBodyItems0FormFieldsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAllShippingAddressesOKBodyItems0FormFieldsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAllShippingAddressesOKBodyItems0FormFieldsItems0) UnmarshalBinary(b []byte) error {
	var res GetAllShippingAddressesOKBodyItems0FormFieldsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
