// Code generated by go-swagger; DO NOT EDIT.

package channel_site

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteChannelsChannelIDSiteParams creates a new DeleteChannelsChannelIDSiteParams object
// with the default values initialized.
func NewDeleteChannelsChannelIDSiteParams() *DeleteChannelsChannelIDSiteParams {
	var ()
	return &DeleteChannelsChannelIDSiteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteChannelsChannelIDSiteParamsWithTimeout creates a new DeleteChannelsChannelIDSiteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteChannelsChannelIDSiteParamsWithTimeout(timeout time.Duration) *DeleteChannelsChannelIDSiteParams {
	var ()
	return &DeleteChannelsChannelIDSiteParams{

		timeout: timeout,
	}
}

// NewDeleteChannelsChannelIDSiteParamsWithContext creates a new DeleteChannelsChannelIDSiteParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteChannelsChannelIDSiteParamsWithContext(ctx context.Context) *DeleteChannelsChannelIDSiteParams {
	var ()
	return &DeleteChannelsChannelIDSiteParams{

		Context: ctx,
	}
}

// NewDeleteChannelsChannelIDSiteParamsWithHTTPClient creates a new DeleteChannelsChannelIDSiteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteChannelsChannelIDSiteParamsWithHTTPClient(client *http.Client) *DeleteChannelsChannelIDSiteParams {
	var ()
	return &DeleteChannelsChannelIDSiteParams{
		HTTPClient: client,
	}
}

/*DeleteChannelsChannelIDSiteParams contains all the parameters to send to the API endpoint
for the delete channels channel ID site operation typically these are written to a http.Request
*/
type DeleteChannelsChannelIDSiteParams struct {

	/*ChannelID*/
	ChannelID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete channels channel ID site params
func (o *DeleteChannelsChannelIDSiteParams) WithTimeout(timeout time.Duration) *DeleteChannelsChannelIDSiteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete channels channel ID site params
func (o *DeleteChannelsChannelIDSiteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete channels channel ID site params
func (o *DeleteChannelsChannelIDSiteParams) WithContext(ctx context.Context) *DeleteChannelsChannelIDSiteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete channels channel ID site params
func (o *DeleteChannelsChannelIDSiteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete channels channel ID site params
func (o *DeleteChannelsChannelIDSiteParams) WithHTTPClient(client *http.Client) *DeleteChannelsChannelIDSiteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete channels channel ID site params
func (o *DeleteChannelsChannelIDSiteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelID adds the channelID to the delete channels channel ID site params
func (o *DeleteChannelsChannelIDSiteParams) WithChannelID(channelID string) *DeleteChannelsChannelIDSiteParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the delete channels channel ID site params
func (o *DeleteChannelsChannelIDSiteParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteChannelsChannelIDSiteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channel_id
	if err := r.SetPathParam("channel_id", o.ChannelID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
