// Code generated by go-swagger; DO NOT EDIT.

package channel_site

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutChannelSiteParams creates a new PutChannelSiteParams object
// with the default values initialized.
func NewPutChannelSiteParams() *PutChannelSiteParams {
	var ()
	return &PutChannelSiteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutChannelSiteParamsWithTimeout creates a new PutChannelSiteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutChannelSiteParamsWithTimeout(timeout time.Duration) *PutChannelSiteParams {
	var ()
	return &PutChannelSiteParams{

		timeout: timeout,
	}
}

// NewPutChannelSiteParamsWithContext creates a new PutChannelSiteParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutChannelSiteParamsWithContext(ctx context.Context) *PutChannelSiteParams {
	var ()
	return &PutChannelSiteParams{

		Context: ctx,
	}
}

// NewPutChannelSiteParamsWithHTTPClient creates a new PutChannelSiteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutChannelSiteParamsWithHTTPClient(client *http.Client) *PutChannelSiteParams {
	var ()
	return &PutChannelSiteParams{
		HTTPClient: client,
	}
}

/*PutChannelSiteParams contains all the parameters to send to the API endpoint
for the put channel site operation typically these are written to a http.Request
*/
type PutChannelSiteParams struct {

	/*Body*/
	Body PutChannelSiteBody
	/*ChannelID*/
	ChannelID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put channel site params
func (o *PutChannelSiteParams) WithTimeout(timeout time.Duration) *PutChannelSiteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put channel site params
func (o *PutChannelSiteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put channel site params
func (o *PutChannelSiteParams) WithContext(ctx context.Context) *PutChannelSiteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put channel site params
func (o *PutChannelSiteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put channel site params
func (o *PutChannelSiteParams) WithHTTPClient(client *http.Client) *PutChannelSiteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put channel site params
func (o *PutChannelSiteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put channel site params
func (o *PutChannelSiteParams) WithBody(body PutChannelSiteBody) *PutChannelSiteParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put channel site params
func (o *PutChannelSiteParams) SetBody(body PutChannelSiteBody) {
	o.Body = body
}

// WithChannelID adds the channelID to the put channel site params
func (o *PutChannelSiteParams) WithChannelID(channelID string) *PutChannelSiteParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the put channel site params
func (o *PutChannelSiteParams) SetChannelID(channelID string) {
	o.ChannelID = channelID
}

// WriteToRequest writes these params to a swagger request
func (o *PutChannelSiteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param channel_id
	if err := r.SetPathParam("channel_id", o.ChannelID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
