// Code generated by go-swagger; DO NOT EDIT.

package theme_actions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new theme actions API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for theme actions API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ActivateStoreTheme(params *ActivateStoreThemeParams, authInfo runtime.ClientAuthInfoWriter) (*ActivateStoreThemeNoContent, error)

	DownloadTheme(params *DownloadThemeParams, authInfo runtime.ClientAuthInfoWriter) (*DownloadThemeOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ActivateStoreTheme activates a theme

  Actives a store *Theme*.

This returns a 204 response upon success.
*/
func (a *Client) ActivateStoreTheme(params *ActivateStoreThemeParams, authInfo runtime.ClientAuthInfoWriter) (*ActivateStoreThemeNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewActivateStoreThemeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "activateStoreTheme",
		Method:             "POST",
		PathPattern:        "/themes/actions/activate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ActivateStoreThemeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ActivateStoreThemeNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ActivateStoreThemeDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  DownloadTheme downloads a theme

  Downloads a stores *Theme*.
*/
func (a *Client) DownloadTheme(params *DownloadThemeParams, authInfo runtime.ClientAuthInfoWriter) (*DownloadThemeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDownloadThemeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "downloadTheme",
		Method:             "POST",
		PathPattern:        "/themes/{uuid}/actions/download",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DownloadThemeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DownloadThemeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DownloadThemeDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
