// Code generated by go-swagger; DO NOT EDIT.

package price_lists_records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeletePriceListRecordReader is a Reader for the DeletePriceListRecord structure.
type DeletePriceListRecordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePriceListRecordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeletePriceListRecordNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeletePriceListRecordNoContent creates a DeletePriceListRecordNoContent with default headers values
func NewDeletePriceListRecordNoContent() *DeletePriceListRecordNoContent {
	return &DeletePriceListRecordNoContent{}
}

/*DeletePriceListRecordNoContent handles this case with default header values.

DeletePriceListRecordNoContent delete price list record no content
*/
type DeletePriceListRecordNoContent struct {
}

func (o *DeletePriceListRecordNoContent) Error() string {
	return fmt.Sprintf("[DELETE /pricelists/{price_list_id}/records/{variant_id}/{currency_code}][%d] deletePriceListRecordNoContent ", 204)
}

func (o *DeletePriceListRecordNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
