// Code generated by go-swagger; DO NOT EDIT.

package price_lists_records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetPriceListRecordCollectionParams creates a new GetPriceListRecordCollectionParams object
// with the default values initialized.
func NewGetPriceListRecordCollectionParams() *GetPriceListRecordCollectionParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &GetPriceListRecordCollectionParams{
		Accept:      &acceptDefault,
		ContentType: &contentTypeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPriceListRecordCollectionParamsWithTimeout creates a new GetPriceListRecordCollectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPriceListRecordCollectionParamsWithTimeout(timeout time.Duration) *GetPriceListRecordCollectionParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &GetPriceListRecordCollectionParams{
		Accept:      &acceptDefault,
		ContentType: &contentTypeDefault,

		timeout: timeout,
	}
}

// NewGetPriceListRecordCollectionParamsWithContext creates a new GetPriceListRecordCollectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPriceListRecordCollectionParamsWithContext(ctx context.Context) *GetPriceListRecordCollectionParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &GetPriceListRecordCollectionParams{
		Accept:      &acceptDefault,
		ContentType: &contentTypeDefault,

		Context: ctx,
	}
}

// NewGetPriceListRecordCollectionParamsWithHTTPClient creates a new GetPriceListRecordCollectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPriceListRecordCollectionParamsWithHTTPClient(client *http.Client) *GetPriceListRecordCollectionParams {
	var (
		acceptDefault      = string("application/json")
		contentTypeDefault = string("application/json")
	)
	return &GetPriceListRecordCollectionParams{
		Accept:      &acceptDefault,
		ContentType: &contentTypeDefault,
		HTTPClient:  client,
	}
}

/*GetPriceListRecordCollectionParams contains all the parameters to send to the API endpoint
for the get price list record collection operation typically these are written to a http.Request
*/
type GetPriceListRecordCollectionParams struct {

	/*Accept*/
	Accept *string
	/*ContentType*/
	ContentType *string
	/*CalculatedPrice
	  Filter items by calculated_price.


	*/
	CalculatedPrice *float64
	/*Currency
	  Filter items by currency.


	*/
	Currency *string
	/*DateCreated
	  Filter items by date_created.


	*/
	DateCreated *strfmt.DateTime
	/*DateModified
	  Filter items by date_modified. For example `v3/catalog/products?date_last_imported:min=2018-06-15`

	*/
	DateModified *strfmt.DateTime
	/*Include
	  Sub-resources to include on a price record, in a comma-separated list. Valid expansions currently include `bulk_pricing_tiers` and `sku`.  Other valies will be ignored.


	*/
	Include *string
	/*Limit
	  Controls the number of items per page in a limited (paginated) list of products.

	*/
	Limit *int64
	/*MapPrice
	  Filter items by map_price.


	*/
	MapPrice *float64
	/*Page
	  Specifies the page number in a limited (paginated) list of products.

	*/
	Page *int64
	/*Price
	  Filter items by price.


	*/
	Price *float64
	/*PriceListID
	  The ID of the `Price List` requested.


	*/
	PriceListID int64
	/*ProductIDIn
	  A comma-separated list of ids of `Product`s whose prices were requested.


	*/
	ProductIDIn *string
	/*RetailPrice
	  Filter items by retail_price.


	*/
	RetailPrice *float64
	/*SalePrice
	  Filter items by sale_price.


	*/
	SalePrice *float64
	/*Sku
	  Filter items by sku.


	*/
	Sku *string
	/*VariantIDIn
	  The ID of the `Variant` whose prices were requested.

	*/
	VariantIDIn *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithTimeout(timeout time.Duration) *GetPriceListRecordCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithContext(ctx context.Context) *GetPriceListRecordCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithHTTPClient(client *http.Client) *GetPriceListRecordCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccept adds the accept to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithAccept(accept *string) *GetPriceListRecordCollectionParams {
	o.SetAccept(accept)
	return o
}

// SetAccept adds the accept to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetAccept(accept *string) {
	o.Accept = accept
}

// WithContentType adds the contentType to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithContentType(contentType *string) *GetPriceListRecordCollectionParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetContentType(contentType *string) {
	o.ContentType = contentType
}

// WithCalculatedPrice adds the calculatedPrice to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithCalculatedPrice(calculatedPrice *float64) *GetPriceListRecordCollectionParams {
	o.SetCalculatedPrice(calculatedPrice)
	return o
}

// SetCalculatedPrice adds the calculatedPrice to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetCalculatedPrice(calculatedPrice *float64) {
	o.CalculatedPrice = calculatedPrice
}

// WithCurrency adds the currency to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithCurrency(currency *string) *GetPriceListRecordCollectionParams {
	o.SetCurrency(currency)
	return o
}

// SetCurrency adds the currency to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetCurrency(currency *string) {
	o.Currency = currency
}

// WithDateCreated adds the dateCreated to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithDateCreated(dateCreated *strfmt.DateTime) *GetPriceListRecordCollectionParams {
	o.SetDateCreated(dateCreated)
	return o
}

// SetDateCreated adds the dateCreated to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetDateCreated(dateCreated *strfmt.DateTime) {
	o.DateCreated = dateCreated
}

// WithDateModified adds the dateModified to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithDateModified(dateModified *strfmt.DateTime) *GetPriceListRecordCollectionParams {
	o.SetDateModified(dateModified)
	return o
}

// SetDateModified adds the dateModified to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetDateModified(dateModified *strfmt.DateTime) {
	o.DateModified = dateModified
}

// WithInclude adds the include to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithInclude(include *string) *GetPriceListRecordCollectionParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetInclude(include *string) {
	o.Include = include
}

// WithLimit adds the limit to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithLimit(limit *int64) *GetPriceListRecordCollectionParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithMapPrice adds the mapPrice to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithMapPrice(mapPrice *float64) *GetPriceListRecordCollectionParams {
	o.SetMapPrice(mapPrice)
	return o
}

// SetMapPrice adds the mapPrice to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetMapPrice(mapPrice *float64) {
	o.MapPrice = mapPrice
}

// WithPage adds the page to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithPage(page *int64) *GetPriceListRecordCollectionParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetPage(page *int64) {
	o.Page = page
}

// WithPrice adds the price to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithPrice(price *float64) *GetPriceListRecordCollectionParams {
	o.SetPrice(price)
	return o
}

// SetPrice adds the price to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetPrice(price *float64) {
	o.Price = price
}

// WithPriceListID adds the priceListID to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithPriceListID(priceListID int64) *GetPriceListRecordCollectionParams {
	o.SetPriceListID(priceListID)
	return o
}

// SetPriceListID adds the priceListId to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetPriceListID(priceListID int64) {
	o.PriceListID = priceListID
}

// WithProductIDIn adds the productIDIn to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithProductIDIn(productIDIn *string) *GetPriceListRecordCollectionParams {
	o.SetProductIDIn(productIDIn)
	return o
}

// SetProductIDIn adds the productIdIn to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetProductIDIn(productIDIn *string) {
	o.ProductIDIn = productIDIn
}

// WithRetailPrice adds the retailPrice to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithRetailPrice(retailPrice *float64) *GetPriceListRecordCollectionParams {
	o.SetRetailPrice(retailPrice)
	return o
}

// SetRetailPrice adds the retailPrice to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetRetailPrice(retailPrice *float64) {
	o.RetailPrice = retailPrice
}

// WithSalePrice adds the salePrice to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithSalePrice(salePrice *float64) *GetPriceListRecordCollectionParams {
	o.SetSalePrice(salePrice)
	return o
}

// SetSalePrice adds the salePrice to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetSalePrice(salePrice *float64) {
	o.SalePrice = salePrice
}

// WithSku adds the sku to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithSku(sku *string) *GetPriceListRecordCollectionParams {
	o.SetSku(sku)
	return o
}

// SetSku adds the sku to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetSku(sku *string) {
	o.Sku = sku
}

// WithVariantIDIn adds the variantIDIn to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) WithVariantIDIn(variantIDIn *int64) *GetPriceListRecordCollectionParams {
	o.SetVariantIDIn(variantIDIn)
	return o
}

// SetVariantIDIn adds the variantIdIn to the get price list record collection params
func (o *GetPriceListRecordCollectionParams) SetVariantIDIn(variantIDIn *int64) {
	o.VariantIDIn = variantIDIn
}

// WriteToRequest writes these params to a swagger request
func (o *GetPriceListRecordCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Accept != nil {

		// header param Accept
		if err := r.SetHeaderParam("Accept", *o.Accept); err != nil {
			return err
		}

	}

	if o.ContentType != nil {

		// header param Content-Type
		if err := r.SetHeaderParam("Content-Type", *o.ContentType); err != nil {
			return err
		}

	}

	if o.CalculatedPrice != nil {

		// query param calculated_price
		var qrCalculatedPrice float64
		if o.CalculatedPrice != nil {
			qrCalculatedPrice = *o.CalculatedPrice
		}
		qCalculatedPrice := swag.FormatFloat64(qrCalculatedPrice)
		if qCalculatedPrice != "" {
			if err := r.SetQueryParam("calculated_price", qCalculatedPrice); err != nil {
				return err
			}
		}

	}

	if o.Currency != nil {

		// query param currency
		var qrCurrency string
		if o.Currency != nil {
			qrCurrency = *o.Currency
		}
		qCurrency := qrCurrency
		if qCurrency != "" {
			if err := r.SetQueryParam("currency", qCurrency); err != nil {
				return err
			}
		}

	}

	if o.DateCreated != nil {

		// query param date_created
		var qrDateCreated strfmt.DateTime
		if o.DateCreated != nil {
			qrDateCreated = *o.DateCreated
		}
		qDateCreated := qrDateCreated.String()
		if qDateCreated != "" {
			if err := r.SetQueryParam("date_created", qDateCreated); err != nil {
				return err
			}
		}

	}

	if o.DateModified != nil {

		// query param date_modified
		var qrDateModified strfmt.DateTime
		if o.DateModified != nil {
			qrDateModified = *o.DateModified
		}
		qDateModified := qrDateModified.String()
		if qDateModified != "" {
			if err := r.SetQueryParam("date_modified", qDateModified); err != nil {
				return err
			}
		}

	}

	if o.Include != nil {

		// query param include
		var qrInclude string
		if o.Include != nil {
			qrInclude = *o.Include
		}
		qInclude := qrInclude
		if qInclude != "" {
			if err := r.SetQueryParam("include", qInclude); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.MapPrice != nil {

		// query param map_price
		var qrMapPrice float64
		if o.MapPrice != nil {
			qrMapPrice = *o.MapPrice
		}
		qMapPrice := swag.FormatFloat64(qrMapPrice)
		if qMapPrice != "" {
			if err := r.SetQueryParam("map_price", qMapPrice); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.Price != nil {

		// query param price
		var qrPrice float64
		if o.Price != nil {
			qrPrice = *o.Price
		}
		qPrice := swag.FormatFloat64(qrPrice)
		if qPrice != "" {
			if err := r.SetQueryParam("price", qPrice); err != nil {
				return err
			}
		}

	}

	// path param price_list_id
	if err := r.SetPathParam("price_list_id", swag.FormatInt64(o.PriceListID)); err != nil {
		return err
	}

	if o.ProductIDIn != nil {

		// query param product_id:in
		var qrProductIDIn string
		if o.ProductIDIn != nil {
			qrProductIDIn = *o.ProductIDIn
		}
		qProductIDIn := qrProductIDIn
		if qProductIDIn != "" {
			if err := r.SetQueryParam("product_id:in", qProductIDIn); err != nil {
				return err
			}
		}

	}

	if o.RetailPrice != nil {

		// query param retail_price
		var qrRetailPrice float64
		if o.RetailPrice != nil {
			qrRetailPrice = *o.RetailPrice
		}
		qRetailPrice := swag.FormatFloat64(qrRetailPrice)
		if qRetailPrice != "" {
			if err := r.SetQueryParam("retail_price", qRetailPrice); err != nil {
				return err
			}
		}

	}

	if o.SalePrice != nil {

		// query param sale_price
		var qrSalePrice float64
		if o.SalePrice != nil {
			qrSalePrice = *o.SalePrice
		}
		qSalePrice := swag.FormatFloat64(qrSalePrice)
		if qSalePrice != "" {
			if err := r.SetQueryParam("sale_price", qSalePrice); err != nil {
				return err
			}
		}

	}

	if o.Sku != nil {

		// query param sku
		var qrSku string
		if o.Sku != nil {
			qrSku = *o.Sku
		}
		qSku := qrSku
		if qSku != "" {
			if err := r.SetQueryParam("sku", qSku); err != nil {
				return err
			}
		}

	}

	if o.VariantIDIn != nil {

		// query param variant_id:in
		var qrVariantIDIn int64
		if o.VariantIDIn != nil {
			qrVariantIDIn = *o.VariantIDIn
		}
		qVariantIDIn := swag.FormatInt64(qrVariantIDIn)
		if qVariantIDIn != "" {
			if err := r.SetQueryParam("variant_id:in", qVariantIDIn); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
