// Code generated by go-swagger; DO NOT EDIT.

package price_lists_records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SetPriceListRecordReader is a Reader for the SetPriceListRecord structure.
type SetPriceListRecordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetPriceListRecordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetPriceListRecordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewSetPriceListRecordNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewSetPriceListRecordConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewSetPriceListRecordUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSetPriceListRecordOK creates a SetPriceListRecordOK with default headers values
func NewSetPriceListRecordOK() *SetPriceListRecordOK {
	return &SetPriceListRecordOK{}
}

/*SetPriceListRecordOK handles this case with default header values.

SetPriceListRecordOK set price list record o k
*/
type SetPriceListRecordOK struct {
	Payload *SetPriceListRecordOKBody
}

func (o *SetPriceListRecordOK) Error() string {
	return fmt.Sprintf("[PUT /pricelists/{price_list_id}/records/{variant_id}/{currency_code}][%d] setPriceListRecordOK  %+v", 200, o.Payload)
}

func (o *SetPriceListRecordOK) GetPayload() *SetPriceListRecordOKBody {
	return o.Payload
}

func (o *SetPriceListRecordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetPriceListRecordOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetPriceListRecordNotFound creates a SetPriceListRecordNotFound with default headers values
func NewSetPriceListRecordNotFound() *SetPriceListRecordNotFound {
	return &SetPriceListRecordNotFound{}
}

/*SetPriceListRecordNotFound handles this case with default header values.

The resource was not found.

*/
type SetPriceListRecordNotFound struct {
	Payload *SetPriceListRecordNotFoundBody
}

func (o *SetPriceListRecordNotFound) Error() string {
	return fmt.Sprintf("[PUT /pricelists/{price_list_id}/records/{variant_id}/{currency_code}][%d] setPriceListRecordNotFound  %+v", 404, o.Payload)
}

func (o *SetPriceListRecordNotFound) GetPayload() *SetPriceListRecordNotFoundBody {
	return o.Payload
}

func (o *SetPriceListRecordNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetPriceListRecordNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetPriceListRecordConflict creates a SetPriceListRecordConflict with default headers values
func NewSetPriceListRecordConflict() *SetPriceListRecordConflict {
	return &SetPriceListRecordConflict{}
}

/*SetPriceListRecordConflict handles this case with default header values.

`Price Record` was in conflict with another price record. This is the result of duplicate unique values.

*/
type SetPriceListRecordConflict struct {
	Payload *SetPriceListRecordConflictBody
}

func (o *SetPriceListRecordConflict) Error() string {
	return fmt.Sprintf("[PUT /pricelists/{price_list_id}/records/{variant_id}/{currency_code}][%d] setPriceListRecordConflict  %+v", 409, o.Payload)
}

func (o *SetPriceListRecordConflict) GetPayload() *SetPriceListRecordConflictBody {
	return o.Payload
}

func (o *SetPriceListRecordConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetPriceListRecordConflictBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetPriceListRecordUnprocessableEntity creates a SetPriceListRecordUnprocessableEntity with default headers values
func NewSetPriceListRecordUnprocessableEntity() *SetPriceListRecordUnprocessableEntity {
	return &SetPriceListRecordUnprocessableEntity{}
}

/*SetPriceListRecordUnprocessableEntity handles this case with default header values.

`Price Record` was not valid. This is the result of missing required fields, or of invalid data. See the response for more details.

*/
type SetPriceListRecordUnprocessableEntity struct {
	Payload *SetPriceListRecordUnprocessableEntityBody
}

func (o *SetPriceListRecordUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /pricelists/{price_list_id}/records/{variant_id}/{currency_code}][%d] setPriceListRecordUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *SetPriceListRecordUnprocessableEntity) GetPayload() *SetPriceListRecordUnprocessableEntityBody {
	return o.Payload
}

func (o *SetPriceListRecordUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetPriceListRecordUnprocessableEntityBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SetPriceListRecordBody Price Record Put
swagger:model SetPriceListRecordBody
*/
type SetPriceListRecordBody struct {

	// bulk pricing tiers
	BulkPricingTiers []*SetPriceListRecordParamsBodyBulkPricingTiersItems0 `json:"bulk_pricing_tiers"`

	// The MAP (Manufacturer's Advertised Price) for the variant mapped in a Price List. Overrides any existing or Catalog MAP price for the variant/product. If empty, the MAP price will be treated as not being set on this variant.
	//
	MapPrice float64 `json:"map_price,omitempty"`

	// The list price for the variant mapped in a Price List. Overrides any existing or Catalog list price for the variant/product.
	//
	Price float64 `json:"price,omitempty"`

	// The retail price for the variant mapped in a Price List. Overrides any existing or Catalog retail price for the variant/product.  If empty, the retail price will be treated as not being set on this variant.
	//
	RetailPrice float64 `json:"retail_price,omitempty"`

	// The sale price for the variant mapped in a Price List. Overrides any existing or Catalog sale price for the variant/product. If empty, the sale price will be treated as not being set on this variant.
	//
	SalePrice float64 `json:"sale_price,omitempty"`

	// The SKU code associated with this `Price Record` if requested and it exists.
	//
	Sku string `json:"sku,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *SetPriceListRecordBody) UnmarshalJSON(raw []byte) error {
	// SetPriceListRecordParamsBodyAO0
	var dataSetPriceListRecordParamsBodyAO0 struct {
		BulkPricingTiers []*SetPriceListRecordParamsBodyBulkPricingTiersItems0 `json:"bulk_pricing_tiers"`

		MapPrice float64 `json:"map_price,omitempty"`

		Price float64 `json:"price,omitempty"`

		RetailPrice float64 `json:"retail_price,omitempty"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataSetPriceListRecordParamsBodyAO0); err != nil {
		return err
	}

	o.BulkPricingTiers = dataSetPriceListRecordParamsBodyAO0.BulkPricingTiers

	o.MapPrice = dataSetPriceListRecordParamsBodyAO0.MapPrice

	o.Price = dataSetPriceListRecordParamsBodyAO0.Price

	o.RetailPrice = dataSetPriceListRecordParamsBodyAO0.RetailPrice

	o.SalePrice = dataSetPriceListRecordParamsBodyAO0.SalePrice

	o.Sku = dataSetPriceListRecordParamsBodyAO0.Sku

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o SetPriceListRecordBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataSetPriceListRecordParamsBodyAO0 struct {
		BulkPricingTiers []*SetPriceListRecordParamsBodyBulkPricingTiersItems0 `json:"bulk_pricing_tiers"`

		MapPrice float64 `json:"map_price,omitempty"`

		Price float64 `json:"price,omitempty"`

		RetailPrice float64 `json:"retail_price,omitempty"`

		SalePrice float64 `json:"sale_price,omitempty"`

		Sku string `json:"sku,omitempty"`
	}

	dataSetPriceListRecordParamsBodyAO0.BulkPricingTiers = o.BulkPricingTiers

	dataSetPriceListRecordParamsBodyAO0.MapPrice = o.MapPrice

	dataSetPriceListRecordParamsBodyAO0.Price = o.Price

	dataSetPriceListRecordParamsBodyAO0.RetailPrice = o.RetailPrice

	dataSetPriceListRecordParamsBodyAO0.SalePrice = o.SalePrice

	dataSetPriceListRecordParamsBodyAO0.Sku = o.Sku

	jsonDataSetPriceListRecordParamsBodyAO0, errSetPriceListRecordParamsBodyAO0 := swag.WriteJSON(dataSetPriceListRecordParamsBodyAO0)
	if errSetPriceListRecordParamsBodyAO0 != nil {
		return nil, errSetPriceListRecordParamsBodyAO0
	}
	_parts = append(_parts, jsonDataSetPriceListRecordParamsBodyAO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this set price list record body
func (o *SetPriceListRecordBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBulkPricingTiers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetPriceListRecordBody) validateBulkPricingTiers(formats strfmt.Registry) error {

	if swag.IsZero(o.BulkPricingTiers) { // not required
		return nil
	}

	for i := 0; i < len(o.BulkPricingTiers); i++ {
		if swag.IsZero(o.BulkPricingTiers[i]) { // not required
			continue
		}

		if o.BulkPricingTiers[i] != nil {
			if err := o.BulkPricingTiers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("PriceRecord" + "." + "bulk_pricing_tiers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *SetPriceListRecordBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetPriceListRecordBody) UnmarshalBinary(b []byte) error {
	var res SetPriceListRecordBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SetPriceListRecordConflictBody Error Response
swagger:model SetPriceListRecordConflictBody
*/
type SetPriceListRecordConflictBody struct {

	// instance
	Instance string `json:"instance,omitempty"`

	// The HTTP status code.
	//
	Status int64 `json:"status,omitempty"`

	// The error title describing the particular error.
	//
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// Detailed Errors
	Errors map[string]string `json:"errors,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *SetPriceListRecordConflictBody) UnmarshalJSON(raw []byte) error {
	// SetPriceListRecordConflictBodyAO0
	var dataSetPriceListRecordConflictBodyAO0 struct {
		Instance string `json:"instance,omitempty"`

		Status int64 `json:"status,omitempty"`

		Title string `json:"title,omitempty"`

		Type string `json:"type,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataSetPriceListRecordConflictBodyAO0); err != nil {
		return err
	}

	o.Instance = dataSetPriceListRecordConflictBodyAO0.Instance

	o.Status = dataSetPriceListRecordConflictBodyAO0.Status

	o.Title = dataSetPriceListRecordConflictBodyAO0.Title

	o.Type = dataSetPriceListRecordConflictBodyAO0.Type

	// SetPriceListRecordConflictBodyAO1
	var dataSetPriceListRecordConflictBodyAO1 struct {
		Errors map[string]string `json:"errors,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataSetPriceListRecordConflictBodyAO1); err != nil {
		return err
	}

	o.Errors = dataSetPriceListRecordConflictBodyAO1.Errors

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o SetPriceListRecordConflictBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataSetPriceListRecordConflictBodyAO0 struct {
		Instance string `json:"instance,omitempty"`

		Status int64 `json:"status,omitempty"`

		Title string `json:"title,omitempty"`

		Type string `json:"type,omitempty"`
	}

	dataSetPriceListRecordConflictBodyAO0.Instance = o.Instance

	dataSetPriceListRecordConflictBodyAO0.Status = o.Status

	dataSetPriceListRecordConflictBodyAO0.Title = o.Title

	dataSetPriceListRecordConflictBodyAO0.Type = o.Type

	jsonDataSetPriceListRecordConflictBodyAO0, errSetPriceListRecordConflictBodyAO0 := swag.WriteJSON(dataSetPriceListRecordConflictBodyAO0)
	if errSetPriceListRecordConflictBodyAO0 != nil {
		return nil, errSetPriceListRecordConflictBodyAO0
	}
	_parts = append(_parts, jsonDataSetPriceListRecordConflictBodyAO0)
	var dataSetPriceListRecordConflictBodyAO1 struct {
		Errors map[string]string `json:"errors,omitempty"`
	}

	dataSetPriceListRecordConflictBodyAO1.Errors = o.Errors

	jsonDataSetPriceListRecordConflictBodyAO1, errSetPriceListRecordConflictBodyAO1 := swag.WriteJSON(dataSetPriceListRecordConflictBodyAO1)
	if errSetPriceListRecordConflictBodyAO1 != nil {
		return nil, errSetPriceListRecordConflictBodyAO1
	}
	_parts = append(_parts, jsonDataSetPriceListRecordConflictBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this set price list record conflict body
func (o *SetPriceListRecordConflictBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *SetPriceListRecordConflictBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetPriceListRecordConflictBody) UnmarshalBinary(b []byte) error {
	var res SetPriceListRecordConflictBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SetPriceListRecordNotFoundBody Not Found
//
// Error payload for the BigCommerce API.
swagger:model SetPriceListRecordNotFoundBody
*/
type SetPriceListRecordNotFoundBody struct {

	// instance
	Instance string `json:"instance,omitempty"`

	// 404 HTTP status code.
	//
	Status int64 `json:"status,omitempty"`

	// The error title describing the particular error.
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this set price list record not found body
func (o *SetPriceListRecordNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetPriceListRecordNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetPriceListRecordNotFoundBody) UnmarshalBinary(b []byte) error {
	var res SetPriceListRecordNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SetPriceListRecordOKBody Price Record Response
//
// Response payload for the BigCommerce API.
swagger:model SetPriceListRecordOKBody
*/
type SetPriceListRecordOKBody struct {

	// Price Record
	//
	// The Price Record object.
	Data struct {

		// The price of the variant as seen on the storefront if a price record is in effect. It will be equal to the `sale_price`, if set, and the `price` if there is not a `sale_price`.  Read only.
		//
		CalculatedPrice float64 `json:"calculated_price,omitempty"`

		// The date on which the Price entry was created.
		//
		// Format: date-time
		DateCreated strfmt.DateTime `json:"date_created,omitempty"`

		// The date on which the Price entry was created.
		//
		// Format: date-time
		DateModified strfmt.DateTime `json:"date_modified,omitempty"`

		// The id of the `Product` this `Price Record`'s variant_id is associated with.  Read only.
		//
		ProductID int64 `json:"product_id,omitempty"`

		SetPriceListRecordOKBodyDataAllOf1

		// bulk pricing tiers
		BulkPricingTiers []*SetPriceListRecordOKBodyBulkPricingTiersItems0 `json:"bulk_pricing_tiers"`

		// The MAP (Manufacturer's Advertised Price) for the variant mapped in a Price List. Overrides any existing or Catalog MAP price for the variant/product. If empty, the MAP price will be treated as not being set on this variant.
		//
		MapPrice float64 `json:"map_price,omitempty"`

		// The list price for the variant mapped in a Price List. Overrides any existing or Catalog list price for the variant/product.
		//
		Price float64 `json:"price,omitempty"`

		// The retail price for the variant mapped in a Price List. Overrides any existing or Catalog retail price for the variant/product.  If empty, the retail price will be treated as not being set on this variant.
		//
		RetailPrice float64 `json:"retail_price,omitempty"`

		// The sale price for the variant mapped in a Price List. Overrides any existing or Catalog sale price for the variant/product. If empty, the sale price will be treated as not being set on this variant.
		//
		SalePrice float64 `json:"sale_price,omitempty"`

		// The SKU code associated with this `Price Record` if requested and it exists.
		//
		Sku string `json:"sku,omitempty"`
	} `json:"data,omitempty"`

	// Meta
	//
	// Empty meta object; may be used later.
	Meta interface{} `json:"meta,omitempty"`
}

// Validate validates this set price list record o k body
func (o *SetPriceListRecordOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetPriceListRecordOKBody) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if err := validate.FormatOf("setPriceListRecordOK"+"."+"data"+"."+"date_created", "body", "date-time", o.Data.DateCreated.String(), formats); err != nil {
		return err
	}

	if err := validate.FormatOf("setPriceListRecordOK"+"."+"data"+"."+"date_modified", "body", "date-time", o.Data.DateModified.String(), formats); err != nil {
		return err
	}

	for i := 0; i < len(o.Data.BulkPricingTiers); i++ {
		if swag.IsZero(o.Data.BulkPricingTiers[i]) { // not required
			continue
		}

		if o.Data.BulkPricingTiers[i] != nil {
			if err := o.Data.BulkPricingTiers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("setPriceListRecordOK" + "." + "data" + "." + "bulk_pricing_tiers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *SetPriceListRecordOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetPriceListRecordOKBody) UnmarshalBinary(b []byte) error {
	var res SetPriceListRecordOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SetPriceListRecordOKBodyBulkPricingTiersItems0 Bulk Pricing Tier
swagger:model SetPriceListRecordOKBodyBulkPricingTiersItems0
*/
type SetPriceListRecordOKBodyBulkPricingTiersItems0 struct {

	// The price adjustment amount. This value along with the type will decide the price per variant for the pricing tier.
	//
	Amount float64 `json:"amount,omitempty"`

	// The maximum allowed quantity of associated variant in the cart to qualify for this tiers pricing.
	//
	QuantityMax int64 `json:"quantity_max,omitempty"`

	// The minimum quantity of associated variant in the cart needed to qualify for this tiers pricing.
	//
	QuantityMin int64 `json:"quantity_min,omitempty"`

	// The type of adjustment that is made. Acceptable values: price – the adjustment amount per product; percent – the adjustment as a percentage of the original price; fixed – the adjusted absolute price of the product.
	//
	// Enum: [fixed price percent]
	Type string `json:"type,omitempty"`
}

// Validate validates this set price list record o k body bulk pricing tiers items0
func (o *SetPriceListRecordOKBodyBulkPricingTiersItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var setPriceListRecordOKBodyBulkPricingTiersItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["fixed","price","percent"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		setPriceListRecordOKBodyBulkPricingTiersItems0TypeTypePropEnum = append(setPriceListRecordOKBodyBulkPricingTiersItems0TypeTypePropEnum, v)
	}
}

const (

	// SetPriceListRecordOKBodyBulkPricingTiersItems0TypeFixed captures enum value "fixed"
	SetPriceListRecordOKBodyBulkPricingTiersItems0TypeFixed string = "fixed"

	// SetPriceListRecordOKBodyBulkPricingTiersItems0TypePrice captures enum value "price"
	SetPriceListRecordOKBodyBulkPricingTiersItems0TypePrice string = "price"

	// SetPriceListRecordOKBodyBulkPricingTiersItems0TypePercent captures enum value "percent"
	SetPriceListRecordOKBodyBulkPricingTiersItems0TypePercent string = "percent"
)

// prop value enum
func (o *SetPriceListRecordOKBodyBulkPricingTiersItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, setPriceListRecordOKBodyBulkPricingTiersItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *SetPriceListRecordOKBodyBulkPricingTiersItems0) validateType(formats strfmt.Registry) error {

	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SetPriceListRecordOKBodyBulkPricingTiersItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetPriceListRecordOKBodyBulkPricingTiersItems0) UnmarshalBinary(b []byte) error {
	var res SetPriceListRecordOKBodyBulkPricingTiersItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SetPriceListRecordOKBodyDataAllOf1 Price Record Identifiers
//
// Price Record object used in batch create or update.
swagger:model SetPriceListRecordOKBodyDataAllOf1
*/
type SetPriceListRecordOKBodyDataAllOf1 struct {

	// The 3-letter currency code with which this price set is associated.
	//
	Currency string `json:"currency,omitempty"`

	// The Price List with which this price set is associated.
	//
	PriceListID int64 `json:"price_list_id,omitempty"`

	// The variant with which this price set is associated. Either sku or variant_id is required.
	//
	Sku string `json:"sku,omitempty"`

	// The variant with which this price set is associated. Either variant_id or sku is required.
	//
	VariantID int64 `json:"variant_id,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *SetPriceListRecordOKBodyDataAllOf1) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		Currency string `json:"currency,omitempty"`

		PriceListID int64 `json:"price_list_id,omitempty"`

		Sku string `json:"sku,omitempty"`

		VariantID int64 `json:"variant_id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	o.Currency = dataAO0.Currency

	o.PriceListID = dataAO0.PriceListID

	o.Sku = dataAO0.Sku

	o.VariantID = dataAO0.VariantID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o SetPriceListRecordOKBodyDataAllOf1) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		Currency string `json:"currency,omitempty"`

		PriceListID int64 `json:"price_list_id,omitempty"`

		Sku string `json:"sku,omitempty"`

		VariantID int64 `json:"variant_id,omitempty"`
	}

	dataAO0.Currency = o.Currency

	dataAO0.PriceListID = o.PriceListID

	dataAO0.Sku = o.Sku

	dataAO0.VariantID = o.VariantID

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this set price list record o k body data all of1
func (o *SetPriceListRecordOKBodyDataAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *SetPriceListRecordOKBodyDataAllOf1) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetPriceListRecordOKBodyDataAllOf1) UnmarshalBinary(b []byte) error {
	var res SetPriceListRecordOKBodyDataAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SetPriceListRecordParamsBodyBulkPricingTiersItems0 Bulk Pricing Tier
swagger:model SetPriceListRecordParamsBodyBulkPricingTiersItems0
*/
type SetPriceListRecordParamsBodyBulkPricingTiersItems0 struct {

	// The price adjustment amount. This value along with the type will decide the price per variant for the pricing tier.
	//
	Amount float64 `json:"amount,omitempty"`

	// The maximum allowed quantity of associated variant in the cart to qualify for this tiers pricing.
	//
	QuantityMax int64 `json:"quantity_max,omitempty"`

	// The minimum quantity of associated variant in the cart needed to qualify for this tiers pricing.
	//
	QuantityMin int64 `json:"quantity_min,omitempty"`

	// The type of adjustment that is made. Acceptable values: price – the adjustment amount per product; percent – the adjustment as a percentage of the original price; fixed – the adjusted absolute price of the product.
	//
	// Enum: [fixed price percent]
	Type string `json:"type,omitempty"`
}

// Validate validates this set price list record params body bulk pricing tiers items0
func (o *SetPriceListRecordParamsBodyBulkPricingTiersItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var setPriceListRecordParamsBodyBulkPricingTiersItems0TypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["fixed","price","percent"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		setPriceListRecordParamsBodyBulkPricingTiersItems0TypeTypePropEnum = append(setPriceListRecordParamsBodyBulkPricingTiersItems0TypeTypePropEnum, v)
	}
}

const (

	// SetPriceListRecordParamsBodyBulkPricingTiersItems0TypeFixed captures enum value "fixed"
	SetPriceListRecordParamsBodyBulkPricingTiersItems0TypeFixed string = "fixed"

	// SetPriceListRecordParamsBodyBulkPricingTiersItems0TypePrice captures enum value "price"
	SetPriceListRecordParamsBodyBulkPricingTiersItems0TypePrice string = "price"

	// SetPriceListRecordParamsBodyBulkPricingTiersItems0TypePercent captures enum value "percent"
	SetPriceListRecordParamsBodyBulkPricingTiersItems0TypePercent string = "percent"
)

// prop value enum
func (o *SetPriceListRecordParamsBodyBulkPricingTiersItems0) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, setPriceListRecordParamsBodyBulkPricingTiersItems0TypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *SetPriceListRecordParamsBodyBulkPricingTiersItems0) validateType(formats strfmt.Registry) error {

	if swag.IsZero(o.Type) { // not required
		return nil
	}

	// value enum
	if err := o.validateTypeEnum("type", "body", o.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SetPriceListRecordParamsBodyBulkPricingTiersItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetPriceListRecordParamsBodyBulkPricingTiersItems0) UnmarshalBinary(b []byte) error {
	var res SetPriceListRecordParamsBodyBulkPricingTiersItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SetPriceListRecordUnprocessableEntityBody Error Response
swagger:model SetPriceListRecordUnprocessableEntityBody
*/
type SetPriceListRecordUnprocessableEntityBody struct {

	// instance
	Instance string `json:"instance,omitempty"`

	// The HTTP status code.
	//
	Status int64 `json:"status,omitempty"`

	// The error title describing the particular error.
	//
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// Detailed Errors
	Errors map[string]string `json:"errors,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *SetPriceListRecordUnprocessableEntityBody) UnmarshalJSON(raw []byte) error {
	// SetPriceListRecordUnprocessableEntityBodyAO0
	var dataSetPriceListRecordUnprocessableEntityBodyAO0 struct {
		Instance string `json:"instance,omitempty"`

		Status int64 `json:"status,omitempty"`

		Title string `json:"title,omitempty"`

		Type string `json:"type,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataSetPriceListRecordUnprocessableEntityBodyAO0); err != nil {
		return err
	}

	o.Instance = dataSetPriceListRecordUnprocessableEntityBodyAO0.Instance

	o.Status = dataSetPriceListRecordUnprocessableEntityBodyAO0.Status

	o.Title = dataSetPriceListRecordUnprocessableEntityBodyAO0.Title

	o.Type = dataSetPriceListRecordUnprocessableEntityBodyAO0.Type

	// SetPriceListRecordUnprocessableEntityBodyAO1
	var dataSetPriceListRecordUnprocessableEntityBodyAO1 struct {
		Errors map[string]string `json:"errors,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataSetPriceListRecordUnprocessableEntityBodyAO1); err != nil {
		return err
	}

	o.Errors = dataSetPriceListRecordUnprocessableEntityBodyAO1.Errors

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o SetPriceListRecordUnprocessableEntityBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataSetPriceListRecordUnprocessableEntityBodyAO0 struct {
		Instance string `json:"instance,omitempty"`

		Status int64 `json:"status,omitempty"`

		Title string `json:"title,omitempty"`

		Type string `json:"type,omitempty"`
	}

	dataSetPriceListRecordUnprocessableEntityBodyAO0.Instance = o.Instance

	dataSetPriceListRecordUnprocessableEntityBodyAO0.Status = o.Status

	dataSetPriceListRecordUnprocessableEntityBodyAO0.Title = o.Title

	dataSetPriceListRecordUnprocessableEntityBodyAO0.Type = o.Type

	jsonDataSetPriceListRecordUnprocessableEntityBodyAO0, errSetPriceListRecordUnprocessableEntityBodyAO0 := swag.WriteJSON(dataSetPriceListRecordUnprocessableEntityBodyAO0)
	if errSetPriceListRecordUnprocessableEntityBodyAO0 != nil {
		return nil, errSetPriceListRecordUnprocessableEntityBodyAO0
	}
	_parts = append(_parts, jsonDataSetPriceListRecordUnprocessableEntityBodyAO0)
	var dataSetPriceListRecordUnprocessableEntityBodyAO1 struct {
		Errors map[string]string `json:"errors,omitempty"`
	}

	dataSetPriceListRecordUnprocessableEntityBodyAO1.Errors = o.Errors

	jsonDataSetPriceListRecordUnprocessableEntityBodyAO1, errSetPriceListRecordUnprocessableEntityBodyAO1 := swag.WriteJSON(dataSetPriceListRecordUnprocessableEntityBodyAO1)
	if errSetPriceListRecordUnprocessableEntityBodyAO1 != nil {
		return nil, errSetPriceListRecordUnprocessableEntityBodyAO1
	}
	_parts = append(_parts, jsonDataSetPriceListRecordUnprocessableEntityBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this set price list record unprocessable entity body
func (o *SetPriceListRecordUnprocessableEntityBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *SetPriceListRecordUnprocessableEntityBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetPriceListRecordUnprocessableEntityBody) UnmarshalBinary(b []byte) error {
	var res SetPriceListRecordUnprocessableEntityBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
