// Code generated by go-swagger; DO NOT EDIT.

package channel_listings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetChannelListingParams creates a new GetChannelListingParams object
// with the default values initialized.
func NewGetChannelListingParams() *GetChannelListingParams {
	var ()
	return &GetChannelListingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChannelListingParamsWithTimeout creates a new GetChannelListingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChannelListingParamsWithTimeout(timeout time.Duration) *GetChannelListingParams {
	var ()
	return &GetChannelListingParams{

		timeout: timeout,
	}
}

// NewGetChannelListingParamsWithContext creates a new GetChannelListingParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChannelListingParamsWithContext(ctx context.Context) *GetChannelListingParams {
	var ()
	return &GetChannelListingParams{

		Context: ctx,
	}
}

// NewGetChannelListingParamsWithHTTPClient creates a new GetChannelListingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChannelListingParamsWithHTTPClient(client *http.Client) *GetChannelListingParams {
	var ()
	return &GetChannelListingParams{
		HTTPClient: client,
	}
}

/*GetChannelListingParams contains all the parameters to send to the API endpoint
for the get channel listing operation typically these are written to a http.Request
*/
type GetChannelListingParams struct {

	/*ChannelID*/
	ChannelID int64
	/*ListingID*/
	ListingID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get channel listing params
func (o *GetChannelListingParams) WithTimeout(timeout time.Duration) *GetChannelListingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get channel listing params
func (o *GetChannelListingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get channel listing params
func (o *GetChannelListingParams) WithContext(ctx context.Context) *GetChannelListingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get channel listing params
func (o *GetChannelListingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get channel listing params
func (o *GetChannelListingParams) WithHTTPClient(client *http.Client) *GetChannelListingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get channel listing params
func (o *GetChannelListingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelID adds the channelID to the get channel listing params
func (o *GetChannelListingParams) WithChannelID(channelID int64) *GetChannelListingParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the get channel listing params
func (o *GetChannelListingParams) SetChannelID(channelID int64) {
	o.ChannelID = channelID
}

// WithListingID adds the listingID to the get channel listing params
func (o *GetChannelListingParams) WithListingID(listingID int64) *GetChannelListingParams {
	o.SetListingID(listingID)
	return o
}

// SetListingID adds the listingId to the get channel listing params
func (o *GetChannelListingParams) SetListingID(listingID int64) {
	o.ListingID = listingID
}

// WriteToRequest writes these params to a swagger request
func (o *GetChannelListingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channel_id
	if err := r.SetPathParam("channel_id", swag.FormatInt64(o.ChannelID)); err != nil {
		return err
	}

	// path param listing_id
	if err := r.SetPathParam("listing_id", swag.FormatInt64(o.ListingID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
