// Code generated by go-swagger; DO NOT EDIT.

package channel_listings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUpdateChannelListingsParams creates a new UpdateChannelListingsParams object
// with the default values initialized.
func NewUpdateChannelListingsParams() *UpdateChannelListingsParams {
	var ()
	return &UpdateChannelListingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateChannelListingsParamsWithTimeout creates a new UpdateChannelListingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateChannelListingsParamsWithTimeout(timeout time.Duration) *UpdateChannelListingsParams {
	var ()
	return &UpdateChannelListingsParams{

		timeout: timeout,
	}
}

// NewUpdateChannelListingsParamsWithContext creates a new UpdateChannelListingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateChannelListingsParamsWithContext(ctx context.Context) *UpdateChannelListingsParams {
	var ()
	return &UpdateChannelListingsParams{

		Context: ctx,
	}
}

// NewUpdateChannelListingsParamsWithHTTPClient creates a new UpdateChannelListingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateChannelListingsParamsWithHTTPClient(client *http.Client) *UpdateChannelListingsParams {
	var ()
	return &UpdateChannelListingsParams{
		HTTPClient: client,
	}
}

/*UpdateChannelListingsParams contains all the parameters to send to the API endpoint
for the update channel listings operation typically these are written to a http.Request
*/
type UpdateChannelListingsParams struct {

	/*Body*/
	Body []*UpdateChannelListingsParamsBodyItems0
	/*ChannelID*/
	ChannelID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update channel listings params
func (o *UpdateChannelListingsParams) WithTimeout(timeout time.Duration) *UpdateChannelListingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update channel listings params
func (o *UpdateChannelListingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update channel listings params
func (o *UpdateChannelListingsParams) WithContext(ctx context.Context) *UpdateChannelListingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update channel listings params
func (o *UpdateChannelListingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update channel listings params
func (o *UpdateChannelListingsParams) WithHTTPClient(client *http.Client) *UpdateChannelListingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update channel listings params
func (o *UpdateChannelListingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update channel listings params
func (o *UpdateChannelListingsParams) WithBody(body []*UpdateChannelListingsParamsBodyItems0) *UpdateChannelListingsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update channel listings params
func (o *UpdateChannelListingsParams) SetBody(body []*UpdateChannelListingsParamsBodyItems0) {
	o.Body = body
}

// WithChannelID adds the channelID to the update channel listings params
func (o *UpdateChannelListingsParams) WithChannelID(channelID int64) *UpdateChannelListingsParams {
	o.SetChannelID(channelID)
	return o
}

// SetChannelID adds the channelId to the update channel listings params
func (o *UpdateChannelListingsParams) SetChannelID(channelID int64) {
	o.ChannelID = channelID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateChannelListingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param channel_id
	if err := r.SetPathParam("channel_id", swag.FormatInt64(o.ChannelID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
